[project]
site_name = "PalmSens for Matlab"
site_description = "Matlab SDK for automating electrochemistry with PalmSens instruments"
site_author = "PalmSens BV"
repo_url = "https://github.com/palmsens/palmsens_sdk"
repo_name = "GitHub"
copyright = """
Copyright &copy; 2026 PalmSens BV
"""
docs_dir = "docs/zensical"

[project.theme]
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.plugins.mkdocstrings]
default_handler = "matlab"

[project.plugins.mkdocstrings.matlab]

[project.plugins.mkdocstrings.handlers.matlab.options]
docstring_style = "google"
# Discard first line of `__init__` method docstrings,
# useful when merging such docstrings into their parent class'.
# docstring_options = { "ignore_init_summary" = true }
# Tables are generally too large, lists will fix this.
docstring_section_style = "list"
# Enable relative crossrefs and scoped crossrefs, see Docstrings options.
relative_crossrefs = true
scoped_crossrefs = true
# Enable cross-references in signatures.
signature_crossrefs = true
# Unwrap actual types from `Annotated` type annotations.
unwrap_annotated = true
# Only render pulic symbols.
filters = "public"
# Comment the option otherwise to get the default filters.
# Show class inherited members.
inherited_members = true
# Render auto-generated summaries of attributes, functions, etc.
# at the start of each symbol's documentation.
summary = true
# For auto-generated pages, one module per page,
# make the module heading be the H1 heading of the page.
# heading_level = 1
# Render headings for parameters, making them linkable.
parameter_headings = true
# Render headings for type parameters too.
type_parameter_headings = true
# Always show the heading for the symbol you render with `:: = id`.
show_root_heading = true
# Only show the name of the symbols you inject render `:: = id`.
show_root_full_path = true
# Show the type of symbol (class, function, etc.) in the heading.
show_symbol_type_heading = true
# Show the type of symbol (class, function, etc.) in the table of contents.
show_symbol_type_toc = true
# Format code to 80 + 10% margin (Black and Ruff defaults)
# in signatures and attribute value code blocks.
# Needs Black/Ruff installed.
line_length = 96
# Merge signature and docstring of `__init__` methods
# into their parent class signature and docstring.
merge_init_into_class = true
# Render signatures and attribute values in a separate code block,
# below the symbol heading.
separate_signature = true
# Show type annotations in signatures.
show_signature_annotations = true
# Show type parameters in signatures.
show_signature_type_parameters = true
# Show backlinks to other documentation sections within each symbol.
backlinks = false  # crashes in linux
# Show base classes OR inheritance diagram.
show_bases = false
show_inheritance_diagram = false
