= Config

== pypalmsens.config

*Classes:*

* link:#pypalmsens.config.BaseSettings[*BaseSettings*] – Protocol to
provide generic methods for parameters.
* link:#pypalmsens.config.CurrentRanges[*CurrentRanges*] – Set the
autoranging current for a given method.
* link:#pypalmsens.config.PotentialRanges[*PotentialRanges*] – Set the
autoranging potential for a given method.
* link:#pypalmsens.config.Pretreatment[*Pretreatment*] – Set the
pretreatment settings for a given method.
* link:#pypalmsens.config.VersusOCP[*VersusOCP*] – Set the versus OCP
settings for a given method.
* link:#pypalmsens.config.BiPot[*BiPot*] – Set the bipot settings for a
given method.
* link:#pypalmsens.config.ELevel[*ELevel*] – Create a multi-step
amperometry level method object.
* link:#pypalmsens.config.PostMeasurement[*PostMeasurement*] – Set the
post measurement settings for a given method.
* link:#pypalmsens.config.CurrentLimits[*CurrentLimits*] – Set the limit
settings for a given method.
* link:#pypalmsens.config.PotentialLimits[*PotentialLimits*] – Set the
limit settings for a given method.
* link:#pypalmsens.config.ChargeLimits[*ChargeLimits*] – Set the charge
limit settings for a given method.
* link:#pypalmsens.config.IrDropCompensation[*IrDropCompensation*] – Set
the iR drop compensation settings for a given method.
* link:#pypalmsens.config.EquilibrationTriggers[*EquilibrationTriggers*]
– Set the trigger at equilibration settings for a given method.
* link:#pypalmsens.config.MeasurementTriggers[*MeasurementTriggers*] –
Set the trigger at measurement settings for a given method.
* link:#pypalmsens.config.Multiplexer[*Multiplexer*] – Set the
multiplexer settings for a given method.
* link:#pypalmsens.config.DataProcessing[*DataProcessing*] – Set the
data processing settings for a given method.
* link:#pypalmsens.config.General[*General*] – Sets general/other
settings for a given method.

=== BaseSettings

Bases: link:#typing.Protocol[Protocol]

Protocol to provide generic methods for parameters.

=== CurrentRanges

Bases: link:#pypalmsens.methods.settings.BaseSettings[BaseSettings]

Set the autoranging current for a given method.

*Attributes:*

* link:#pypalmsens.config.CurrentRanges.max[*max*]
(link:#pypalmsens.methods._shared.CURRENT_RANGE[CURRENT_RANGE]) –
* link:#pypalmsens.config.CurrentRanges.min[*min*]
(link:#pypalmsens.methods._shared.CURRENT_RANGE[CURRENT_RANGE]) –
* link:#pypalmsens.config.CurrentRanges.start[*start*]
(link:#pypalmsens.methods._shared.CURRENT_RANGE[CURRENT_RANGE]) –

==== max

[source,python]
----
max: CURRENT_RANGE = CURRENT_RANGE.cr_10_mA
----

==== min

[source,python]
----
min: CURRENT_RANGE = CURRENT_RANGE.cr_1_uA
----

==== start

[source,python]
----
start: CURRENT_RANGE = CURRENT_RANGE.cr_100_uA
----

=== PotentialRanges

Bases: link:#pypalmsens.methods.settings.BaseSettings[BaseSettings]

Set the autoranging potential for a given method.

*Attributes:*

* link:#pypalmsens.config.PotentialRanges.max[*max*]
(link:#pypalmsens.methods._shared.POTENTIAL_RANGE[POTENTIAL_RANGE]) –
* link:#pypalmsens.config.PotentialRanges.min[*min*]
(link:#pypalmsens.methods._shared.POTENTIAL_RANGE[POTENTIAL_RANGE]) –
* link:#pypalmsens.config.PotentialRanges.start[*start*]
(link:#pypalmsens.methods._shared.POTENTIAL_RANGE[POTENTIAL_RANGE]) –

==== max

[source,python]
----
max: POTENTIAL_RANGE = POTENTIAL_RANGE.pr_1_V
----

==== min

[source,python]
----
min: POTENTIAL_RANGE = POTENTIAL_RANGE.pr_1_mV
----

==== start

[source,python]
----
start: POTENTIAL_RANGE = POTENTIAL_RANGE.pr_1_V
----

=== Pretreatment

Bases: link:#pypalmsens.methods.settings.BaseSettings[BaseSettings]

Set the pretreatment settings for a given method.

*Attributes:*

* link:#pypalmsens.config.Pretreatment.deposition_potential[*deposition_potential*]
(link:#float[float]) –
* link:#pypalmsens.config.Pretreatment.deposition_time[*deposition_time*]
(link:#float[float]) –
* link:#pypalmsens.config.Pretreatment.conditioning_potential[*conditioning_potential*]
(link:#float[float]) –
* link:#pypalmsens.config.Pretreatment.conditioning_time[*conditioning_time*]
(link:#float[float]) –

==== deposition_potential

[source,python]
----
deposition_potential: float = 0.0
----

==== deposition_time

[source,python]
----
deposition_time: float = 0.0
----

==== conditioning_potential

[source,python]
----
conditioning_potential: float = 0.0
----

==== conditioning_time

[source,python]
----
conditioning_time: float = 0.0
----

=== VersusOCP

Bases: link:#pypalmsens.methods.settings.BaseSettings[BaseSettings]

Set the versus OCP settings for a given method.

*Attributes:*

* link:#pypalmsens.config.VersusOCP.mode[*mode*] (link:#int[int]) –
* link:#pypalmsens.config.VersusOCP.max_ocp_time[*max_ocp_time*]
(link:#float[float]) –
* link:#pypalmsens.config.VersusOCP.stability_criterion[*stability_criterion*]
(link:#int[int]) –

==== mode

[source,python]
----
mode: int = 0
----

==== max_ocp_time

[source,python]
----
max_ocp_time: float = 20.0
----

==== stability_criterion

[source,python]
----
stability_criterion: int = 0
----

=== BiPot

Bases: link:#pypalmsens.methods.settings.BaseSettings[BaseSettings]

Set the bipot settings for a given method.

*Attributes:*

* link:#pypalmsens.config.BiPot.mode[*mode*]
(link:#typing.Literal[Literal]['`constant`', '`offset`']) –
* link:#pypalmsens.config.BiPot.potential[*potential*]
(link:#float[float]) –
* link:#pypalmsens.config.BiPot.current_range_max[*current_range_max*]
(link:#pypalmsens.methods._shared.CURRENT_RANGE[CURRENT_RANGE]) –
* link:#pypalmsens.config.BiPot.current_range_min[*current_range_min*]
(link:#pypalmsens.methods._shared.CURRENT_RANGE[CURRENT_RANGE]) –
* link:#pypalmsens.config.BiPot.current_range_start[*current_range_start*]
(link:#pypalmsens.methods._shared.CURRENT_RANGE[CURRENT_RANGE]) –

==== mode

[source,python]
----
mode: Literal['constant', 'offset'] = 'constant'
----

==== potential

[source,python]
----
potential: float = 0.0
----

==== current_range_max

[source,python]
----
current_range_max: CURRENT_RANGE = CURRENT_RANGE.cr_10_mA
----

==== current_range_min

[source,python]
----
current_range_min: CURRENT_RANGE = CURRENT_RANGE.cr_1_uA
----

==== current_range_start

[source,python]
----
current_range_start: CURRENT_RANGE = CURRENT_RANGE.cr_100_uA
----

=== ELevel

[source,python]
----
ELevel(level=0.0, duration=1.0, record=True, use_limit_current_max=False, limit_current_max=0.0, use_limit_current_min=False, limit_current_min=0.0, trigger_at_level=False, trigger_at_level_lines=(False, False, False, False))
----

Create a multi-step amperometry level method object.

*Functions:*

* link:#pypalmsens.config.ELevel.to_psobj[*to_psobj*] –
* link:#pypalmsens.config.ELevel.from_psobj[*from_psobj*] – Construct
ELevel dataclass from PalmSens.Techniques.ELevel object.

*Attributes:*

* link:#pypalmsens.config.ELevel.level[*level*] (link:#float[float]) –
* link:#pypalmsens.config.ELevel.duration[*duration*]
(link:#float[float]) –
* link:#pypalmsens.config.ELevel.record[*record*] (link:#bool[bool]) –
* link:#pypalmsens.config.ELevel.use_limit_current_max[*use_limit_current_max*]
(link:#bool[bool]) –
* link:#pypalmsens.config.ELevel.limit_current_max[*limit_current_max*]
(link:#float[float]) –
* link:#pypalmsens.config.ELevel.use_limit_current_min[*use_limit_current_min*]
(link:#bool[bool]) –
* link:#pypalmsens.config.ELevel.limit_current_min[*limit_current_min*]
(link:#float[float]) –
* link:#pypalmsens.config.ELevel.trigger_at_level[*trigger_at_level*]
(link:#bool[bool]) –
* link:#pypalmsens.config.ELevel.trigger_at_level_lines[*trigger_at_level_lines*]
(link:#tuple[tuple][link:#bool[bool], link:#bool[bool],
link:#bool[bool], link:#bool[bool]]) –

==== level

[source,python]
----
level: float = 0.0
----

==== duration

[source,python]
----
duration: float = 1.0
----

==== record

[source,python]
----
record: bool = True
----

==== use_limit_current_max

[source,python]
----
use_limit_current_max: bool = False
----

==== limit_current_max

[source,python]
----
limit_current_max: float = 0.0
----

==== use_limit_current_min

[source,python]
----
use_limit_current_min: bool = False
----

==== limit_current_min

[source,python]
----
limit_current_min: float = 0.0
----

==== trigger_at_level

[source,python]
----
trigger_at_level: bool = False
----

==== trigger_at_level_lines

[source,python]
----
trigger_at_level_lines: tuple[bool, bool, bool, bool] = (False, False, False, False)
----

==== to_psobj

[source,python]
----
to_psobj()
----

==== from_psobj

[source,python]
----
from_psobj(psobj)
----

Construct ELevel dataclass from PalmSens.Techniques.ELevel object.

=== PostMeasurement

Bases: link:#pypalmsens.methods.settings.BaseSettings[BaseSettings]

Set the post measurement settings for a given method.

*Attributes:*

* link:#pypalmsens.config.PostMeasurement.cell_on_after_measurement[*cell_on_after_measurement*]
(link:#bool[bool]) –
* link:#pypalmsens.config.PostMeasurement.standby_potential[*standby_potential*]
(link:#float[float]) –
* link:#pypalmsens.config.PostMeasurement.standby_time[*standby_time*]
(link:#float[float]) –

==== cell_on_after_measurement

[source,python]
----
cell_on_after_measurement: bool = False
----

==== standby_potential

[source,python]
----
standby_potential: float = 0.0
----

==== standby_time

[source,python]
----
standby_time: float = 0.0
----

=== CurrentLimits

Bases: link:#pypalmsens.methods.settings.BaseSettings[BaseSettings]

Set the limit settings for a given method.

*Attributes:*

* link:#pypalmsens.config.CurrentLimits.use_limit_max[*use_limit_max*]
(link:#bool[bool]) –
* link:#pypalmsens.config.CurrentLimits.limit_max[*limit_max*]
(link:#float[float]) –
* link:#pypalmsens.config.CurrentLimits.use_limit_min[*use_limit_min*]
(link:#bool[bool]) –
* link:#pypalmsens.config.CurrentLimits.limit_min[*limit_min*]
(link:#float[float]) –

==== use_limit_max

[source,python]
----
use_limit_max: bool = False
----

==== limit_max

[source,python]
----
limit_max: float = 0.0
----

==== use_limit_min

[source,python]
----
use_limit_min: bool = False
----

==== limit_min

[source,python]
----
limit_min: float = 0.0
----

=== PotentialLimits

Bases: link:#pypalmsens.methods.settings.BaseSettings[BaseSettings]

Set the limit settings for a given method.

*Attributes:*

* link:#pypalmsens.config.PotentialLimits.use_limit_max[*use_limit_max*]
(link:#bool[bool]) –
* link:#pypalmsens.config.PotentialLimits.limit_max[*limit_max*]
(link:#float[float]) –
* link:#pypalmsens.config.PotentialLimits.use_limit_min[*use_limit_min*]
(link:#bool[bool]) –
* link:#pypalmsens.config.PotentialLimits.limit_min[*limit_min*]
(link:#float[float]) –

==== use_limit_max

[source,python]
----
use_limit_max: bool = False
----

==== limit_max

[source,python]
----
limit_max: float = 0.0
----

==== use_limit_min

[source,python]
----
use_limit_min: bool = False
----

==== limit_min

[source,python]
----
limit_min: float = 0.0
----

=== ChargeLimits

Bases: link:#pypalmsens.methods.settings.BaseSettings[BaseSettings]

Set the charge limit settings for a given method.

*Attributes:*

* link:#pypalmsens.config.ChargeLimits.use_limit_max[*use_limit_max*]
(link:#bool[bool]) –
* link:#pypalmsens.config.ChargeLimits.limit_max[*limit_max*]
(link:#float[float]) –
* link:#pypalmsens.config.ChargeLimits.use_limit_min[*use_limit_min*]
(link:#bool[bool]) –
* link:#pypalmsens.config.ChargeLimits.limit_min[*limit_min*]
(link:#float[float]) –

==== use_limit_max

[source,python]
----
use_limit_max: bool = False
----

==== limit_max

[source,python]
----
limit_max: float = 0.0
----

==== use_limit_min

[source,python]
----
use_limit_min: bool = False
----

==== limit_min

[source,python]
----
limit_min: float = 0.0
----

=== IrDropCompensation

Bases: link:#pypalmsens.methods.settings.BaseSettings[BaseSettings]

Set the iR drop compensation settings for a given method.

*Attributes:*

* link:#pypalmsens.config.IrDropCompensation.enable[*enable*]
(link:#bool[bool]) –
* link:#pypalmsens.config.IrDropCompensation.ir_compensation[*ir_compensation*]
(link:#float[float]) –

==== enable

[source,python]
----
enable: bool = False
----

==== ir_compensation

[source,python]
----
ir_compensation: float = 0.0
----

=== EquilibrationTriggers

Bases: link:#pypalmsens.methods.settings.BaseSettings[BaseSettings]

Set the trigger at equilibration settings for a given method.

*Attributes:*

* link:#pypalmsens.config.EquilibrationTriggers.enable[*enable*]
(link:#bool[bool]) –
* link:#pypalmsens.config.EquilibrationTriggers.d0[*d0*]
(link:#bool[bool]) –
* link:#pypalmsens.config.EquilibrationTriggers.d1[*d1*]
(link:#bool[bool]) –
* link:#pypalmsens.config.EquilibrationTriggers.d2[*d2*]
(link:#bool[bool]) –
* link:#pypalmsens.config.EquilibrationTriggers.d3[*d3*]
(link:#bool[bool]) –

==== enable

[source,python]
----
enable: bool = False
----

==== d0

[source,python]
----
d0: bool = False
----

==== d1

[source,python]
----
d1: bool = False
----

==== d2

[source,python]
----
d2: bool = False
----

==== d3

[source,python]
----
d3: bool = False
----

=== MeasurementTriggers

Bases: link:#pypalmsens.methods.settings.BaseSettings[BaseSettings]

Set the trigger at measurement settings for a given method.

*Attributes:*

* link:#pypalmsens.config.MeasurementTriggers.enable[*enable*]
(link:#bool[bool]) –
* link:#pypalmsens.config.MeasurementTriggers.d0[*d0*]
(link:#bool[bool]) –
* link:#pypalmsens.config.MeasurementTriggers.d1[*d1*]
(link:#bool[bool]) –
* link:#pypalmsens.config.MeasurementTriggers.d2[*d2*]
(link:#bool[bool]) –
* link:#pypalmsens.config.MeasurementTriggers.d3[*d3*]
(link:#bool[bool]) –

==== enable

[source,python]
----
enable: bool = False
----

==== d0

[source,python]
----
d0: bool = False
----

==== d1

[source,python]
----
d1: bool = False
----

==== d2

[source,python]
----
d2: bool = False
----

==== d3

[source,python]
----
d3: bool = False
----

=== Multiplexer

Bases: link:#pypalmsens.methods.settings.BaseSettings[BaseSettings]

Set the multiplexer settings for a given method.

*Attributes:*

* link:#pypalmsens.config.Multiplexer.mode[*mode*]
(link:#typing.Literal[Literal]['`none`', '`consecutive`',
'`alternate`']) –
* link:#pypalmsens.config.Multiplexer.channels[*channels*]
(link:#list[list][link:#int[int]]) –
* link:#pypalmsens.config.Multiplexer.connect_sense_to_working_electrode[*connect_sense_to_working_electrode*]
(link:#bool[bool]) –
* link:#pypalmsens.config.Multiplexer.combine_reference_and_counter_electrodes[*combine_reference_and_counter_electrodes*]
(link:#bool[bool]) –
* link:#pypalmsens.config.Multiplexer.use_channel_1_reference_and_counter_electrodes[*use_channel_1_reference_and_counter_electrodes*]
(link:#bool[bool]) –
* link:#pypalmsens.config.Multiplexer.set_unselected_channel_working_electrode[*set_unselected_channel_working_electrode*]
(link:#int[int]) –

==== mode

[source,python]
----
mode: Literal['none', 'consecutive', 'alternate'] = 'none'
----

==== channels

[source,python]
----
channels: list[int] = attrs.field(factory=list)
----

==== connect_sense_to_working_electrode

[source,python]
----
connect_sense_to_working_electrode: bool = False
----

==== combine_reference_and_counter_electrodes

[source,python]
----
combine_reference_and_counter_electrodes: bool = False
----

==== use_channel_1_reference_and_counter_electrodes

[source,python]
----
use_channel_1_reference_and_counter_electrodes: bool = False
----

==== set_unselected_channel_working_electrode

[source,python]
----
set_unselected_channel_working_electrode: int = 0
----

=== DataProcessing

Bases: link:#pypalmsens.methods.settings.BaseSettings[BaseSettings]

Set the data processing settings for a given method.

*Attributes:*

* link:#pypalmsens.config.DataProcessing.smooth_level[*smooth_level*]
(link:#int[int]) –
* link:#pypalmsens.config.DataProcessing.min_height[*min_height*]
(link:#float[float]) –
* link:#pypalmsens.config.DataProcessing.min_width[*min_width*]
(link:#float[float]) –

==== smooth_level

[source,python]
----
smooth_level: int = 0
----

==== min_height

[source,python]
----
min_height: float = 0.0
----

==== min_width

[source,python]
----
min_width: float = 0.1
----

=== General

Bases: link:#pypalmsens.methods.settings.BaseSettings[BaseSettings]

Sets general/other settings for a given method.

*Attributes:*

* link:#pypalmsens.config.General.save_on_internal_storage[*save_on_internal_storage*]
(link:#bool[bool]) –
* link:#pypalmsens.config.General.use_hardware_sync[*use_hardware_sync*]
(link:#bool[bool]) –
* link:#pypalmsens.config.General.notes[*notes*] (link:#str[str]) –
* link:#pypalmsens.config.General.power_frequency[*power_frequency*]
(link:#typing.Literal[Literal][50, 60]) –

==== save_on_internal_storage

[source,python]
----
save_on_internal_storage: bool = False
----

==== use_hardware_sync

[source,python]
----
use_hardware_sync: bool = False
----

==== notes

[source,python]
----
notes: str = ''
----

==== power_frequency

[source,python]
----
power_frequency: Literal[50, 60] = 50
----
