= PyPalmSens: Python SDK for PalmSens devices

PyPalmSens is a Python library for automating electrochemistry experiments with your PalmSens instruments.
PyPalmSens is built on top of the xref:ROOT:index.adoc[PalmSens .NET libraries].
It provides an intuitive Python API, making it straightforward to integrate into your Python workflows.

With PyPalmSens, you can:

- Connect to one or more instruments/channels
- Automate electrochemistry measurements
- Access and process measured data
- Analyze and manipulate data
- Perform peak detection
- Do Equivalent Circuit Fitting on impedance data
- Manually control of the cell
- Read and write method and data files

To install:

```bash
pip install pypalmsens
```

PyPalmSens requires the .NET runtime to be installed.
For specific installation instructions for your platform, see xref:installation.adoc[]

== Getting started

The following example shows how to discover devices and manually read out the current.

```python
from pypalmsens import instruments
from pypalmsens.methods import CURRENT_RANGE

manager = instruments.InstrumentManager()

available_instruments = instruments.discover_instruments()
manager.connect(available_instruments[0])

# enable cell
manager.set_cell(True)
# set potential to 1 V
manager.set_potential(1)
# set current range to 1 mA
manager.set_current_range(CURRENT_RANGE.cr_1_mA)

current = manager.read_current()
print(f'{current=} µA')

manager.set_cell(False)
manager.disconnect()
```

Set up and measure a simple chronoamperometry experiment:

```python
from pypalmsens import instruments
from pypalmsens.methods import ChronoAmperometryParameters

manager = instruments.InstrumentManager()

available_instruments = instruments.discover_instruments()
manager.connect(available_instruments[0])

method = ChronoAmperometryParameters(
    interval_time=0.01,
    potential=1.0,
    run_time=10.0,
)

measurement = manager.measure(method)
manager.disconnect()
```

Analyze a previous measurement with https://pandas.pydata.org/[pandas]:

```python
import pandas as pd
from pypalmsens import load_session_file

measurements = load_session_file('Demo CV DPV EIS IS-C electrode.pssession')

frames = []
frame_names = []

for measurement in measurements:
    frames.append(measurement.dataset.to_dataframe())
    frame_names.append(measurement.title)

df = pd.concat(frames, keys=frame_names)
print(df)
```

== Compatible devices and firmware

The following devices and firmwares are supported:

[cols=",",options="header",]
|===
|Device |Minimum required firmware version
|EmStat |3.7
|EmStat2 |7.7
|EmStat3 |7.7
|EmStat3{plus} |7.7
|EmStat4 |1.3
|EmStat4T |1.4
|EmStat Go |7.7
|EmStat Pico |1.5
|Sensit Smart |1.5
|Sensit BT |1.5
|Sensit Wearable |1.5
|MultiEmStat3 |7.7
|MultiEmStat4 |1.3
|PalmSens3 |2.8
|PalmSens4 |1.7
|MultiPalmSens4 |1.7
|===

== Example programs

The following examples are included in the https://github.com/PalmSens/PalmSens_SDK/tree/main/python[examples directory].

`load_save_data.py`::
Shows how to load/save methods and measurements and how to inspect the data.
`manual_control.py`::
Shows how to discover devices, establish a connection and control an instrument manually.
`manual_control_async.py`::
Shows how to discover devices, establish a connection and control an instrument manually using the asynchronous instrument manager.
`measurement_CA.py`::
Shows how to configure and run a chronoamperometry measurement.
`measurement_CA_async.py`::
Shows how to configure and run a chronoamperometry measurement using the asynchronous instrument manager.
`measurement_CV.py`::
Shows how to configure and run a cyclic voltammetry measurement.
`measurement_EIS.py`::
Shows how to configure and run a EIS measurement.
`measurement_MethodSCRIPT_sandbox.py`::
Shows how to configure and run a MethodSCRIPT Sandbox measurement.
`measurement_stream_to_csv.py`::
Shows how to configure and run a chronoamperometry measurement and write the results to a CSV file in real-time.
`measurement_SWV_vs_OCP.py`::
Shows how to configure and run a square wave voltammetry measurement versus OCP.
`multiplexer.py`::
Shows how to configure and control a multiplexer and run consecutive and alternating multiplexer measurments.
`multichannel_measurement.py`::
Shows how to connect to a collection of instruments and run a chronoamperometry measurement on all channels simultaneously.
`multichannel_measurement_custom_loop.py`::
Shows how to run and configure a sequence of measurements on a collection of channels simultaneously.
`multichannel_HW_sync.py`::
Shows how to connect to a collection of instruments and run a chronopotentiometry measurement on all channels simultaneously using hardware synchronization.
