= Instrument management

== pypalmsens

*Classes:*

* link:#pypalmsens.InstrumentManager[*InstrumentManager*] – Instrument
manager for PalmSens instruments.
* link:#pypalmsens.InstrumentManagerAsync[*InstrumentManagerAsync*] –
Asynchronous instrument manager for PalmSens instruments.

*Functions:*

* link:#pypalmsens.connect[*connect*] – Connect to instrument and return
InstrumentManager.
* link:#pypalmsens.connect_async[*connect_async*] – Connect to
instrument and return InstrumentManagerAsync.
* link:#pypalmsens.discover[*discover*] – Discover instruments.
* link:#pypalmsens.discover_async[*discover_async*] – Discover
instruments.

=== InstrumentManager

[source,python]
----
InstrumentManager(instrument, *, callback=None)
----

Instrument manager for PalmSens instruments.

*Parameters:*

* *instrument*
(link:#pypalmsens._instruments._common.Instrument[Instrument]) –
Instrument to connect to, use `+discover()+` to find connected
instruments.
* *callback*
(link:#typing.Optional[Optional][link:#pypalmsens._instruments._common.Callback[Callback]])
– If specified, call this function on every new set of data points. New
data points are batched, and contain all points since the last time it
was called. Each point is a dictionary containing frequency,z_re, z_im
for impedimetric techniques and index, x, x_unit and x_type, y, y_unit
and y_type for non-impedimetric techniques.

*Functions:*

* link:#pypalmsens.InstrumentManager.is_connected[*is_connected*] –
Return True if an instrument connection exists.
* link:#pypalmsens.InstrumentManager.connect[*connect*] –
* link:#pypalmsens.InstrumentManager.set_cell[*set_cell*] –
* link:#pypalmsens.InstrumentManager.set_potential[*set_potential*] –
* link:#pypalmsens.InstrumentManager.set_current_range[*set_current_range*]
–
* link:#pypalmsens.InstrumentManager.read_current[*read_current*] –
* link:#pypalmsens.InstrumentManager.read_potential[*read_potential*] –
* link:#pypalmsens.InstrumentManager.get_instrument_serial[*get_instrument_serial*]
–
* link:#pypalmsens.InstrumentManager.validate_method[*validate_method*]
–
* link:#pypalmsens.InstrumentManager.measure[*measure*] –
* link:#pypalmsens.InstrumentManager.wait_digital_trigger[*wait_digital_trigger*]
–
* link:#pypalmsens.InstrumentManager.abort[*abort*] –
* link:#pypalmsens.InstrumentManager.initialize_multiplexer[*initialize_multiplexer*]
– Initialize the multiplexer. Returns the number of available
multiplexer
* link:#pypalmsens.InstrumentManager.set_mux8r2_settings[*set_mux8r2_settings*]
– Set the settings for the Mux8R2 multiplexer.
* link:#pypalmsens.InstrumentManager.set_multiplexer_channel[*set_multiplexer_channel*]
–
* link:#pypalmsens.InstrumentManager.disconnect[*disconnect*] –

*Attributes:*

* link:#pypalmsens.InstrumentManager.callback[*callback*] –
* link:#pypalmsens.InstrumentManager.instrument[*instrument*] –

==== callback

[source,python]
----
callback = callback
----

==== instrument

[source,python]
----
instrument = instrument
----

==== is_connected

[source,python]
----
is_connected()
----

Return True if an instrument connection exists.

==== connect

[source,python]
----
connect()
----

==== set_cell

[source,python]
----
set_cell(cell_on)
----

==== set_potential

[source,python]
----
set_potential(potential)
----

==== set_current_range

[source,python]
----
set_current_range(current_range)
----

==== read_current

[source,python]
----
read_current()
----

==== read_potential

[source,python]
----
read_potential()
----

==== get_instrument_serial

[source,python]
----
get_instrument_serial()
----

==== validate_method

[source,python]
----
validate_method(method)
----

==== measure

[source,python]
----
measure(parameters)
----

==== wait_digital_trigger

[source,python]
----
wait_digital_trigger(wait_for_high)
----

==== abort

[source,python]
----
abort()
----

==== initialize_multiplexer

[source,python]
----
initialize_multiplexer(mux_model)
----

Initialize the multiplexer. Returns the number of available multiplexer
channels.

:param mux_model: The model of the multiplexer. 0 = 8 channel, 1 = 16
channel, 2 = 32 channel.

==== set_mux8r2_settings

[source,python]
----
set_mux8r2_settings(connect_sense_to_working_electrode=False, combine_reference_and_counter_electrodes=False, use_channel_1_reference_and_counter_electrodes=False, set_unselected_channel_working_electrode=0)
----

Set the settings for the Mux8R2 multiplexer.

*Parameters:*

* *connect_sense_to_working_electrode* (link:#bool[bool]) – Connect the
sense electrode to the working electrode. Default is False.
* *combine_reference_and_counter_electrodes* (link:#bool[bool]) –
Combine the reference and counter electrodes. Default is False.
* *use_channel_1_reference_and_counter_electrodes* (link:#bool[bool]) –
Use channel 1 reference and counter electrodes for all working
electrodes. Default is False.
* *set_unselected_channel_working_electrode* (link:#int[int]) – Set the
unselected channel working electrode to disconnected/floating (0),
ground (1), or standby potential (2). Default is 0.

==== set_multiplexer_channel

[source,python]
----
set_multiplexer_channel(channel)
----

==== disconnect

[source,python]
----
disconnect()
----

=== InstrumentManagerAsync

[source,python]
----
InstrumentManagerAsync(instrument, *, callback=None)
----

Asynchronous instrument manager for PalmSens instruments.

*Parameters:*

* *instrument* – Instrument to connect to, use `+discover()+` to find
connected instruments.
* *callback*
(link:#typing.Optional[Optional][link:#pypalmsens._instruments._common.Callback[Callback]])
– If specified, call this function on every new set of data points. New
data points are batched, and contain all points since the last time it
was called. Each point is a dictionary containing frequency,z_re, z_im
for impedimetric techniques and index, x, x_unit and x_type, y, y_unit
and y_type for non-impedimetric techniques.

*Functions:*

* link:#pypalmsens.InstrumentManagerAsync.is_connected[*is_connected*] –
* link:#pypalmsens.InstrumentManagerAsync.connect[*connect*] –
* link:#pypalmsens.InstrumentManagerAsync.set_cell[*set_cell*] –
* link:#pypalmsens.InstrumentManagerAsync.set_potential[*set_potential*]
–
* link:#pypalmsens.InstrumentManagerAsync.set_current_range[*set_current_range*]
–
* link:#pypalmsens.InstrumentManagerAsync.read_current[*read_current*] –
* link:#pypalmsens.InstrumentManagerAsync.read_potential[*read_potential*]
–
* link:#pypalmsens.InstrumentManagerAsync.get_instrument_serial[*get_instrument_serial*]
–
* link:#pypalmsens.InstrumentManagerAsync.validate_method[*validate_method*]
–
* link:#pypalmsens.InstrumentManagerAsync.measure[*measure*] –
* link:#pypalmsens.InstrumentManagerAsync.initiate_hardware_sync_follower_channel[*initiate_hardware_sync_follower_channel*]
–
* link:#pypalmsens.InstrumentManagerAsync.wait_digital_trigger[*wait_digital_trigger*]
–
* link:#pypalmsens.InstrumentManagerAsync.abort[*abort*] –
* link:#pypalmsens.InstrumentManagerAsync.initialize_multiplexer[*initialize_multiplexer*]
– Initialize the multiplexer. Returns the number of available
multiplexer
* link:#pypalmsens.InstrumentManagerAsync.set_mux8r2_settings[*set_mux8r2_settings*]
– Set the settings for the Mux8R2 multiplexer.
* link:#pypalmsens.InstrumentManagerAsync.set_multiplexer_channel[*set_multiplexer_channel*]
–
* link:#pypalmsens.InstrumentManagerAsync.disconnect[*disconnect*] –

*Attributes:*

* link:#pypalmsens.InstrumentManagerAsync.callback[*callback*] –
* link:#pypalmsens.InstrumentManagerAsync.instrument[*instrument*] –

==== callback

[source,python]
----
callback = callback
----

==== instrument

[source,python]
----
instrument = instrument
----

==== is_connected

[source,python]
----
is_connected()
----

==== connect

[source,python]
----
connect()
----

==== set_cell

[source,python]
----
set_cell(cell_on)
----

==== set_potential

[source,python]
----
set_potential(potential)
----

==== set_current_range

[source,python]
----
set_current_range(current_range)
----

==== read_current

[source,python]
----
read_current()
----

==== read_potential

[source,python]
----
read_potential()
----

==== get_instrument_serial

[source,python]
----
get_instrument_serial()
----

==== validate_method

[source,python]
----
validate_method(method)
----

==== measure

[source,python]
----
measure(parameters, hardware_sync_initiated_event=None)
----

==== initiate_hardware_sync_follower_channel

[source,python]
----
initiate_hardware_sync_follower_channel(method)
----

==== wait_digital_trigger

[source,python]
----
wait_digital_trigger(wait_for_high)
----

==== abort

[source,python]
----
abort()
----

==== initialize_multiplexer

[source,python]
----
initialize_multiplexer(mux_model)
----

Initialize the multiplexer. Returns the number of available multiplexer
channels.

:param mux_model: The model of the multiplexer. 0 = 8 channel, 1 = 16
channel, 2 = 32 channel.

==== set_mux8r2_settings

[source,python]
----
set_mux8r2_settings(connect_sense_to_working_electrode=False, combine_reference_and_counter_electrodes=False, use_channel_1_reference_and_counter_electrodes=False, set_unselected_channel_working_electrode=0)
----

Set the settings for the Mux8R2 multiplexer.

*Parameters:*

* *connect_sense_to_working_electrode* (link:#bool[bool]) – Connect the
sense electrode to the working electrode. Default is False.
* *combine_reference_and_counter_electrodes* (link:#bool[bool]) –
Combine the reference and counter electrodes. Default is False.
* *use_channel_1_reference_and_counter_electrodes* (link:#bool[bool]) –
Use channel 1 reference and counter electrodes for all working
electrodes. Default is False.
* *set_unselected_channel_working_electrode* (link:#int[int]) – Set the
unselected channel working electrode to disconnected/floating (0),
ground (1), or standby potential (2). Default is 0.

==== set_multiplexer_channel

[source,python]
----
set_multiplexer_channel(channel)
----

==== disconnect

[source,python]
----
disconnect()
----

=== connect

[source,python]
----
connect(instrument=None)
----

Connect to instrument and return InstrumentManager.

*Parameters:*

* *instrument*
(link:#pypalmsens._instruments._common.Instrument[Instrument]) – Connect
to this instrument. If not specified, automatically discover and connect
to the first instrument.

*Returns:*

* *manager*
(link:#pypalmsens._instruments._instrument_manager.InstrumentManager[InstrumentManager])
– Return instance of `+InstrumentManager+` connected to the given
instrument. The connection will be terminated after the context ends.

=== connect_async

[source,python]
----
connect_async(instrument=None)
----

Connect to instrument and return InstrumentManagerAsync.

*Parameters:*

* *instrument*
(link:#pypalmsens._instruments._common.Instrument[Instrument]) – Connect
to this instrument. If not specified, automatically discover and connect
to the first instrument.

*Returns:*

* *manager*
(link:#pypalmsens._instruments._instrument_manager_async.InstrumentManagerAsync[InstrumentManagerAsync])
– Return instance of `+InstrumentManagerAsync+` connected to the given
instrument. The connection will be terminated after the context ends.

=== discover

[source,python]
----
discover(ftdi=False, usbcdc=True, bluetooth=False, serial=True)
----

Discover instruments.

*Parameters:*

* *ftdi* (link:#bool[bool]) – If True, discover ftdi devices
* *usbcdc* (link:#bool[bool]) – If True, discover usbcdc devices
(Windows only)
* *bluetooth* (link:#bool[bool]) – If True, discover bluetooth devices
(Windows only)
* *serial* (link:#bool[bool]) – If True, discover serial devices

=== discover_async

[source,python]
----
discover_async(ftdi=False, usbcdc=True, bluetooth=False, serial=True)
----

Discover instruments.

*Parameters:*

* *ftdi* (link:#bool[bool]) – If True, discover ftdi devices
* *usbcdc* (link:#bool[bool]) – If True, discover usbcdc devices
(Windows only)
* *bluetooth* (link:#bool[bool]) – If True, discover bluetooth devices
(Windows only)
