== pypalmsens.fitting

This module contains the public api for circuit fitting.

*Classes:*

* link:#pypalmsens.fitting.Parameter[*Parameter*] – Set or update
Parameter attributes.
* link:#pypalmsens.fitting.Parameters[*Parameters*] – Tuple-like
container class for parameters.
* link:#pypalmsens.fitting.FitResult[*FitResult*] – Container for
fitting results.
* link:#pypalmsens.fitting.CircuitModel[*CircuitModel*] – Fit an
equivalent circuit model.

=== Parameter

[source,python]
----
Parameter(symbol, value=None, min=None, max=None, fixed=None)
----

Set or update Parameter attributes.

*Attributes:*

* link:#pypalmsens.fitting.Parameter.symbol[*symbol*] (link:#str[str]) –
Name of the parameter (not used in minimization).
* link:#pypalmsens.fitting.Parameter.value[*value*]
(link:#typing.Optional[Optional][link:#float[float]]) – Initial value of
the parameter.
* link:#pypalmsens.fitting.Parameter.min[*min*]
(link:#typing.Optional[Optional][link:#float[float]]) – Minimum (lower
bound) for the parameter.
* link:#pypalmsens.fitting.Parameter.max[*max*]
(link:#typing.Optional[Optional][link:#float[float]]) – Maximum (upper
bound) for the parameter.
* link:#pypalmsens.fitting.Parameter.fixed[*fixed*]
(link:#typing.Optional[Optional][link:#bool[bool]]) – If True, fix the
value for this parameter.

==== symbol

[source,python]
----
symbol: str
----

Name of the parameter (not used in minimization).

==== value

[source,python]
----
value: Optional[float] = None
----

Initial value of the parameter.

==== min

[source,python]
----
min: Optional[float] = None
----

Minimum (lower bound) for the parameter.

==== max

[source,python]
----
max: Optional[float] = None
----

Maximum (upper bound) for the parameter.

==== fixed

[source,python]
----
fixed: Optional[bool] = None
----

If True, fix the value for this parameter.

=== Parameters

[source,python]
----
Parameters(cdc)
----

Tuple-like container class for parameters.

This class is instantiated from the CDC code and contains default
parameters. This ensures that the length and type of parameters match
that of `+CircuitModel+`. Update the parameters in this class and pass
to `+CircuitModel.fit()+`.

*Parameters:*

* *cdc* (link:#str[str]) – Genererate fitting parameters for this CDC.

*Attributes:*

* link:#pypalmsens.fitting.Parameters.cdc[*cdc*] – CDC code used to
generate parameter listing.

==== cdc

[source,python]
----
cdc = cdc
----

CDC code used to generate parameter listing.

=== FitResult

[source,python]
----
FitResult(cdc, parameters, error, chisq, n_iter, exit_code)
----

Container for fitting results.

*Functions:*

* link:#pypalmsens.fitting.FitResult.from_psfitresult[*from_psfitresult*]
– Construct fitresult from SDK FitResult.
* link:#pypalmsens.fitting.FitResult.from_eisdata[*from_eisdata*] –
Construct fitresulf from EISData.
* link:#pypalmsens.fitting.FitResult.get_psmodel[*get_psmodel*] – Get
SDK Circuit model object
* link:#pypalmsens.fitting.FitResult.get_nyquist[*get_nyquist*] –
Calculate observed and calculated nyquist curves.
* link:#pypalmsens.fitting.FitResult.get_bode_z[*get_bode_z*] –
Calculate observed and calculated Bode curve Z vs Frequency.
* link:#pypalmsens.fitting.FitResult.get_bode_phase[*get_bode_phase*] –
Calculate observed and calculated Bode curve phase vs Frequency.
* link:#pypalmsens.fitting.FitResult.plot_nyquist[*plot_nyquist*] – Make
nyquist plot using matplotlib.
* link:#pypalmsens.fitting.FitResult.plot_bode[*plot_bode*] – Make bode
plot using matplotlib.

*Attributes:*

* link:#pypalmsens.fitting.FitResult.cdc[*cdc*] (link:#str[str]) –
Circuit model CDC values.
* link:#pypalmsens.fitting.FitResult.parameters[*parameters*]
(link:#list[list][link:#float[float]]) – Optimized parameters for CDC.
* link:#pypalmsens.fitting.FitResult.error[*error*]
(link:#list[list][link:#float[float]]) – Error (%) on parameters.
* link:#pypalmsens.fitting.FitResult.chisq[*chisq*] (link:#float[float])
– Chi-squared goodness of fit statistic.
* link:#pypalmsens.fitting.FitResult.n_iter[*n_iter*] (link:#int[int]) –
Total number of iterations.
* link:#pypalmsens.fitting.FitResult.exit_code[*exit_code*]
(link:#str[str]) – Exit code for the minimization.

==== cdc

[source,python]
----
cdc: str
----

Circuit model CDC values.

==== parameters

[source,python]
----
parameters: list[float]
----

Optimized parameters for CDC.

==== error

[source,python]
----
error: list[float]
----

Error (%) on parameters.

==== chisq

[source,python]
----
chisq: float
----

Chi-squared goodness of fit statistic.

==== n_iter

[source,python]
----
n_iter: int
----

Total number of iterations.

==== exit_code

[source,python]
----
exit_code: str
----

Exit code for the minimization.

==== from_psfitresult

[source,python]
----
from_psfitresult(result, cdc)
----

Construct fitresult from SDK FitResult.

==== from_eisdata

[source,python]
----
from_eisdata(data)
----

Construct fitresulf from EISData.

==== get_psmodel

[source,python]
----
get_psmodel(data)
----

Get SDK Circuit model object

==== get_nyquist

[source,python]
----
get_nyquist(data)
----

Calculate observed and calculated nyquist curves.

*Parameters:*

* *data* (link:#pypalmsens._data.eisdata.EISData[EISData]) – Input EIS
data.

*Returns:*

* calc, meas : tuple[Curve, Curve] – Returns the nyquist curve
calculated from the model parameters and the measured curve from the EIS
data.

==== get_bode_z

[source,python]
----
get_bode_z(data)
----

Calculate observed and calculated Bode curve Z vs Frequency.

*Parameters:*

* *data* (link:#pypalmsens._data.eisdata.EISData[EISData]) – Input EIS
data.

*Returns:*

* calc, meas : tuple[Curve, Curve] – Returns the nyquist curve
calculated from the model parameters and the measured curve from the EIS
data.

==== get_bode_phase

[source,python]
----
get_bode_phase(data)
----

Calculate observed and calculated Bode curve phase vs Frequency.

*Parameters:*

* *data* (link:#pypalmsens._data.eisdata.EISData[EISData]) – Input EIS
data.

*Returns:*

* calc, meas : tuple[Curve, Curve] – Returns the nyquist curve
calculated from the model parameters and the measured curve from the EIS
data.

==== plot_nyquist

[source,python]
----
plot_nyquist(data)
----

Make nyquist plot using matplotlib.

*Parameters:*

* *data* (link:#pypalmsens._data.eisdata.EISData[EISData]) – Input EIS
data.

*Returns:*

* *fig* (link:#fig.Figure[Figure]) – Returns matplotlib figure object.
use `+fig.show()+` to render plot.

==== plot_bode

[source,python]
----
plot_bode(data)
----

Make bode plot using matplotlib.

*Parameters:*

* *data* (link:#pypalmsens._data.eisdata.EISData[EISData]) – Input EIS
data.

*Returns:*

* *fig* (link:#fig.Figure[Figure]) – Returns matplotlib figure object.
use `+fig.show()+` to render plot.

=== CircuitModel

[source,python]
----
CircuitModel(cdc, algorithm='leastsq', max_iterations=500, min_delta_error=1e-09, min_delta_step=1e-12, min_freq=None, max_freq=None, tolerance=0.0001, lambda_start=0.01, lambda_factor=10.0, _last_result=None, _last_psfitter=None)
----

Fit an equivalent circuit model.

The class takes a CDC string as a required argument to set up the model.

The other parameters are optional and can be used to tweak the
minimization. The model supports fitting over a specified frequency
range and adjustment of exit conditions (i.e. max # iterations, min
delta error, min parameter step size).

Optionally you can change the initial values of the parameters, their
min/max bounds or fix their value.

Example:

....
model = CircuitModel('R(RC)')
result = model.fit(eis_data)
....

*Functions:*

* link:#pypalmsens.fitting.CircuitModel.default_parameters[*default_parameters*]
– Get default parameters. Use this to modify parameter values.
* link:#pypalmsens.fitting.CircuitModel.fit[*fit*] – Fit circuit model.

*Attributes:*

* link:#pypalmsens.fitting.CircuitModel.cdc[*cdc*] (link:#str[str]) –
Sets the circuit specified in the CDC string.
* link:#pypalmsens.fitting.CircuitModel.algorithm[*algorithm*]
(link:#typing.Literal[Literal]['`leastsq`', '`nelder-mead`']) – Name of
the fitting method to use.
* link:#pypalmsens.fitting.CircuitModel.max_iterations[*max_iterations*]
(link:#int[int]) – Maximum number of iterations.
* link:#pypalmsens.fitting.CircuitModel.min_delta_error[*min_delta_error*]
(link:#float[float]) – Minimum convergence error.
* link:#pypalmsens.fitting.CircuitModel.min_delta_step[*min_delta_step*]
(link:#float[float]) – Minimum convergence step.
* link:#pypalmsens.fitting.CircuitModel.min_freq[*min_freq*]
(link:#typing.Optional[Optional][link:#float[float]]) – Minimum fitting
frequency in Hz.
* link:#pypalmsens.fitting.CircuitModel.max_freq[*max_freq*]
(link:#typing.Optional[Optional][link:#float[float]]) – Maximum fitting
frequency in Hz.
* link:#pypalmsens.fitting.CircuitModel.tolerance[*tolerance*]
(link:#float[float]) – Convergence tolerance. Nelder-Mead only (default
= 1e-4).
* link:#pypalmsens.fitting.CircuitModel.lambda_start[*lambda_start*]
(link:#float[float]) – Start lambda value. Levenberg-Marquardt only
(default = 0.01).
* link:#pypalmsens.fitting.CircuitModel.lambda_factor[*lambda_factor*]
(link:#float[float]) – Lambda Scaling Factor. Levenberg-Marquardt only
(default = 10).
* link:#pypalmsens.fitting.CircuitModel.last_result[*last_result*] –
Store last fit result.
* link:#pypalmsens.fitting.CircuitModel.last_psfitter[*last_psfitter*] –
Store reference to last SDK fitting object.

==== cdc

[source,python]
----
cdc: str
----

Sets the circuit specified in the CDC string.

For more information, see:
https://www.utwente.nl/en/tnw/ims/publications/downloads/cdc-explained.pdf

==== algorithm

[source,python]
----
algorithm: Literal['leastsq', 'nelder-mead'] = 'leastsq'
----

Name of the fitting method to use.

Valid values are: `+leastsq+` (Levenberg-Marquardt), `+nelder-mead+`

==== max_iterations

[source,python]
----
max_iterations: int = 500
----

Maximum number of iterations.

Minimization terminates once it reaches this number of steps (default =
500).

==== min_delta_error

[source,python]
----
min_delta_error: float = 1e-09
----

Minimum convergence error.

Minimization converges if the residual (squared difference) falls below
this value (default = 1e-9).

==== min_delta_step

[source,python]
----
min_delta_step: float = 1e-12
----

Minimum convergence step.

Minimization converges if the difference in parameter values falls below
this value (default = 1e-12).

==== min_freq

[source,python]
----
min_freq: Optional[float] = None
----

Minimum fitting frequency in Hz.

==== max_freq

[source,python]
----
max_freq: Optional[float] = None
----

Maximum fitting frequency in Hz.

==== tolerance

[source,python]
----
tolerance: float = 0.0001
----

Convergence tolerance. Nelder-Mead only (default = 1e-4).

==== lambda_start

[source,python]
----
lambda_start: float = 0.01
----

Start lambda value. Levenberg-Marquardt only (default = 0.01).

==== lambda_factor

[source,python]
----
lambda_factor: float = 10.0
----

Lambda Scaling Factor. Levenberg-Marquardt only (default = 10).

==== last_result

[source,python]
----
last_result
----

Store last fit result.

==== last_psfitter

[source,python]
----
last_psfitter
----

Store reference to last SDK fitting object.

==== default_parameters

[source,python]
----
default_parameters()
----

Get default parameters. Use this to modify parameter values.

*Returns:*

* *parameters* (link:#pypalmsens._fitting.Parameters[Parameters]) –
Default parameters for CDC.

==== fit

[source,python]
----
fit(data, *, parameters=None)
----

Fit circuit model.

*Parameters:*

* *data* (link:#pypalmsens._data.eisdata.EISData[EISData]) – Input data.
* *parameters*
(link:#typing.Optional[Optional][link:#collections.abc.Sequence[Sequence][link:#float[float]]
| link:#pypalmsens._fitting.Parameters[Parameters]]) – Optional initial
parameters for fit. Can be passed as `+Parameters+` object or list of
values.

*Returns:*

* *result* (link:#pypalmsens._fitting.FitResult[FitResult]) – Returns
dataclass with fit results. Can also be accessed via `+.last_result+`.
