== pypalmsens

*Classes:*

* link:#pypalmsens.InstrumentManagerAsync[*InstrumentManagerAsync*] –
Asynchronous instrument manager for PalmSens instruments.
* link:#pypalmsens.InstrumentPoolAsync[*InstrumentPoolAsync*] – Manages
a set of instrument.

*Functions:*

* link:#pypalmsens.connect_async[*connect_async*] – Connect to
instrument and return InstrumentManagerAsync.
* link:#pypalmsens.discover_async[*discover_async*] – Discover
instruments.

=== InstrumentManagerAsync

[source,python]
----
InstrumentManagerAsync(instrument, *, callback=None)
----

Asynchronous instrument manager for PalmSens instruments.

*Parameters:*

* *instrument* – Instrument to connect to, use `+discover()+` to find
connected instruments.
* *callback*
(link:#typing.Optional[Optional][link:#pypalmsens._instruments._common.Callback[Callback]])
– If specified, call this function on every new set of data points. New
data points are batched, and contain all points since the last time it
was called. Each point is a dictionary containing `+frequency+`,
`+z_re+`, `+z_im+` for impedimetric techniques and `+index+`, `+x+`,
`+x_unit+`, `+x_type+`, `+y+`, `+y_unit+` and `+y_type+` for
non-impedimetric techniques.

*Functions:*

* link:#pypalmsens.InstrumentManagerAsync.is_connected[*is_connected*] –
Return True if an instrument connection exists.
* link:#pypalmsens.InstrumentManagerAsync.connect[*connect*] – Connect
to instrument.
* link:#pypalmsens.InstrumentManagerAsync.set_cell[*set_cell*] – Turn
the cell on or off.
* link:#pypalmsens.InstrumentManagerAsync.set_potential[*set_potential*]
– Set the potential of the cell.
* link:#pypalmsens.InstrumentManagerAsync.set_current_range[*set_current_range*]
– Set the current range for the cell.
* link:#pypalmsens.InstrumentManagerAsync.read_current[*read_current*] –
Read the current in µA.
* link:#pypalmsens.InstrumentManagerAsync.read_potential[*read_potential*]
– Read the potential in V.
* link:#pypalmsens.InstrumentManagerAsync.get_instrument_serial[*get_instrument_serial*]
– Return instrument serial number.
* link:#pypalmsens.InstrumentManagerAsync.validate_method[*validate_method*]
– Validate method.
* link:#pypalmsens.InstrumentManagerAsync.measure[*measure*] – Start
measurement using given method parameters.
* link:#pypalmsens.InstrumentManagerAsync.initiate_hardware_sync_follower_channel[*initiate_hardware_sync_follower_channel*]
– Initiate hardware sync follower channel.
* link:#pypalmsens.InstrumentManagerAsync.wait_digital_trigger[*wait_digital_trigger*]
– Wait for digital trigger.
* link:#pypalmsens.InstrumentManagerAsync.abort[*abort*] – Abort
measurement.
* link:#pypalmsens.InstrumentManagerAsync.initialize_multiplexer[*initialize_multiplexer*]
– Initialize the multiplexer.
* link:#pypalmsens.InstrumentManagerAsync.set_mux8r2_settings[*set_mux8r2_settings*]
– Set the settings for the Mux8R2 multiplexer.
* link:#pypalmsens.InstrumentManagerAsync.set_multiplexer_channel[*set_multiplexer_channel*]
– Sets the multiplexer channel.
* link:#pypalmsens.InstrumentManagerAsync.disconnect[*disconnect*] –
Disconnect from the instrument.

*Attributes:*

* link:#pypalmsens.InstrumentManagerAsync.callback[*callback*] – This
callback is called on every data point.
* link:#pypalmsens.InstrumentManagerAsync.instrument[*instrument*] –
Instrument to connect to.

==== callback

[source,python]
----
callback = callback
----

This callback is called on every data point.

==== instrument

[source,python]
----
instrument = instrument
----

Instrument to connect to.

==== is_connected

[source,python]
----
is_connected()
----

Return True if an instrument connection exists.

==== connect

[source,python]
----
connect()
----

Connect to instrument.

==== set_cell

[source,python]
----
set_cell(cell_on)
----

Turn the cell on or off.

*Parameters:*

* *cell_on* (link:#bool[bool]) – If true, turn on the cell

==== set_potential

[source,python]
----
set_potential(potential)
----

Set the potential of the cell.

*Parameters:*

* *potential* (link:#float[float]) – Potential in V

==== set_current_range

[source,python]
----
set_current_range(current_range)
----

Set the current range for the cell.

*Parameters:*

* *current_range*
(link:#pypalmsens._methods.CURRENT_RANGE[CURRENT_RANGE]) – Set the
current range, use `+pypalmsens.settings.CURRENT_RANGE+`.

==== read_current

[source,python]
----
read_current()
----

Read the current in µA.

*Returns:*

* link:#float[float] – Current in µA.”

==== read_potential

[source,python]
----
read_potential()
----

Read the potential in V.

*Returns:*

* link:#float[float] – Potential in V.

==== get_instrument_serial

[source,python]
----
get_instrument_serial()
----

Return instrument serial number.

*Returns:*

* link:#str[str] – Instrument serial.

==== validate_method

[source,python]
----
validate_method(psmethod)
----

Validate method.

==== measure

[source,python]
----
measure(method, hardware_sync_initiated_event=None)
----

Start measurement using given method parameters.

*Parameters:*

* *method* (link:#pypalmsens._methods.BaseTechnique[BaseTechnique]) –
Method parameters for measurement
* *hardware_sync_initiated_event* – …

==== initiate_hardware_sync_follower_channel

[source,python]
----
initiate_hardware_sync_follower_channel(method)
----

Initiate hardware sync follower channel.

*Parameters:*

* *method* (link:#MethodParameters[MethodParameters]) – Method
parameters

*Returns:*

* link:#tuple[tuple][link:#event[event], link:#future[future]] –
Activate the event to start the measurement. The second item is a future
that contains the data once the measurement is finished.

==== wait_digital_trigger

[source,python]
----
wait_digital_trigger(wait_for_high)
----

Wait for digital trigger.

*Parameters:*

* *wait_for_high* – …

==== abort

[source,python]
----
abort()
----

Abort measurement.

==== initialize_multiplexer

[source,python]
----
initialize_multiplexer(mux_model)
----

Initialize the multiplexer.

*Parameters:*

* *mux_model* (link:#int[int]) – The model of the multiplexer. 0 = 8
channel, 1 = 16 channel, 2 = 32 channel.

*Returns:*

* link:#int[int] – Number of available multiplexes channels

==== set_mux8r2_settings

[source,python]
----
set_mux8r2_settings(connect_sense_to_working_electrode=False, combine_reference_and_counter_electrodes=False, use_channel_1_reference_and_counter_electrodes=False, set_unselected_channel_working_electrode=0)
----

Set the settings for the Mux8R2 multiplexer.

*Parameters:*

* *connect_sense_to_working_electrode* (link:#bool[bool]) – Connect the
sense electrode to the working electrode. Default is False.
* *combine_reference_and_counter_electrodes* (link:#bool[bool]) –
Combine the reference and counter electrodes. Default is False.
* *use_channel_1_reference_and_counter_electrodes* (link:#bool[bool]) –
Use channel 1 reference and counter electrodes for all working
electrodes. Default is False.
* *set_unselected_channel_working_electrode* (link:#int[int]) – Set the
unselected channel working electrode to disconnected/floating (0),
ground (1), or standby potential (2). Default is 0.

==== set_multiplexer_channel

[source,python]
----
set_multiplexer_channel(channel)
----

Sets the multiplexer channel.

*Parameters:*

* *channel* (link:#int[int]) – Index of the channel to set.

==== disconnect

[source,python]
----
disconnect()
----

Disconnect from the instrument.

=== InstrumentPoolAsync

[source,python]
----
InstrumentPoolAsync(devices_or_managers, *, callback=None)
----

Manages a set of instrument.

Most calls are run asynchronously in the background, which means that
measurements are running in parallel.

*Parameters:*

* *devices_or_managers*
(link:#list[list][link:#pypalmsens._instruments._common.Instrument[Instrument]
|
link:#pypalmsens._instruments.instrument_manager_async.InstrumentManagerAsync[InstrumentManagerAsync]])
– List of devices or managers.
* *callback* (link:#typing.Callable[Callable]) – Optional callable to
set on instrument managers

*Functions:*

* link:#pypalmsens.InstrumentPoolAsync.connect[*connect*] – Connect all
instrument managers in the pool.
* link:#pypalmsens.InstrumentPoolAsync.disconnect[*disconnect*] –
Disconnect all instrument managers in the pool.
* link:#pypalmsens.InstrumentPoolAsync.is_connected[*is_connected*] –
Return true if all managers in the pool are connected.
* link:#pypalmsens.InstrumentPoolAsync.is_disconnected[*is_disconnected*]
– Return true if all managers in the pool are disconnected.
* link:#pypalmsens.InstrumentPoolAsync.remove[*remove*] – Close and
remove manager from pool.
* link:#pypalmsens.InstrumentPoolAsync.add[*add*] – Open and add manager
to the pool.
* link:#pypalmsens.InstrumentPoolAsync.measure[*measure*] – Concurrently
start measurement on all managers in the pool.
* link:#pypalmsens.InstrumentPoolAsync.submit[*submit*] – Concurrently
start measurement on all managers in the pool.

*Attributes:*

* link:#pypalmsens.InstrumentPoolAsync.managers[*managers*] – List of
instruments managers in the pool.

==== managers

[source,python]
----
managers = []
----

List of instruments managers in the pool.

==== connect

[source,python]
----
connect()
----

Connect all instrument managers in the pool.

==== disconnect

[source,python]
----
disconnect()
----

Disconnect all instrument managers in the pool.

==== is_connected

[source,python]
----
is_connected()
----

Return true if all managers in the pool are connected.

==== is_disconnected

[source,python]
----
is_disconnected()
----

Return true if all managers in the pool are disconnected.

==== remove

[source,python]
----
remove(manager)
----

Close and remove manager from pool.

*Parameters:*

* *manager*
(link:#pypalmsens._instruments.instrument_manager_async.InstrumentManagerAsync[InstrumentManagerAsync])
– Instance of an instrument manager.

==== add

[source,python]
----
add(manager)
----

Open and add manager to the pool.

*Parameters:*

* *manager*
(link:#pypalmsens._instruments.instrument_manager_async.InstrumentManagerAsync[InstrumentManagerAsync])
– Instance of an instrument manager.

==== measure

[source,python]
----
measure(method)
----

Concurrently start measurement on all managers in the pool.

For hardware synchronization, set `+use_hardware_sync+` on the method.
In addition, the pool must contain:

* channels from a single multi-channel instrument only
* the first channel of the multi-channel instrument
* at least two channels

All instruments are prepared and put in a waiting state. The
measurements are started via a hardware sync trigger on channel 1.

*Parameters:*

* *method* (link:#MethodSettings[MethodSettings]) – Method parameters
for measurement.

==== submit

[source,python]
----
submit(func, **kwargs)
----

Concurrently start measurement on all managers in the pool.

*Parameters:*

* *func* (link:#typing.Callable[Callable]) – This function gets called
with an instance of `+InstrumentManagerAsync+` as the argument.
* ***kwargs* (link:#typing.Any[Any]) – These keyword arguments are
passed on to the submitted function.

=== connect_async

[source,python]
----
connect_async(instrument=None)
----

Connect to instrument and return InstrumentManagerAsync.

*Parameters:*

* *instrument*
(link:#pypalmsens._instruments._common.Instrument[Instrument]) – Connect
to this instrument. If not specified, automatically discover and connect
to the first instrument.

*Returns:*

* *manager*
(link:#pypalmsens._instruments.instrument_manager_async.InstrumentManagerAsync[InstrumentManagerAsync])
– Return instance of `+InstrumentManagerAsync+` connected to the given
instrument. The connection will be terminated after the context ends.

=== discover_async

[source,python]
----
discover_async(ftdi=False, usbcdc=True, winusb=True, bluetooth=False, serial=True)
----

Discover instruments.

*Parameters:*

* *ftdi* (link:#bool[bool]) – If True, discover ftdi devices
* *usbcdc* (link:#bool[bool]) – If True, discover usbcdc devices
(Windows only)
* *winusb* (link:#bool[bool]) – If True, discover winusb devices
(Windows only)
* *bluetooth* (link:#bool[bool]) – If True, discover bluetooth devices
(Windows only)
