== pypalmsens

*Classes:*

* link:#pypalmsens.InstrumentManager[*InstrumentManager*] – Instrument
manager for PalmSens instruments.
* link:#pypalmsens.InstrumentPool[*InstrumentPool*] – Manages a set of
instrument.

*Functions:*

* link:#pypalmsens.connect[*connect*] – Connect to instrument and return
InstrumentManager.
* link:#pypalmsens.discover[*discover*] – Discover instruments.

=== InstrumentManager

[source,python]
----
InstrumentManager(instrument, *, callback=None)
----

Instrument manager for PalmSens instruments.

*Parameters:*

* *instrument*
(link:#pypalmsens._instruments._common.Instrument[Instrument]) –
Instrument to connect to, use `+discover()+` to find connected
instruments.
* *callback*
(link:#typing.Optional[Optional][link:#pypalmsens._instruments._common.Callback[Callback]])
– If specified, call this function on every new set of data points. New
data points are batched, and contain all points since the last time it
was called. Each point is a dictionary containing `+frequency+`,
`+z_re+`, `+z_im+` for impedimetric techniques and `+index+`, `+x+`,
`+x_unit+`, `+x_type+`, `+y+`, `+y_unit+` and `+y_type+` for
non-impedimetric techniques.

*Functions:*

* link:#pypalmsens.InstrumentManager.is_connected[*is_connected*] –
Return True if an instrument connection exists.
* link:#pypalmsens.InstrumentManager.connect[*connect*] – Connect to
instrument.
* link:#pypalmsens.InstrumentManager.set_cell[*set_cell*] – Turn the
cell on or off.
* link:#pypalmsens.InstrumentManager.set_potential[*set_potential*] –
Set the potential of the cell.
* link:#pypalmsens.InstrumentManager.set_current_range[*set_current_range*]
– Set the current range for the cell.
* link:#pypalmsens.InstrumentManager.read_current[*read_current*] – Read
the current in µA.
* link:#pypalmsens.InstrumentManager.read_potential[*read_potential*] –
Read the potential in V.
* link:#pypalmsens.InstrumentManager.get_instrument_serial[*get_instrument_serial*]
– Return instrument serial number.
* link:#pypalmsens.InstrumentManager.validate_method[*validate_method*]
– Validate method.
* link:#pypalmsens.InstrumentManager.measure[*measure*] – Start
measurement using given method parameters.
* link:#pypalmsens.InstrumentManager.wait_digital_trigger[*wait_digital_trigger*]
– Wait for digital trigger.
* link:#pypalmsens.InstrumentManager.abort[*abort*] – Abort measurement.
* link:#pypalmsens.InstrumentManager.initialize_multiplexer[*initialize_multiplexer*]
– Initialize the multiplexer.
* link:#pypalmsens.InstrumentManager.set_mux8r2_settings[*set_mux8r2_settings*]
– Set the settings for the Mux8R2 multiplexer.
* link:#pypalmsens.InstrumentManager.set_multiplexer_channel[*set_multiplexer_channel*]
– Sets the multiplexer channel.
* link:#pypalmsens.InstrumentManager.disconnect[*disconnect*] –
Disconnect from the instrument.

*Attributes:*

* link:#pypalmsens.InstrumentManager.callback[*callback*] – This
callback is called on every data point.
* link:#pypalmsens.InstrumentManager.instrument[*instrument*] –
Instrument to connect to.

==== callback

[source,python]
----
callback = callback
----

This callback is called on every data point.

==== instrument

[source,python]
----
instrument = instrument
----

Instrument to connect to.

==== is_connected

[source,python]
----
is_connected()
----

Return True if an instrument connection exists.

==== connect

[source,python]
----
connect()
----

Connect to instrument.

==== set_cell

[source,python]
----
set_cell(cell_on)
----

Turn the cell on or off.

*Parameters:*

* *cell_on* (link:#bool[bool]) – If true, turn on the cell

==== set_potential

[source,python]
----
set_potential(potential)
----

Set the potential of the cell.

*Parameters:*

* *potential* (link:#float[float]) – Potential in V

==== set_current_range

[source,python]
----
set_current_range(current_range)
----

Set the current range for the cell.

*Parameters:*

* *current_range*
(link:#pypalmsens._methods.CURRENT_RANGE[CURRENT_RANGE]) – Set the
current range, use `+pypalmsens.settings.CURRENT_RANGE+`.

==== read_current

[source,python]
----
read_current()
----

Read the current in µA.

*Returns:*

* link:#float[float] – Current in µA.”

==== read_potential

[source,python]
----
read_potential()
----

Read the potential in V.

*Returns:*

* link:#float[float] – Potential in V.

==== get_instrument_serial

[source,python]
----
get_instrument_serial()
----

Return instrument serial number.

*Returns:*

* link:#str[str] – Instrument serial.

==== validate_method

[source,python]
----
validate_method(psmethod)
----

Validate method.

==== measure

[source,python]
----
measure(method)
----

Start measurement using given method parameters.

*Parameters:*

* *method* (link:#pypalmsens._methods.BaseTechnique[BaseTechnique]) –
Method parameters for measurement

==== wait_digital_trigger

[source,python]
----
wait_digital_trigger(wait_for_high)
----

Wait for digital trigger.

*Parameters:*

* *wait_for_high* – …

==== abort

[source,python]
----
abort()
----

Abort measurement.

==== initialize_multiplexer

[source,python]
----
initialize_multiplexer(mux_model)
----

Initialize the multiplexer.

*Parameters:*

* *mux_model* (link:#int[int]) – The model of the multiplexer. 0 = 8
channel, 1 = 16 channel, 2 = 32 channel.

*Returns:*

* link:#int[int] – Number of available multiplexes channels

==== set_mux8r2_settings

[source,python]
----
set_mux8r2_settings(connect_sense_to_working_electrode=False, combine_reference_and_counter_electrodes=False, use_channel_1_reference_and_counter_electrodes=False, set_unselected_channel_working_electrode=0)
----

Set the settings for the Mux8R2 multiplexer.

*Parameters:*

* *connect_sense_to_working_electrode* (link:#bool[bool]) – Connect the
sense electrode to the working electrode. Default is False.
* *combine_reference_and_counter_electrodes* (link:#bool[bool]) –
Combine the reference and counter electrodes. Default is False.
* *use_channel_1_reference_and_counter_electrodes* (link:#bool[bool]) –
Use channel 1 reference and counter electrodes for all working
electrodes. Default is False.
* *set_unselected_channel_working_electrode* (link:#int[int]) – Set the
unselected channel working electrode to disconnected/floating (0),
ground (1), or standby potential (2). Default is 0.

==== set_multiplexer_channel

[source,python]
----
set_multiplexer_channel(channel)
----

Sets the multiplexer channel.

*Parameters:*

* *channel* (link:#int[int]) – Index of the channel to set.

==== disconnect

[source,python]
----
disconnect()
----

Disconnect from the instrument.

=== InstrumentPool

[source,python]
----
InstrumentPool(devices_or_managers, *, callback=None)
----

Manages a set of instrument.

Most calls are run asynchronously in the background, which means that
measurements are running in parallel.

This is a thin wrapper around the `+InstrumentManagerAsync+`.

*Parameters:*

* *devices_or_managers*
(link:#list[list][link:#pypalmsens._instruments._common.Instrument[Instrument]
|
link:#pypalmsens._instruments.instrument_manager_async.InstrumentManagerAsync[InstrumentManagerAsync]])
– List of devices or managers.
* *callback* (link:#typing.Callable[Callable]) – Optional callable to
set on instrument managers

*Functions:*

* link:#pypalmsens.InstrumentPool.connect[*connect*] – Connect all
instrument managers in the pool.
* link:#pypalmsens.InstrumentPool.disconnect[*disconnect*] – Disconnect
all instrument managers in the pool.
* link:#pypalmsens.InstrumentPool.is_connected[*is_connected*] – Return
true if all managers in the pool are connected.
* link:#pypalmsens.InstrumentPool.is_disconnected[*is_disconnected*] –
Return true if all managers in the pool are disconnected.
* link:#pypalmsens.InstrumentPool.remove[*remove*] – Close and remove
manager from pool.
* link:#pypalmsens.InstrumentPool.add[*add*] – Open and add manager to
the pool.
* link:#pypalmsens.InstrumentPool.measure[*measure*] – Concurrently run
measurement on all managers in the pool.

*Attributes:*

* link:#pypalmsens.InstrumentPool.managers[*managers*] – List of
instruments managers in the pool.

==== managers

[source,python]
----
managers = self._async.managers
----

List of instruments managers in the pool.

==== connect

[source,python]
----
connect()
----

Connect all instrument managers in the pool.

==== disconnect

[source,python]
----
disconnect()
----

Disconnect all instrument managers in the pool.

==== is_connected

[source,python]
----
is_connected()
----

Return true if all managers in the pool are connected.

==== is_disconnected

[source,python]
----
is_disconnected()
----

Return true if all managers in the pool are disconnected.

==== remove

[source,python]
----
remove(manager)
----

Close and remove manager from pool.

*Parameters:*

* *manager*
(link:#pypalmsens._instruments.instrument_manager_async.InstrumentManagerAsync[InstrumentManagerAsync])
– Instance of an instrument manager.

==== add

[source,python]
----
add(manager)
----

Open and add manager to the pool.

*Parameters:*

* *manager*
(link:#pypalmsens._instruments.instrument_manager_async.InstrumentManagerAsync[InstrumentManagerAsync])
– Instance of an instrument manager.

==== measure

[source,python]
----
measure(method)
----

Concurrently run measurement on all managers in the pool.

For hardware synchronization, set `+use_hardware_sync+` on the method.
In addition, the pool must contain:

* channels from a single multi-channel instrument only
* the first channel of the multi-channel instrument
* at least two channels

All instruments are prepared and put in a waiting state. The
measurements are started via a hardware sync trigger on channel 1.

*Parameters:*

* *method* (link:#MethodSettings[MethodSettings]) – Method parameters
for measurement.

=== connect

[source,python]
----
connect(instrument=None)
----

Connect to instrument and return InstrumentManager.

*Parameters:*

* *instrument*
(link:#pypalmsens._instruments._common.Instrument[Instrument]) – Connect
to this instrument. If not specified, automatically discover and connect
to the first instrument.

*Returns:*

* *manager*
(link:#pypalmsens._instruments.instrument_manager.InstrumentManager[InstrumentManager])
– Return instance of `+InstrumentManager+` connected to the given
instrument. The connection will be terminated after the context ends.

=== discover

[source,python]
----
discover(ftdi=False, usbcdc=True, winusb=True, bluetooth=False, serial=True)
----

Discover instruments.

*Parameters:*

* *ftdi* (link:#bool[bool]) – If True, discover ftdi devices
* *usbcdc* (link:#bool[bool]) – If True, discover usbcdc devices
(Windows only)
* *winusb* (link:#bool[bool]) – If True, discover winusb devices
(Windows only)
* *bluetooth* (link:#bool[bool]) – If True, discover bluetooth devices
(Windows only)
* *serial* (link:#bool[bool]) – If True, discover serial devices

Return

discovered : listlink:#instrument[Instrument] List of dataclasses with
discovered instruments.
