== pypalmsens.mixed_mode

*Classes:*

* link:#pypalmsens.mixed_mode.ConstantE[*ConstantE*] – Amperometric
detection stage.
* link:#pypalmsens.mixed_mode.ConstantI[*ConstantI*] – Potentiometry
stage.
* link:#pypalmsens.mixed_mode.SweepE[*SweepE*] – Linear sweep detection
stage.
* link:#pypalmsens.mixed_mode.OpenCircuit[*OpenCircuit*] – Ocp stage.
* link:#pypalmsens.mixed_mode.Impedance[*Impedance*] – Electostatic
impedance stage.
* link:#pypalmsens.mixed_mode.MixedMode[*MixedMode*] – Create mixed mode
method parameters.

=== ConstantE

Amperometric detection stage.

*Functions:*

* link:#pypalmsens.mixed_mode.ConstantE.from_stage_type[*from_stage_type*]
– Create new instance of appropriate stage from its type.

*Attributes:*

* link:#pypalmsens.mixed_mode.ConstantE.current_limits[*current_limits*]
(link:#pypalmsens._methods.settings.CurrentLimits[CurrentLimits]) – Set
the current limit settings.
* link:#pypalmsens.mixed_mode.ConstantE.type[*type*]
(link:#typing.Literal[Literal]['`ConstantE`']) –
* link:#pypalmsens.mixed_mode.ConstantE.potential[*potential*]
(link:#float[float]) – Potential in V.
* link:#pypalmsens.mixed_mode.ConstantE.run_time[*run_time*]
(link:#float[float]) – Run time in s.

==== current_limits

[source,python]
----
current_limits: settings.CurrentLimits = attrs.field(factory=(settings.CurrentLimits))
----

Set the current limit settings.

==== type

[source,python]
----
type: Literal['ConstantE'] = 'ConstantE'
----

==== potential

[source,python]
----
potential: float = 0.0
----

Potential in V.

==== run_time

[source,python]
----
run_time: float = 1.0
----

Run time in s.

==== from_stage_type

[source,python]
----
from_stage_type(id)
----

Create new instance of appropriate stage from its type.

=== ConstantI

Potentiometry stage.

*Functions:*

* link:#pypalmsens.mixed_mode.ConstantI.from_stage_type[*from_stage_type*]
– Create new instance of appropriate stage from its type.

*Attributes:*

* link:#pypalmsens.mixed_mode.ConstantI.potential_limits[*potential_limits*]
(link:#pypalmsens._methods.settings.PotentialLimits[PotentialLimits]) –
Set the potential limit settings
* link:#pypalmsens.mixed_mode.ConstantI.type[*type*]
(link:#typing.Literal[Literal]['`ConstantI`']) –
* link:#pypalmsens.mixed_mode.ConstantI.current[*current*]
(link:#float[float]) – The current to apply in the given current range.
* link:#pypalmsens.mixed_mode.ConstantI.applied_current_range[*applied_current_range*]
(link:#pypalmsens._methods._shared.CURRENT_RANGE[CURRENT_RANGE]) –
Applied current range.
* link:#pypalmsens.mixed_mode.ConstantI.run_time[*run_time*]
(link:#float[float]) – Run time in s.

==== potential_limits

[source,python]
----
potential_limits: settings.PotentialLimits = attrs.field(factory=(settings.PotentialLimits))
----

Set the potential limit settings

==== type

[source,python]
----
type: Literal['ConstantI'] = 'ConstantI'
----

==== current

[source,python]
----
current: float = 0.0
----

The current to apply in the given current range.

Note that this value acts as a multiplier in the applied current range.

So if 10 uA is the applied current range and 1.5 is given as current
value, the applied current will be 15 uA.

==== applied_current_range

[source,python]
----
applied_current_range: CURRENT_RANGE = CURRENT_RANGE.cr_100_uA
----

Applied current range.

Use `+CURRENT_RANGE+` to define the range.

==== run_time

[source,python]
----
run_time: float = 1.0
----

Run time in s.

==== from_stage_type

[source,python]
----
from_stage_type(id)
----

Create new instance of appropriate stage from its type.

=== SweepE

Linear sweep detection stage.

*Functions:*

* link:#pypalmsens.mixed_mode.SweepE.from_stage_type[*from_stage_type*]
– Create new instance of appropriate stage from its type.

*Attributes:*

* link:#pypalmsens.mixed_mode.SweepE.current_limits[*current_limits*]
(link:#pypalmsens._methods.settings.CurrentLimits[CurrentLimits]) – Set
the current limit settings.
* link:#pypalmsens.mixed_mode.SweepE.type[*type*]
(link:#typing.Literal[Literal]['`SweepE`']) –
* link:#pypalmsens.mixed_mode.SweepE.begin_potential[*begin_potential*]
(link:#float[float]) – Begin potential in V.
* link:#pypalmsens.mixed_mode.SweepE.end_potential[*end_potential*]
(link:#float[float]) – End potential in V.
* link:#pypalmsens.mixed_mode.SweepE.step_potential[*step_potential*]
(link:#float[float]) – Step potential in V.
* link:#pypalmsens.mixed_mode.SweepE.scanrate[*scanrate*]
(link:#float[float]) – Scan rate in V/s.

==== current_limits

[source,python]
----
current_limits: settings.CurrentLimits = attrs.field(factory=(settings.CurrentLimits))
----

Set the current limit settings.

==== type

[source,python]
----
type: Literal['SweepE'] = 'SweepE'
----

==== begin_potential

[source,python]
----
begin_potential: float = -0.5
----

Begin potential in V.

==== end_potential

[source,python]
----
end_potential: float = 0.5
----

End potential in V.

==== step_potential

[source,python]
----
step_potential: float = 0.1
----

Step potential in V.

==== scanrate

[source,python]
----
scanrate: float = 1.0
----

Scan rate in V/s.

==== from_stage_type

[source,python]
----
from_stage_type(id)
----

Create new instance of appropriate stage from its type.

=== OpenCircuit

Ocp stage.

*Functions:*

* link:#pypalmsens.mixed_mode.OpenCircuit.from_stage_type[*from_stage_type*]
– Create new instance of appropriate stage from its type.

*Attributes:*

* link:#pypalmsens.mixed_mode.OpenCircuit.potential_limits[*potential_limits*]
(link:#pypalmsens._methods.settings.PotentialLimits[PotentialLimits]) –
Set the potential limit settings
* link:#pypalmsens.mixed_mode.OpenCircuit.type[*type*]
(link:#typing.Literal[Literal]['`OpenCircuit`']) –
* link:#pypalmsens.mixed_mode.OpenCircuit.run_time[*run_time*]
(link:#float[float]) – Run time in s.

==== potential_limits

[source,python]
----
potential_limits: settings.PotentialLimits = attrs.field(factory=(settings.PotentialLimits))
----

Set the potential limit settings

==== type

[source,python]
----
type: Literal['OpenCircuit'] = 'OpenCircuit'
----

==== run_time

[source,python]
----
run_time: float = 1.0
----

Run time in s.

==== from_stage_type

[source,python]
----
from_stage_type(id)
----

Create new instance of appropriate stage from its type.

=== Impedance

Electostatic impedance stage.

*Functions:*

* link:#pypalmsens.mixed_mode.Impedance.from_stage_type[*from_stage_type*]
– Create new instance of appropriate stage from its type.

*Attributes:*

* link:#pypalmsens.mixed_mode.Impedance.type[*type*]
(link:#typing.Literal[Literal]['`Impedance`']) –
* link:#pypalmsens.mixed_mode.Impedance.run_time[*run_time*]
(link:#float[float]) – Run time in s.
* link:#pypalmsens.mixed_mode.Impedance.dc_potential[*dc_potential*]
(link:#float[float]) – DC potential in V.
* link:#pypalmsens.mixed_mode.Impedance.ac_potential[*ac_potential*]
(link:#float[float]) – AC potential in V RMS.
* link:#pypalmsens.mixed_mode.Impedance.frequency[*frequency*]
(link:#float[float]) – Frequency in Hz.
* link:#pypalmsens.mixed_mode.Impedance.min_sampling_time[*min_sampling_time*]
(link:#float[float]) – Minimum sampling time in s.
* link:#pypalmsens.mixed_mode.Impedance.max_equilibration_time[*max_equilibration_time*]
(link:#float[float]) – Max equilibration time in s.

==== type

[source,python]
----
type: Literal['Impedance'] = 'Impedance'
----

==== run_time

[source,python]
----
run_time: float = 10.0
----

Run time in s.

==== dc_potential

[source,python]
----
dc_potential: float = 0.0
----

DC potential in V.

==== ac_potential

[source,python]
----
ac_potential: float = 0.01
----

AC potential in V RMS.

==== frequency

[source,python]
----
frequency: float = 50000.0
----

Frequency in Hz.

==== min_sampling_time

[source,python]
----
min_sampling_time: float = 0.5
----

Minimum sampling time in s.

The instrument will measure at least 2 sine waves. The sampling time
will be automatically adjusted when necessary.

==== max_equilibration_time

[source,python]
----
max_equilibration_time: float = 5.0
----

Max equilibration time in s.

Used as a guard when the frequency drops below 1/max. equilibration
time.

==== from_stage_type

[source,python]
----
from_stage_type(id)
----

Create new instance of appropriate stage from its type.

=== MixedMode

Create mixed mode method parameters.

*Functions:*

* link:#pypalmsens.mixed_mode.MixedMode.to_dict[*to_dict*] – Return the
technique instance as a new key/value dictionary mapping.
* link:#pypalmsens.mixed_mode.MixedMode.from_dict[*from_dict*] –
Structure technique instance from dict.
* link:#pypalmsens.mixed_mode.MixedMode.from_method_id[*from_method_id*]
– Create new instance of appropriate technique from method ID.

*Attributes:*

* link:#pypalmsens.mixed_mode.MixedMode.current_range[*current_range*]
(link:#pypalmsens._methods.settings.CurrentRange[CurrentRange]) – Set
the autoranging current.
* link:#pypalmsens.mixed_mode.MixedMode.pretreatment[*pretreatment*]
(link:#pypalmsens._methods.settings.Pretreatment[Pretreatment]) – Set
the pretreatment settings.
* link:#pypalmsens.mixed_mode.MixedMode.post_measurement[*post_measurement*]
(link:#pypalmsens._methods.settings.PostMeasurement[PostMeasurement]) –
Set the post measurement settings.
* link:#pypalmsens.mixed_mode.MixedMode.data_processing[*data_processing*]
(link:#pypalmsens._methods.settings.DataProcessing[DataProcessing]) –
Set the data processing settings.
* link:#pypalmsens.mixed_mode.MixedMode.general[*general*]
(link:#pypalmsens._methods.settings.General[General]) – Sets
general/other settings.
* link:#pypalmsens.mixed_mode.MixedMode.interval_time[*interval_time*]
(link:#float[float]) – Interval time in s.
* link:#pypalmsens.mixed_mode.MixedMode.cycles[*cycles*]
(link:#int[int]) – Number of times to go through all stages.
* link:#pypalmsens.mixed_mode.MixedMode.stages[*stages*]
(link:#list[list][link:#pypalmsens._methods.mixed_mode.ConstantE[ConstantE]
| link:#pypalmsens._methods.mixed_mode.ConstantI[ConstantI] |
link:#pypalmsens._methods.mixed_mode.SweepE[SweepE] |
link:#pypalmsens._methods.mixed_mode.OpenCircuit[OpenCircuit] |
link:#pypalmsens._methods.mixed_mode.Impedance[Impedance]]) – List of
stages to run through.

==== current_range

[source,python]
----
current_range: settings.CurrentRange = attrs.field(factory=(settings.CurrentRange), converter=current_converter)
----

Set the autoranging current.

==== pretreatment

[source,python]
----
pretreatment: settings.Pretreatment = attrs.field(factory=(settings.Pretreatment))
----

Set the pretreatment settings.

==== post_measurement

[source,python]
----
post_measurement: settings.PostMeasurement = attrs.field(factory=(settings.PostMeasurement))
----

Set the post measurement settings.

==== data_processing

[source,python]
----
data_processing: settings.DataProcessing = attrs.field(factory=(settings.DataProcessing))
----

Set the data processing settings.

==== general

[source,python]
----
general: settings.General = attrs.field(factory=(settings.General))
----

Sets general/other settings.

==== interval_time

[source,python]
----
interval_time: float = 0.1
----

Interval time in s.

==== cycles

[source,python]
----
cycles: int = 1
----

Number of times to go through all stages.

==== stages

[source,python]
----
stages: list[ConstantE | ConstantI | SweepE | OpenCircuit | Impedance] = attrs.field(factory=list)
----

List of stages to run through.

==== to_dict

[source,python]
----
to_dict()
----

Return the technique instance as a new key/value dictionary mapping.

==== from_dict

[source,python]
----
from_dict(obj)
----

Structure technique instance from dict.

Opposite of `+.to_dict()+`

==== from_method_id

[source,python]
----
from_method_id(id)
----

Create new instance of appropriate technique from method ID.
