= Example Apps
:experimental:

This page lists some examples to help you get started with app development.

The examples use https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/[asynchronous
programming] where necessary to prevent the PalmSens SDK libraries from blocking the user interface.

To make a new app using one of the example apps as a template:

1. Copy the directory you want to copy, e.g. `BasicExample`
2. Rename the directory to e.g. `MyNewApp`
3. Rename `BasicExample.csproj` to `MyNewApp.csproj`
4. Right click menu:Solution[Add > Existing Project], select `MyNewApp.csproj` file
5. Update namespace (find-replace), `BasicExample` -> `MyNewApp`

== Example apps

Basic Example::
Shows how to make a connection and run a measurement, with a minimum amount of code.

Plot Example::
Shows how to make a connection, run a measurement and plot the results.

Electrochemical Impedance Spectroscopy Plot Example::
Shows how to make a connection, run an Electrochemical Impedance Spectroscopy measurement and plot the results.

[#example-data]
Import, Analyze and Save Data Example::
Shows how to load and measurements and methods from and to `.pssession` and `.psmethod` files, and how to smooth data, manipulate data and detect peaks.

Multiplexer Example::
Shows how to make a connection and run a measurement on different multiplexer channels.

Auxilliary/BiPot Example::
Shows how to measure additional data from the auxiliary port or a bipot.

[#example-internal]
Internal Storage Example::
Shows how to navigate and access files on the internal storage of a EmStat Pico Development Board, Sensit BT, EmStat4 and PalmSens4.

[#example-eis-fit]
Electrochemical Impedance Spectroscopy Fit Example::
Shows how perform an equivalent circuit analysis on an EIS frequency scan measurement.

[#example-peaks]
Peak Detection Example::
Shows how to perform an advanced peak detection for Linear Sweep Voltammetry and Cyclic Voltammetry measurements.

The following examples use https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/[asynchronous programming] to prevent the PalmSens SDK libraries from blocking the user interface.
Please note that when using the async functionalities of the core not to mix in any synchronous functions that communicate with the PalmSens/EmStat instrument.

Basic Example Async::
Shows how to make a connection and run a measurement, with a minimum amount of code.

Plot Example Async::
Shows how to make a connection, run a measurement and plot the results.

Multi Channel Example::
Shows how to make a connection to multiple channels, run different types of measurements and plot the results.

Electrochemical Impedance Spectroscopy Fit Example Async::
Shows how perform an equivalent circuit analysis on an EIS frequency scan measurement.

Peak Detection Example Async::
Shows how to perform an advanced peak detection for Linear Sweep Voltammetry and Cyclic Voltammetry measurements.

Internal Storage Example Async::
Shows how to navigate and access files on the internal storage of a EmStat Pico Development Board, Sensit BT, EmStat4 and PalmSens4.

Firmware Update Example Async::
Shows how to update the firmware of an instrument.

MethodSCRIPT™ Example::
Shows how to execute MethodSCRIPT™ on compatible instruments using a Sandbox measurement or directly using getter and setter functions.

GPIO Example Async::
Shows how to read and set the digital lines of a EmStat Pico Development Board.

The following examples use the `PalmSens.Core` library directly.

Console Example::
Shows how to discover devices, establish a connection and run a measurement using only the PalmSens.Core.dll & PalmSens.Core.Windows.dll
