= Labview

The PalmSens SDK contains the following .NET libraries and LabVIEW
classes, controls and Vis in the PalmSens folder:

Libraries Folder::
Contains all the necessary .NET libraries

PalmSens LabVIEW class::

    Class that implements the basic features required to use our instruments
    in LabVIEW.

    * `Initialise`: Initialises the class and .NET libraries.
    * `Dispose`: Frees up memory used by .NET libraries.
    * `ListInstruments`: Returns an array of the available instruments.
    * `Connect`: Connects to the specified instrument.
    * `Disconnect`: Disconnects from the connected instrument.
    * `Measure`: Performs a measurement.
    * `AbortMeasurement`: Aborts the current measurement

MeasurementResults and LiveCurveResults controls::
Type definitions for the in and outputs of the Measure function.

Event Callback Vis::
VIs used by the Measure function to receive data from .NET events.

== Example programs

The following examples are included.

Example – BasicExample::
Demonstrates how to use the PalmSens class to run a measurement.

Example – MethodSCRIPTExample::
Demonstrates how to use the PalmSens class to run a MethodSCRIPT^TM^
measurement.

Example – BasicUIExample::
Demonstrates how to use the PalmSens class to run and plot a measurement in real-time and the recommended method to abort, disconnect, or terminate the app during an active measurement.

== Compatible devices and firmware

[cols="1,1",options="header",]
|===
| Device | Minimum required firmware version
| EmStat | 3.7
| EmStat2 | 7.7
| EmStat3 | 7.7
| EmStat3+ | 7.7
| EmStat4 | 1.2
| EmStat Go | 7.7
| EmStat Pico | 1.3
| Sensit Smart | 1.3
| Sensit BT | 1.3
| MultiEmStat | 7.7
| PalmSens3 | 2.8
| PalmSens4 | 1.7
| MultiPalmSens4 | 1.7
|===
