= PalmSens Developer documentation

{empty} +
{empty}

image::banner.svg[PalmSens banner, width=80%]

{empty} +
{empty}

Take full control of your PalmSens instruments and modules with the PalmSens Software Development Kits (SDKs) and code examples.

SDKs are available for the ecosystems below. See the links for installation instructions, code documentation, and examples.

- xref:python:ROOT:index.adoc[]
- xref:matlab:ROOT:index.adoc[]
- xref:labview:ROOT:index.adoc[]
- xref:maui:ROOT:index.adoc[]

== Which SDK should I use?

For new projects, we recommend using xref:python:ROOT:index.adoc[PyPalmSens] for data science and prototyping projects, and the xref:maui:ROOT:index.adoc[.NET MAUI SDK] for native, cross-platform application development targeting Windows, Android, and iOS.
Both of these SDKs are actively maintained and will continue to receive new features and updates.

For existing codebases, we support the xref:matlab:ROOT:index.adoc[Matlab SDK] and xref:labview:ROOT:index.adoc[LabView SDK]. These SDKs will continue to receive occasional bug fixes but are no longer under active development.
