= Installation
:experimental: true

== Requirements (Windows)

* https://python.org[Python version 3.10 or newer]
* .NET Framework 4.7.2
* Drivers included with _PSTrace5.x_, _MultiTrace4.x_, _PSTrace Xpress_ or the included http://https://github.com/PalmSens/PalmSens_SDK/releases/download/python-1.0.0/PalmSens.Drivers.exe[driver installer]

[NOTE]
====
Python 3.13 contains https://github.com/python/cpython/issues/130522[a known issue] which will print errors to the output due to threads not being disposed correctly, these errors can safely be ignored.
`Exception ignored in: <function _DeleteDummyThreadOnDel.__del__ at 0x000001B73AEEE5C0>`
====

== Requirements (Linux)

* Python version 3.10 or newer. Use your system's package manager to install Python.
* .NET Runtime 9.0 or newer, see this https://learn.microsoft.com/en-us/dotnet/core/install/linux[link] for more information.
  Typically this is called something like `dotnet-runtime-9.0` in your system's package manager.
* Optional: FTDI d2xx drivers available on https://ftdichip.com/drivers/d2xx-drivers/[the ftdi website].
+
If you do not use them it is recommended to disable scanning for FTDI devices.
+
[,python]
----
import pypalmsens as ps
available_instruments = ps.discover(ftdi=False)
----

== Virtual environments

Virtual enviroments are used to create isolated Python installations.
Tools like https://docs.python.org/3/library/venv.html[venv] or https://docs.conda.io/projects/conda/[conda] help you create and update environment that have different versions of Python and/or packages installed in them. This makes them useful for software development.

This section shows how to set up and activate an environment.

Setting up a virtual environment using https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/[Python, pip and venv]:

[,powershell]
----
python -m venv .venv
.venv/Scripts/activate.ps1
python -m pip install -e .[develop]
----

Alternatively, setting up a https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html[virtual environment using Conda]:

[,powershell]
----
conda create -n pypalmsens python=3.13
conda activate pypalmsens
pip install pypalmsens
----

=== Visual Studio Code

https://code.visualstudio.com/[VS Code] supports virtual environments. In combination with the Python, Python Debugger and Pylance extensions, VS code makes it easy to create virtual environments and load the python dependencies.

See the https://code.visualstudio.com/docs/python/environments#_creating-environments[VSCode documentation] for how to set this up.
