= Installation
:experimental: true

To install:

```
pip install pypalmsens
```

== Requirements (Windows)

* https://python.org[Python version 3.10 or newer]
* .NET Framework 4.7.2
* Drivers included with PSTrace 5, MultiTrace 4, PSTrace Xpress or the https://github.com/PalmSens/PalmSens_SDK/releases/download/python-1.0.0/PalmSens.Drivers.exe[driver installer].

[#req-linux]
== Requirements (Linux and MacOS)

* https://python.org[Python version 3.10 or newer]. Use your system's package manager to install Python.
* .NET Runtime 9.0 or newer. This is called something like `dotnet-runtime-9.0` in your package manager.
  See the links below or https://learn.microsoft.com/en-us/dotnet/core/install/linux[click here] for more information.
  - https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu-install[Ubuntu]
  - https://learn.microsoft.com/en-us/dotnet/core/install/linux-debian[Debian]
  - https://learn.microsoft.com/en-us/dotnet/core/install/linux-fedora[Fedora]
  - https://learn.microsoft.com/en-us/dotnet/core/install/linux-rhel[Redhat]
  - https://learn.microsoft.com/en-us/dotnet/iot/deployment[Raspberry Pi and other single-board ARM computers]
  - https://learn.microsoft.com/en-us/dotnet/core/install/macos[MacOS]
* Optional: https://ftdichip.com/drivers/d2xx-drivers/[FTDI d2xx drivers].
  - For a list of devices with an FTDI chip, see the xref:index.adoc#compatibility[Compatibility table].
  - For Raspberry Pi 4 or 5 you need the ARMv8 driver.
  - See xref:#ftdisetup[below] for how to set up your system for FTDI devices.

In addition, make sure your user is added to the 'dialout' group:

[,bash]
----
$ groups
pi adm dialout ...
----

If your username is not among the list, add it using:

[,bash]
----
sudo usermod -a -G dialout $USER
----

And log out and in again to make sure the changes have take effect.
This avoids errors like `can’t open device "/dev/ttyACM0": Permission denied` when trying to connect to a device.

[NOTE]
.Known issues
====
Linux / MacOS support is a work in progress.
Although many features work, there are some limitations compared to the Windows version.

See https://github.com/PalmSens/PalmSens_SDK/issues/60[this issue] for an actual list of known issues.
====

[#ftdisetup]
=== FTDI devices

// [,bash]
// ----
// tar xfvz libftd2xx-arm-v8-1.4.33.tgz
// cd libftd2xx-arm-v8-1.4.33.tgz
// sudo cp libftd2xx.* /usr/local/lib
// sudo chmod 0755 /usr/local/lib/libftd2xx.so.1.4.33
// sudo ln -sf /usr/local/lib/libftd2xx.so.1.4.33 /usr/local/lib/libftd2xx.so
// ----

To set up your system to work with devices using the https://ftdichip.com/[FTDI chip], you need to follow a few additional steps.
To see if your device needs the FTDI drivers, see the xref:index.adoc#compatibility[Compatibility table].

First, install the https://ftdichip.com/drivers/d2xx-drivers/[D2XX drivers].

Set up https://wiki.archlinux.org/title/Udev[udev rules].
`udev` manages permissions of the device to be accessible to non-root users and groups.
Add the following lines to `/etc/udev/rules.d/50-ftdi.rules`:

[,ascii]
----
ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6015", RUN+="/bin/sh -c 'rmmod ftdi_sio && rmmod usbserial'", MODE="0666"
ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6011", RUN+="/bin/sh -c 'rmmod ftdi_sio && rmmod usbserial'", MODE="0666"
ATTRS{idVendor}=="0403", ATTRS{idProduct}=="d180", RUN+="/bin/sh -c 'rmmod ftdi_sio && rmmod usbserial'", MODE="0666"
ATTRS{idVendor}=="0403", ATTRS{idProduct}=="d181", RUN+="/bin/sh -c 'rmmod ftdi_sio && rmmod usbserial'", MODE="0666"
----

And restart `udevadm`.

[,bash]
----
sudo udevadm control --reload
sudo udevadm trigger
----

=== RuntimeError: Failed to create a .NET runtime (coreclr)

This error is raised if you did not install the dotnet runtime correctly. See xref:#req-linux[installation instructions above].

The error will say somethin along the likes of:

[,bash]
----
RuntimeError: Can not determine dotnet root
...
RuntimeError: Failed to create a .NET runtime (coreclr) using the
                parameters {'runtime_config': '/home/pi/palmsenssdk/python/src/pypalmsens/_pssdk/mono/runtimeconfig.json'}.
----

[%collapsible]
====
[,bash]
----
(.venv) pi@raspberrypi:~/palmsenssdk/python $ python
Python 3.13.5 (main, Jun 25 2025, 18:55:22) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypalmsens as ps
Traceback (most recent call last):
  File "/home/pi/palmsenssdk/python/.venv/lib/python3.13/site-packages/pythonnet/__init__.py", line 77, in _create_runtime_from_spec
    return clr_loader.get_coreclr(**params)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/pi/palmsenssdk/python/.venv/lib/python3.13/site-packages/clr_loader/__init__.py", line 121, in get_coreclr
    dotnet_root = find_dotnet_root()
  File "/home/pi/palmsenssdk/python/.venv/lib/python3.13/site-packages/clr_loader/util/find.py", line 57, in find_dotnet_root
    raise RuntimeError("Can not determine dotnet root")
RuntimeError: Can not determine dotnet root

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    import pypalmsens as ps
  File "/home/pi/palmsenssdk/python/src/pypalmsens/__init__.py", line 9, in <module>
    from ._lib.mono import sdk_version
  File "/home/pi/palmsenssdk/python/src/pypalmsens/_lib/mono.py", line 13, in <module>
    load('coreclr', runtime_config=str(PSSDK_DIR / 'runtimeconfig.json'))
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi/palmsenssdk/python/.venv/lib/python3.13/site-packages/pythonnet/__init__.py", line 135, in load
    set_runtime(runtime, **params)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/pi/palmsenssdk/python/.venv/lib/python3.13/site-packages/pythonnet/__init__.py", line 29, in set_runtime
    runtime = _create_runtime_from_spec(runtime, params)
  File "/home/pi/palmsenssdk/python/.venv/lib/python3.13/site-packages/pythonnet/__init__.py", line 90, in _create_runtime_from_spec
    raise RuntimeError(
    ...<2 lines>...
    ) from exc
RuntimeError: Failed to create a .NET runtime (coreclr) using the
                parameters {'runtime_config': '/home/pi/palmsenssdk/python/src/pypalmsens/_pssdk/mono/runtimeconfig.json'}.
----
====

== Virtual environments

Virtual enviroments are used to create isolated Python installations.
Tools like https://docs.python.org/3/library/venv.html[venv] or https://docs.conda.io/projects/conda/[conda] help you create and update environment that have different versions of Python and/or packages installed in them. This makes them useful for software development.

This section shows how to set up and activate an environment.

Setting up a virtual environment using https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/[Python, pip and venv]:

[,powershell]
----
python -m venv .venv
.venv/Scripts/activate.ps1
python -m pip install -e .[develop]
----

Alternatively, setting up a https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html[virtual environment using Conda]:

[,powershell]
----
conda create -n pypalmsens python=3.13
conda activate pypalmsens
pip install pypalmsens
----

=== Visual Studio Code

https://code.visualstudio.com/[VS Code] supports virtual environments. In combination with the Python, Python Debugger and Pylance extensions, VS code makes it easy to create virtual environments and load the python dependencies.

See the https://code.visualstudio.com/docs/python/environments#_creating-environments[VSCode documentation] for how to set this up.
