== pypalmsens.models

This module contains code for equivalent circuit fitting.

*Classes:*

* link:#pypalmsens.models.Parameter[*Parameter*] – Set or update
Parameter attributes.
* link:#pypalmsens.models.Parameters[*Parameters*] – Tuple-like
container class for parameters.
* link:#pypalmsens.models.FitResult[*FitResult*] – Container for fitting
results.
* link:#pypalmsens.models.CircuitModel[*CircuitModel*] – Fit an
equivalent circuit model.

=== Parameter

[source,python]
----
Parameter(symbol, value=None, min=None, max=None, fixed=None)
----

Set or update Parameter attributes.

*Functions:*

* link:#pypalmsens.models.Parameter.from_psparameter[*from_psparameter*]
– Create instance from SDK Parameter object.
* link:#pypalmsens.models.Parameter.update_psparameter[*update_psparameter*]
– Update PalmSens SDK object with values from dataclass.

*Attributes:*

* link:#pypalmsens.models.Parameter.symbol[*symbol*] (link:#str[str]) –
* link:#pypalmsens.models.Parameter.value[*value*]
(link:#typing.Optional[Optional][link:#float[float]]) –
* link:#pypalmsens.models.Parameter.min[*min*]
(link:#typing.Optional[Optional][link:#float[float]]) –
* link:#pypalmsens.models.Parameter.max[*max*]
(link:#typing.Optional[Optional][link:#float[float]]) –
* link:#pypalmsens.models.Parameter.fixed[*fixed*]
(link:#typing.Optional[Optional][link:#bool[bool]]) –

==== symbol

[source,python]
----
symbol: str
----

==== value

[source,python]
----
value: Optional[float] = None
----

==== min

[source,python]
----
min: Optional[float] = None
----

==== max

[source,python]
----
max: Optional[float] = None
----

==== fixed

[source,python]
----
fixed: Optional[bool] = None
----

==== from_psparameter

[source,python]
----
from_psparameter(psparameter)
----

Create instance from SDK Parameter object.

==== update_psparameter

[source,python]
----
update_psparameter(psparameter)
----

Update PalmSens SDK object with values from dataclass.

=== Parameters

[source,python]
----
Parameters(cdc)
----

Bases: link:#collections.abc.Sequence[Sequence]

Tuple-like container class for parameters.

This class is instantiated from the CDC code and contains default
parameters. This ensures that the length and type of parameters match
that of `+CircuitModel+`. Update the parameters in this class and pass
to `+CircuitModel.fit()+`.

*Functions:*

* link:#pypalmsens.models.Parameters.update_psmodel_parameters[*update_psmodel_parameters*]
– Update the initial parameters in the SDK model with parameters in this
instance.

*Attributes:*

* link:#pypalmsens.models.Parameters.cdc[*cdc*] –

==== cdc

[source,python]
----
cdc = cdc
----

==== update_psmodel_parameters

[source,python]
----
update_psmodel_parameters(psmodel)
----

Update the initial parameters in the SDK model with parameters in this
instance.

Note that the length and type of parameters must match that of the SDK
class.

=== FitResult

[source,python]
----
FitResult(cdc, parameters, chisq, exit_code, n_iter, error)
----

Container for fitting results.

*Functions:*

* link:#pypalmsens.models.FitResult.from_psfitresult[*from_psfitresult*]
– Construct fitresult from SDK FitResult.
* link:#pypalmsens.models.FitResult.from_eisdata[*from_eisdata*] –
Construct fitresulf from EISData.
* link:#pypalmsens.models.FitResult.get_psmodel[*get_psmodel*] – Get SDK
Circuit model object
* link:#pypalmsens.models.FitResult.get_nyquist[*get_nyquist*] –
Calculate observed and calculated nyquist curves.
* link:#pypalmsens.models.FitResult.get_bode_z[*get_bode_z*] – Calculate
observed and calculated Bode curve Z vs Frequency.
* link:#pypalmsens.models.FitResult.get_bode_phase[*get_bode_phase*] –
Calculate observed and calculated Bode curve phase vs Frequency.
* link:#pypalmsens.models.FitResult.plot_nyquist[*plot_nyquist*] – Make
nyquist plot.
* link:#pypalmsens.models.FitResult.plot_bode[*plot_bode*] – Make bode
plot.

*Attributes:*

* link:#pypalmsens.models.FitResult.cdc[*cdc*] (link:#str[str]) –
* link:#pypalmsens.models.FitResult.parameters[*parameters*]
(link:#list[list][link:#float[float]]) –
* link:#pypalmsens.models.FitResult.chisq[*chisq*] (link:#float[float])
–
* link:#pypalmsens.models.FitResult.exit_code[*exit_code*]
(link:#str[str]) –
* link:#pypalmsens.models.FitResult.n_iter[*n_iter*] (link:#int[int]) –
* link:#pypalmsens.models.FitResult.error[*error*]
(link:#list[list][link:#float[float]]) –

==== cdc

[source,python]
----
cdc: str
----

==== parameters

[source,python]
----
parameters: list[float]
----

==== chisq

[source,python]
----
chisq: float
----

==== exit_code

[source,python]
----
exit_code: str
----

==== n_iter

[source,python]
----
n_iter: int
----

==== error

[source,python]
----
error: list[float]
----

==== from_psfitresult

[source,python]
----
from_psfitresult(result, cdc)
----

Construct fitresult from SDK FitResult.

==== from_eisdata

[source,python]
----
from_eisdata(data)
----

Construct fitresulf from EISData.

==== get_psmodel

[source,python]
----
get_psmodel(data)
----

Get SDK Circuit model object

==== get_nyquist

[source,python]
----
get_nyquist(data)
----

Calculate observed and calculated nyquist curves.

*Parameters:*

* *data* (link:#pypalmsens.data.EISData[EISData]) – Input EIS data.

*Returns:*

* calc, meas : tuple[Curve, Curve] – Returns the nyquist curve
calculated from the model parameters and the measured curve from the EIS
data.

==== get_bode_z

[source,python]
----
get_bode_z(data)
----

Calculate observed and calculated Bode curve Z vs Frequency.

*Parameters:*

* *data* (link:#pypalmsens.data.EISData[EISData]) – Input EIS data.

*Returns:*

* calc, meas : tuple[Curve, Curve] – Returns the nyquist curve
calculated from the model parameters and the measured curve from the EIS
data.

==== get_bode_phase

[source,python]
----
get_bode_phase(data)
----

Calculate observed and calculated Bode curve phase vs Frequency.

*Parameters:*

* *data* (link:#pypalmsens.data.EISData[EISData]) – Input EIS data.

*Returns:*

* calc, meas : tuple[Curve, Curve] – Returns the nyquist curve
calculated from the model parameters and the measured curve from the EIS
data.

==== plot_nyquist

[source,python]
----
plot_nyquist(data)
----

Make nyquist plot.

*Parameters:*

* *data* (link:#pypalmsens.data.EISData[EISData]) – Input EIS data.

*Returns:*

* *fig* (link:#matplotlib.fig.Figure[Figure]) – Returns matplotlib
figure object. use `+fig.show()+` to render plot.

==== plot_bode

[source,python]
----
plot_bode(data)
----

Make bode plot.

*Parameters:*

* *data* (link:#pypalmsens.data.EISData[EISData]) – Input EIS data.

*Returns:*

* *fig* (link:#matplotlib.fig.Figure[Figure]) – Returns matplotlib
figure object. use `+fig.show()+` to render plot.

=== CircuitModel

[source,python]
----
CircuitModel(cdc, algorithm='leastsq', max_iterations=500, min_delta_error=1e-09, min_delta_step=1e-12, min_freq=None, max_freq=None, tolerance=0.0001, lambda_start=0.01, lambda_factor=10.0, _last_result=None, _last_psfitter=None)
----

Fit an equivalent circuit model.

The class takes a CDC string as a required argument to set up the model.

The other parameters are optional and can be used to tweak the
minimization. The model supports fitting over a specified frequency
range and adjustment of exit conditions (i.e. max # iterations, min
delta error, min parameter step size).

Optionally you can change the initial values of the parameters, their
min/max bounds or fix their value.

Example:

....
model = CircuitModel('R(RC)')
result = model.fit(eis_data)
....

*Functions:*

* link:#pypalmsens.models.CircuitModel.default_parameters[*default_parameters*]
– Get default parameters. Use this to modify parameter values.
* link:#pypalmsens.models.CircuitModel.psfitoptions[*psfitoptions*] –
Fit circuit model.
* link:#pypalmsens.models.CircuitModel.fit[*fit*] – Fit circuit model.

*Attributes:*

* link:#pypalmsens.models.CircuitModel.cdc[*cdc*] (link:#str[str]) –
* link:#pypalmsens.models.CircuitModel.algorithm[*algorithm*]
(link:#typing.Literal[Literal]['`leastsq`', '`nelder-mead`']) –
* link:#pypalmsens.models.CircuitModel.max_iterations[*max_iterations*]
(link:#int[int]) –
* link:#pypalmsens.models.CircuitModel.min_delta_error[*min_delta_error*]
(link:#float[float]) –
* link:#pypalmsens.models.CircuitModel.min_delta_step[*min_delta_step*]
(link:#float[float]) –
* link:#pypalmsens.models.CircuitModel.min_freq[*min_freq*]
(link:#typing.Optional[Optional][link:#float[float]]) –
* link:#pypalmsens.models.CircuitModel.max_freq[*max_freq*]
(link:#typing.Optional[Optional][link:#float[float]]) –
* link:#pypalmsens.models.CircuitModel.tolerance[*tolerance*]
(link:#float[float]) –
* link:#pypalmsens.models.CircuitModel.lambda_start[*lambda_start*]
(link:#float[float]) –
* link:#pypalmsens.models.CircuitModel.lambda_factor[*lambda_factor*]
(link:#float[float]) –
* link:#pypalmsens.models.CircuitModel.last_result[*last_result*] –
Store last fit result.
* link:#pypalmsens.models.CircuitModel.last_psfitter[*last_psfitter*] –
Store reference to last SDK fitting object.

==== cdc

[source,python]
----
cdc: str
----

==== algorithm

[source,python]
----
algorithm: Literal['leastsq', 'nelder-mead'] = 'leastsq'
----

==== max_iterations

[source,python]
----
max_iterations: int = 500
----

==== min_delta_error

[source,python]
----
min_delta_error: float = 1e-09
----

==== min_delta_step

[source,python]
----
min_delta_step: float = 1e-12
----

==== min_freq

[source,python]
----
min_freq: Optional[float] = None
----

==== max_freq

[source,python]
----
max_freq: Optional[float] = None
----

==== tolerance

[source,python]
----
tolerance: float = 0.0001
----

==== lambda_start

[source,python]
----
lambda_start: float = 0.01
----

==== lambda_factor

[source,python]
----
lambda_factor: float = 10.0
----

==== last_result

[source,python]
----
last_result
----

Store last fit result.

==== last_psfitter

[source,python]
----
last_psfitter
----

Store reference to last SDK fitting object.

==== default_parameters

[source,python]
----
default_parameters()
----

Get default parameters. Use this to modify parameter values.

*Returns:*

* *parameters* (link:#pypalmsens.models.Parameters[Parameters]) –
Default parameters for CDC.

==== psfitoptions

[source,python]
----
psfitoptions(data, *, parameters=None)
----

Fit circuit model.

*Parameters:*

* *data* (link:#pypalmsens.data.EISData[EISData]) – Input EIS data.
* *parameters*
(link:#typing.Optional[Optional][link:#collections.abc.Sequence[Sequence][link:#float[float]]
| link:#pypalmsens.models.Parameters[Parameters]]) – Optional initial
parameters for fit. Can be passed as `+Parameters+` object or list of
values.

*Returns:*

* *opts* (link:#PalmSens.Fitting.FitOptions[FitOptions]) – SDK object
containing fitting options.

==== fit

[source,python]
----
fit(data, *, parameters=None)
----

Fit circuit model.

*Parameters:*

* *data* (link:#pypalmsens.data.EISData[EISData]) – Input data.
* *parameters*
(link:#typing.Optional[Optional][link:#collections.abc.Sequence[Sequence][link:#float[float]]
| link:#pypalmsens.models.Parameters[Parameters]]) – Optional initial
parameters for fit. Can be passed as `+Parameters+` object or list of
values.

*Returns:*

* *result* (link:#pypalmsens.models.FitResult[FitResult]) – Returns
dataclass with fit results. Can also be accessed via `+.last_result+`.
