== pypalmsens

*Classes:*

* link:#pypalmsens.ChronoAmperometry[*ChronoAmperometry*] – Create
chrono amperometry method parameters.
* link:#pypalmsens.ChronoPotentiometry[*ChronoPotentiometry*] – Create
potentiometry method parameters.
* link:#pypalmsens.CyclicVoltammetry[*CyclicVoltammetry*] – Create
cyclic voltammetry method parameters.
* link:#pypalmsens.DifferentialPulseVoltammetry[*DifferentialPulseVoltammetry*]
– Create square wave method parameters.
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy[*ElectrochemicalImpedanceSpectroscopy*]
– Create potentiometry method parameters.
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy[*GalvanostaticImpedanceSpectroscopy*]
– Create potentiometry method parameters.
* link:#pypalmsens.LinearSweepVoltammetry[*LinearSweepVoltammetry*] –
Create linear sweep method parameters.
* link:#pypalmsens.MethodScript[*MethodScript*] – Create a method script
sandbox object.
* link:#pypalmsens.MultiStepAmperometry[*MultiStepAmperometry*] – Create
multi-step amperometry method parameters.
* link:#pypalmsens.OpenCircuitPotentiometry[*OpenCircuitPotentiometry*]
– Create open circuit potentiometry method parameters.
* link:#pypalmsens.SquareWaveVoltammetry[*SquareWaveVoltammetry*] –
Create square wave method parameters.

=== ChronoAmperometry

Bases: link:#pypalmsens.methods.techniques.BaseConfig[BaseConfig]

Create chrono amperometry method parameters.

*Attributes:*

* link:#pypalmsens.ChronoAmperometry.equilibration_time[*equilibration_time*]
(link:#float[float]) –
* link:#pypalmsens.ChronoAmperometry.interval_time[*interval_time*]
(link:#float[float]) –
* link:#pypalmsens.ChronoAmperometry.potential[*potential*]
(link:#float[float]) –
* link:#pypalmsens.ChronoAmperometry.run_time[*run_time*]
(link:#float[float]) –
* link:#pypalmsens.ChronoAmperometry.record_auxiliary_input[*record_auxiliary_input*]
(link:#bool[bool]) –
* link:#pypalmsens.ChronoAmperometry.record_cell_potential[*record_cell_potential*]
(link:#bool[bool]) –
* link:#pypalmsens.ChronoAmperometry.record_we_potential[*record_we_potential*]
(link:#bool[bool]) –
* link:#pypalmsens.ChronoAmperometry.enable_bipot_current[*enable_bipot_current*]
(link:#bool[bool]) –
* link:#pypalmsens.ChronoAmperometry.current_ranges[*current_ranges*]
(link:#pypalmsens.methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.ChronoAmperometry.pretreatment[*pretreatment*]
(link:#pypalmsens.methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.ChronoAmperometry.versus_ocp[*versus_ocp*]
(link:#pypalmsens.methods.settings.VersusOCP[VersusOCP]) –
* link:#pypalmsens.ChronoAmperometry.bipot[*bipot*]
(link:#pypalmsens.methods.settings.BiPot[BiPot]) –
* link:#pypalmsens.ChronoAmperometry.post_measurement[*post_measurement*]
(link:#pypalmsens.methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.ChronoAmperometry.current_limits[*current_limits*]
(link:#pypalmsens.methods.settings.CurrentLimits[CurrentLimits]) –
* link:#pypalmsens.ChronoAmperometry.charge_limits[*charge_limits*]
(link:#pypalmsens.methods.settings.ChargeLimits[ChargeLimits]) –
* link:#pypalmsens.ChronoAmperometry.ir_drop[*ir_drop*]
(link:#pypalmsens.methods.settings.IrDropCompensation[IrDropCompensation])
–
* link:#pypalmsens.ChronoAmperometry.equilibration_triggers[*equilibration_triggers*]
(link:#pypalmsens.methods.settings.EquilibrationTriggers[EquilibrationTriggers])
–
* link:#pypalmsens.ChronoAmperometry.measurement_triggers[*measurement_triggers*]
(link:#pypalmsens.methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.ChronoAmperometry.data_processing[*data_processing*]
(link:#pypalmsens.methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.ChronoAmperometry.multiplexer[*multiplexer*]
(link:#pypalmsens.methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.ChronoAmperometry.general[*general*]
(link:#pypalmsens.methods.settings.General[General]) –

==== equilibration_time

[source,python]
----
equilibration_time: float = 0.0
----

==== interval_time

[source,python]
----
interval_time: float = 0.1
----

==== potential

[source,python]
----
potential: float = 0.0
----

==== run_time

[source,python]
----
run_time: float = 1.0
----

==== record_auxiliary_input

[source,python]
----
record_auxiliary_input: bool = False
----

==== record_cell_potential

[source,python]
----
record_cell_potential: bool = False
----

==== record_we_potential

[source,python]
----
record_we_potential: bool = False
----

==== enable_bipot_current

[source,python]
----
enable_bipot_current: bool = False
----

==== current_ranges

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== pretreatment

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== versus_ocp

[source,python]
----
versus_ocp: VersusOCP = attrs.field(factory=VersusOCP)
----

==== bipot

[source,python]
----
bipot: BiPot = attrs.field(factory=BiPot)
----

==== post_measurement

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== current_limits

[source,python]
----
current_limits: CurrentLimits = attrs.field(factory=CurrentLimits)
----

==== charge_limits

[source,python]
----
charge_limits: ChargeLimits = attrs.field(factory=ChargeLimits)
----

==== ir_drop

[source,python]
----
ir_drop: IrDropCompensation = attrs.field(factory=IrDropCompensation)
----

==== equilibration_triggers

[source,python]
----
equilibration_triggers: EquilibrationTriggers = attrs.field(factory=EquilibrationTriggers)
----

==== measurement_triggers

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== data_processing

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== multiplexer

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== general

[source,python]
----
general: General = attrs.field(factory=General)
----

=== ChronoPotentiometry

Bases: link:#pypalmsens.methods.techniques.BaseConfig[BaseConfig]

Create potentiometry method parameters.

*Attributes:*

* link:#pypalmsens.ChronoPotentiometry.current[*current*]
(link:#float[float]) –
* link:#pypalmsens.ChronoPotentiometry.applied_current_range[*applied_current_range*]
(link:#pypalmsens.methods._shared.CURRENT_RANGE[CURRENT_RANGE]) –
* link:#pypalmsens.ChronoPotentiometry.interval_time[*interval_time*]
(link:#float[float]) –
* link:#pypalmsens.ChronoPotentiometry.run_time[*run_time*]
(link:#float[float]) –
* link:#pypalmsens.ChronoPotentiometry.record_auxiliary_input[*record_auxiliary_input*]
(link:#bool[bool]) –
* link:#pypalmsens.ChronoPotentiometry.record_cell_potential[*record_cell_potential*]
(link:#bool[bool]) –
* link:#pypalmsens.ChronoPotentiometry.record_we_current[*record_we_current*]
(link:#bool[bool]) –
* link:#pypalmsens.ChronoPotentiometry.current_ranges[*current_ranges*]
(link:#pypalmsens.methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.ChronoPotentiometry.potential_ranges[*potential_ranges*]
(link:#pypalmsens.methods.settings.PotentialRanges[PotentialRanges]) –
* link:#pypalmsens.ChronoPotentiometry.pretreatment[*pretreatment*]
(link:#pypalmsens.methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.ChronoPotentiometry.post_measurement[*post_measurement*]
(link:#pypalmsens.methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.ChronoPotentiometry.potential_limits[*potential_limits*]
(link:#pypalmsens.methods.settings.PotentialLimits[PotentialLimits]) –
* link:#pypalmsens.ChronoPotentiometry.measurement_triggers[*measurement_triggers*]
(link:#pypalmsens.methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.ChronoPotentiometry.data_processing[*data_processing*]
(link:#pypalmsens.methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.ChronoPotentiometry.multiplexer[*multiplexer*]
(link:#pypalmsens.methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.ChronoPotentiometry.general[*general*]
(link:#pypalmsens.methods.settings.General[General]) –

==== current

[source,python]
----
current: float = 0.0
----

==== applied_current_range

[source,python]
----
applied_current_range: CURRENT_RANGE = CURRENT_RANGE.cr_100_uA
----

==== interval_time

[source,python]
----
interval_time: float = 0.1
----

==== run_time

[source,python]
----
run_time: float = 1.0
----

==== record_auxiliary_input

[source,python]
----
record_auxiliary_input: bool = False
----

==== record_cell_potential

[source,python]
----
record_cell_potential: bool = False
----

==== record_we_current

[source,python]
----
record_we_current: bool = False
----

==== current_ranges

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== potential_ranges

[source,python]
----
potential_ranges: PotentialRanges = attrs.field(factory=PotentialRanges)
----

==== pretreatment

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== post_measurement

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== potential_limits

[source,python]
----
potential_limits: PotentialLimits = attrs.field(factory=PotentialLimits)
----

==== measurement_triggers

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== data_processing

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== multiplexer

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== general

[source,python]
----
general: General = attrs.field(factory=General)
----

=== CyclicVoltammetry

Bases: link:#pypalmsens.methods.techniques.BaseConfig[BaseConfig]

Create cyclic voltammetry method parameters.

*Attributes:*

* link:#pypalmsens.CyclicVoltammetry.equilibration_time[*equilibration_time*]
(link:#float[float]) –
* link:#pypalmsens.CyclicVoltammetry.begin_potential[*begin_potential*]
(link:#float[float]) –
* link:#pypalmsens.CyclicVoltammetry.vertex1_potential[*vertex1_potential*]
(link:#float[float]) –
* link:#pypalmsens.CyclicVoltammetry.vertex2_potential[*vertex2_potential*]
(link:#float[float]) –
* link:#pypalmsens.CyclicVoltammetry.step_potential[*step_potential*]
(link:#float[float]) –
* link:#pypalmsens.CyclicVoltammetry.scanrate[*scanrate*]
(link:#float[float]) –
* link:#pypalmsens.CyclicVoltammetry.n_scans[*n_scans*]
(link:#float[float]) –
* link:#pypalmsens.CyclicVoltammetry.enable_bipot_current[*enable_bipot_current*]
(link:#bool[bool]) –
* link:#pypalmsens.CyclicVoltammetry.record_auxiliary_input[*record_auxiliary_input*]
(link:#bool[bool]) –
* link:#pypalmsens.CyclicVoltammetry.record_cell_potential[*record_cell_potential*]
(link:#bool[bool]) –
* link:#pypalmsens.CyclicVoltammetry.record_we_potential[*record_we_potential*]
(link:#bool[bool]) –
* link:#pypalmsens.CyclicVoltammetry.current_ranges[*current_ranges*]
(link:#pypalmsens.methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.CyclicVoltammetry.pretreatment[*pretreatment*]
(link:#pypalmsens.methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.CyclicVoltammetry.versus_ocp[*versus_ocp*]
(link:#pypalmsens.methods.settings.VersusOCP[VersusOCP]) –
* link:#pypalmsens.CyclicVoltammetry.post_measurement[*post_measurement*]
(link:#pypalmsens.methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.CyclicVoltammetry.current_limits[*current_limits*]
(link:#pypalmsens.methods.settings.CurrentLimits[CurrentLimits]) –
* link:#pypalmsens.CyclicVoltammetry.ir_drop_compensation[*ir_drop_compensation*]
(link:#pypalmsens.methods.settings.IrDropCompensation[IrDropCompensation])
–
* link:#pypalmsens.CyclicVoltammetry.equilibrion_triggers[*equilibrion_triggers*]
(link:#pypalmsens.methods.settings.EquilibrationTriggers[EquilibrationTriggers])
–
* link:#pypalmsens.CyclicVoltammetry.measurement_triggers[*measurement_triggers*]
(link:#pypalmsens.methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.CyclicVoltammetry.data_processing[*data_processing*]
(link:#pypalmsens.methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.CyclicVoltammetry.general[*general*]
(link:#pypalmsens.methods.settings.General[General]) –

==== equilibration_time

[source,python]
----
equilibration_time: float = 0.0
----

==== begin_potential

[source,python]
----
begin_potential: float = -0.5
----

==== vertex1_potential

[source,python]
----
vertex1_potential: float = 0.5
----

==== vertex2_potential

[source,python]
----
vertex2_potential: float = -0.5
----

==== step_potential

[source,python]
----
step_potential: float = 0.1
----

==== scanrate

[source,python]
----
scanrate: float = 1.0
----

==== n_scans

[source,python]
----
n_scans: float = 1
----

==== enable_bipot_current

[source,python]
----
enable_bipot_current: bool = False
----

==== record_auxiliary_input

[source,python]
----
record_auxiliary_input: bool = False
----

==== record_cell_potential

[source,python]
----
record_cell_potential: bool = False
----

==== record_we_potential

[source,python]
----
record_we_potential: bool = False
----

==== current_ranges

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== pretreatment

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== versus_ocp

[source,python]
----
versus_ocp: VersusOCP = attrs.field(factory=VersusOCP)
----

==== post_measurement

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== current_limits

[source,python]
----
current_limits: CurrentLimits = attrs.field(factory=CurrentLimits)
----

==== ir_drop_compensation

[source,python]
----
ir_drop_compensation: IrDropCompensation = attrs.field(factory=IrDropCompensation)
----

==== equilibrion_triggers

[source,python]
----
equilibrion_triggers: EquilibrationTriggers = attrs.field(factory=EquilibrationTriggers)
----

==== measurement_triggers

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== data_processing

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== general

[source,python]
----
general: General = attrs.field(factory=General)
----

=== DifferentialPulseVoltammetry

Bases: link:#pypalmsens.methods.techniques.BaseConfig[BaseConfig]

Create square wave method parameters.

*Attributes:*

* link:#pypalmsens.DifferentialPulseVoltammetry.equilibration_time[*equilibration_time*]
(link:#float[float]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.begin_potential[*begin_potential*]
(link:#float[float]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.end_potential[*end_potential*]
(link:#float[float]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.step_potential[*step_potential*]
(link:#float[float]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.pulse_potential[*pulse_potential*]
(link:#float[float]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.pulse_time[*pulse_time*]
(link:#float[float]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.scan_rate[*scan_rate*]
(link:#float[float]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.record_auxiliary_input[*record_auxiliary_input*]
(link:#bool[bool]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.record_cell_potential[*record_cell_potential*]
(link:#bool[bool]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.record_we_potential[*record_we_potential*]
(link:#bool[bool]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.enable_bipot_current[*enable_bipot_current*]
(link:#bool[bool]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.current_ranges[*current_ranges*]
(link:#pypalmsens.methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.pretreatment[*pretreatment*]
(link:#pypalmsens.methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.versus_ocp[*versus_ocp*]
(link:#pypalmsens.methods.settings.VersusOCP[VersusOCP]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.bipot[*bipot*]
(link:#pypalmsens.methods.settings.BiPot[BiPot]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.post_measurement[*post_measurement*]
(link:#pypalmsens.methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.ir_drop[*ir_drop*]
(link:#pypalmsens.methods.settings.IrDropCompensation[IrDropCompensation])
–
* link:#pypalmsens.DifferentialPulseVoltammetry.equilibration_triggers[*equilibration_triggers*]
(link:#pypalmsens.methods.settings.EquilibrationTriggers[EquilibrationTriggers])
–
* link:#pypalmsens.DifferentialPulseVoltammetry.measurement_triggers[*measurement_triggers*]
(link:#pypalmsens.methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.DifferentialPulseVoltammetry.data_processing[*data_processing*]
(link:#pypalmsens.methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.multiplexer[*multiplexer*]
(link:#pypalmsens.methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.general[*general*]
(link:#pypalmsens.methods.settings.General[General]) –

==== equilibration_time

[source,python]
----
equilibration_time: float = 0.0
----

==== begin_potential

[source,python]
----
begin_potential: float = -0.5
----

==== end_potential

[source,python]
----
end_potential: float = 0.5
----

==== step_potential

[source,python]
----
step_potential: float = 0.1
----

==== pulse_potential

[source,python]
----
pulse_potential: float = 0.05
----

==== pulse_time

[source,python]
----
pulse_time: float = 0.01
----

==== scan_rate

[source,python]
----
scan_rate: float = 1.0
----

==== record_auxiliary_input

[source,python]
----
record_auxiliary_input: bool = False
----

==== record_cell_potential

[source,python]
----
record_cell_potential: bool = False
----

==== record_we_potential

[source,python]
----
record_we_potential: bool = False
----

==== enable_bipot_current

[source,python]
----
enable_bipot_current: bool = False
----

==== current_ranges

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== pretreatment

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== versus_ocp

[source,python]
----
versus_ocp: VersusOCP = attrs.field(factory=VersusOCP)
----

==== bipot

[source,python]
----
bipot: BiPot = attrs.field(factory=BiPot)
----

==== post_measurement

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== ir_drop

[source,python]
----
ir_drop: IrDropCompensation = attrs.field(factory=IrDropCompensation)
----

==== equilibration_triggers

[source,python]
----
equilibration_triggers: EquilibrationTriggers = attrs.field(factory=EquilibrationTriggers)
----

==== measurement_triggers

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== data_processing

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== multiplexer

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== general

[source,python]
----
general: General = attrs.field(factory=General)
----

=== ElectrochemicalImpedanceSpectroscopy

Bases: link:#pypalmsens.methods.techniques.BaseConfig[BaseConfig]

Create potentiometry method parameters.

*Attributes:*

* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.equilibration_time[*equilibration_time*]
(link:#float[float]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.dc_potential[*dc_potential*]
(link:#float[float]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.ac_potential[*ac_potential*]
(link:#float[float]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.n_frequencies[*n_frequencies*]
(link:#int[int]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.max_frequency[*max_frequency*]
(link:#float[float]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.min_frequency[*min_frequency*]
(link:#float[float]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.current_ranges[*current_ranges*]
(link:#pypalmsens.methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.potential_ranges[*potential_ranges*]
(link:#pypalmsens.methods.settings.PotentialRanges[PotentialRanges]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.pretreatment[*pretreatment*]
(link:#pypalmsens.methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.versus_ocp[*versus_ocp*]
(link:#pypalmsens.methods.settings.VersusOCP[VersusOCP]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.post_measurement[*post_measurement*]
(link:#pypalmsens.methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.measurement_triggers[*measurement_triggers*]
(link:#pypalmsens.methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.equilibration_triggers[*equilibration_triggers*]
(link:#pypalmsens.methods.settings.EquilibrationTriggers[EquilibrationTriggers])
–
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.multiplexer[*multiplexer*]
(link:#pypalmsens.methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.general[*general*]
(link:#pypalmsens.methods.settings.General[General]) –

==== equilibration_time

[source,python]
----
equilibration_time: float = 0.0
----

==== dc_potential

[source,python]
----
dc_potential: float = 0.0
----

==== ac_potential

[source,python]
----
ac_potential: float = 0.01
----

==== n_frequencies

[source,python]
----
n_frequencies: int = 11
----

==== max_frequency

[source,python]
----
max_frequency: float = 100000.0
----

==== min_frequency

[source,python]
----
min_frequency: float = 1000.0
----

==== current_ranges

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== potential_ranges

[source,python]
----
potential_ranges: PotentialRanges = attrs.field(factory=PotentialRanges)
----

==== pretreatment

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== versus_ocp

[source,python]
----
versus_ocp: VersusOCP = attrs.field(factory=VersusOCP)
----

==== post_measurement

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== measurement_triggers

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== equilibration_triggers

[source,python]
----
equilibration_triggers: EquilibrationTriggers = attrs.field(factory=EquilibrationTriggers)
----

==== multiplexer

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== general

[source,python]
----
general: General = attrs.field(factory=General)
----

=== GalvanostaticImpedanceSpectroscopy

Bases: link:#pypalmsens.methods.techniques.BaseConfig[BaseConfig]

Create potentiometry method parameters.

*Attributes:*

* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.applied_current_range[*applied_current_range*]
(link:#pypalmsens.methods._shared.CURRENT_RANGE[CURRENT_RANGE]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.equilibration_time[*equilibration_time*]
(link:#float[float]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.ac_current[*ac_current*]
(link:#float[float]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.dc_current[*dc_current*]
(link:#float[float]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.n_frequencies[*n_frequencies*]
(link:#int[int]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.max_frequency[*max_frequency*]
(link:#float[float]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.min_frequency[*min_frequency*]
(link:#float[float]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.current_ranges[*current_ranges*]
(link:#pypalmsens.methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.potential_ranges[*potential_ranges*]
(link:#pypalmsens.methods.settings.PotentialRanges[PotentialRanges]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.pretreatment[*pretreatment*]
(link:#pypalmsens.methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.post_measurement[*post_measurement*]
(link:#pypalmsens.methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.equilibration_triggers[*equilibration_triggers*]
(link:#pypalmsens.methods.settings.EquilibrationTriggers[EquilibrationTriggers])
–
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.measurement_triggers[*measurement_triggers*]
(link:#pypalmsens.methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.multiplexer[*multiplexer*]
(link:#pypalmsens.methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.general[*general*]
(link:#pypalmsens.methods.settings.General[General]) –

==== applied_current_range

[source,python]
----
applied_current_range: CURRENT_RANGE = CURRENT_RANGE.cr_100_uA
----

==== equilibration_time

[source,python]
----
equilibration_time: float = 0.0
----

==== ac_current

[source,python]
----
ac_current: float = 0.01
----

==== dc_current

[source,python]
----
dc_current: float = 0.0
----

==== n_frequencies

[source,python]
----
n_frequencies: int = 11
----

==== max_frequency

[source,python]
----
max_frequency: float = 100000.0
----

==== min_frequency

[source,python]
----
min_frequency: float = 1000.0
----

==== current_ranges

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== potential_ranges

[source,python]
----
potential_ranges: PotentialRanges = attrs.field(factory=PotentialRanges)
----

==== pretreatment

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== post_measurement

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== equilibration_triggers

[source,python]
----
equilibration_triggers: EquilibrationTriggers = attrs.field(factory=EquilibrationTriggers)
----

==== measurement_triggers

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== multiplexer

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== general

[source,python]
----
general: General = attrs.field(factory=General)
----

=== LinearSweepVoltammetry

Bases: link:#pypalmsens.methods.techniques.BaseConfig[BaseConfig]

Create linear sweep method parameters.

*Attributes:*

* link:#pypalmsens.LinearSweepVoltammetry.begin_potential[*begin_potential*]
(link:#float[float]) –
* link:#pypalmsens.LinearSweepVoltammetry.end_potential[*end_potential*]
(link:#float[float]) –
* link:#pypalmsens.LinearSweepVoltammetry.step_potential[*step_potential*]
(link:#float[float]) –
* link:#pypalmsens.LinearSweepVoltammetry.scanrate[*scanrate*]
(link:#float[float]) –
* link:#pypalmsens.LinearSweepVoltammetry.record_auxiliary_input[*record_auxiliary_input*]
(link:#bool[bool]) –
* link:#pypalmsens.LinearSweepVoltammetry.record_cell_potential[*record_cell_potential*]
(link:#bool[bool]) –
* link:#pypalmsens.LinearSweepVoltammetry.record_we_potential[*record_we_potential*]
(link:#bool[bool]) –
* link:#pypalmsens.LinearSweepVoltammetry.enable_bipot_current[*enable_bipot_current*]
(link:#bool[bool]) –
* link:#pypalmsens.LinearSweepVoltammetry.current_ranges[*current_ranges*]
(link:#pypalmsens.methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.LinearSweepVoltammetry.pretreatment[*pretreatment*]
(link:#pypalmsens.methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.LinearSweepVoltammetry.versus_ocp[*versus_ocp*]
(link:#pypalmsens.methods.settings.VersusOCP[VersusOCP]) –
* link:#pypalmsens.LinearSweepVoltammetry.bipot[*bipot*]
(link:#pypalmsens.methods.settings.BiPot[BiPot]) –
* link:#pypalmsens.LinearSweepVoltammetry.post_measurement[*post_measurement*]
(link:#pypalmsens.methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.LinearSweepVoltammetry.current_limits[*current_limits*]
(link:#pypalmsens.methods.settings.CurrentLimits[CurrentLimits]) –
* link:#pypalmsens.LinearSweepVoltammetry.ir_drop[*ir_drop*]
(link:#pypalmsens.methods.settings.IrDropCompensation[IrDropCompensation])
–
* link:#pypalmsens.LinearSweepVoltammetry.equilibration_triggers[*equilibration_triggers*]
(link:#pypalmsens.methods.settings.EquilibrationTriggers[EquilibrationTriggers])
–
* link:#pypalmsens.LinearSweepVoltammetry.measurement_triggers[*measurement_triggers*]
(link:#pypalmsens.methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.LinearSweepVoltammetry.data_processing[*data_processing*]
(link:#pypalmsens.methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.LinearSweepVoltammetry.multiplexer[*multiplexer*]
(link:#pypalmsens.methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.LinearSweepVoltammetry.general[*general*]
(link:#pypalmsens.methods.settings.General[General]) –

==== begin_potential

[source,python]
----
begin_potential: float = -0.5
----

==== end_potential

[source,python]
----
end_potential: float = 0.5
----

==== step_potential

[source,python]
----
step_potential: float = 0.1
----

==== scanrate

[source,python]
----
scanrate: float = 1.0
----

==== record_auxiliary_input

[source,python]
----
record_auxiliary_input: bool = False
----

==== record_cell_potential

[source,python]
----
record_cell_potential: bool = False
----

==== record_we_potential

[source,python]
----
record_we_potential: bool = False
----

==== enable_bipot_current

[source,python]
----
enable_bipot_current: bool = False
----

==== current_ranges

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== pretreatment

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== versus_ocp

[source,python]
----
versus_ocp: VersusOCP = attrs.field(factory=VersusOCP)
----

==== bipot

[source,python]
----
bipot: BiPot = attrs.field(factory=BiPot)
----

==== post_measurement

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== current_limits

[source,python]
----
current_limits: CurrentLimits = attrs.field(factory=CurrentLimits)
----

==== ir_drop

[source,python]
----
ir_drop: IrDropCompensation = attrs.field(factory=IrDropCompensation)
----

==== equilibration_triggers

[source,python]
----
equilibration_triggers: EquilibrationTriggers = attrs.field(factory=EquilibrationTriggers)
----

==== measurement_triggers

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== data_processing

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== multiplexer

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== general

[source,python]
----
general: General = attrs.field(factory=General)
----

=== MethodScript

Bases: link:#pypalmsens.methods.techniques.BaseConfig[BaseConfig]

Create a method script sandbox object.

*Attributes:*

* link:#pypalmsens.MethodScript.script[*script*] (link:#str[str]) –

==== script

[source,python]
----
script: str = 'e\nwait 100m\nif 1 < 2\n    send_string "Hello world"\nendif\n\n'
----

=== MultiStepAmperometry

Bases: link:#pypalmsens.methods.techniques.BaseConfig[BaseConfig]

Create multi-step amperometry method parameters.

*Attributes:*

* link:#pypalmsens.MultiStepAmperometry.equilibration_time[*equilibration_time*]
(link:#float[float]) –
* link:#pypalmsens.MultiStepAmperometry.interval_time[*interval_time*]
(link:#float[float]) –
* link:#pypalmsens.MultiStepAmperometry.n_cycles[*n_cycles*]
(link:#float[float]) –
* link:#pypalmsens.MultiStepAmperometry.levels[*levels*]
(link:#list[list][link:#pypalmsens.methods._shared.ELevel[ELevel]]) –
* link:#pypalmsens.MultiStepAmperometry.record_auxiliary_input[*record_auxiliary_input*]
(link:#bool[bool]) –
* link:#pypalmsens.MultiStepAmperometry.record_cell_potential[*record_cell_potential*]
(link:#bool[bool]) –
* link:#pypalmsens.MultiStepAmperometry.record_we_potential[*record_we_potential*]
(link:#bool[bool]) –
* link:#pypalmsens.MultiStepAmperometry.enable_bipot_current[*enable_bipot_current*]
(link:#bool[bool]) –
* link:#pypalmsens.MultiStepAmperometry.current_ranges[*current_ranges*]
(link:#pypalmsens.methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.MultiStepAmperometry.pretreatment[*pretreatment*]
(link:#pypalmsens.methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.MultiStepAmperometry.bipot[*bipot*]
(link:#pypalmsens.methods.settings.BiPot[BiPot]) –
* link:#pypalmsens.MultiStepAmperometry.post_measurement[*post_measurement*]
(link:#pypalmsens.methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.MultiStepAmperometry.current_limits[*current_limits*]
(link:#pypalmsens.methods.settings.CurrentLimits[CurrentLimits]) –
* link:#pypalmsens.MultiStepAmperometry.ir_drop[*ir_drop*]
(link:#pypalmsens.methods.settings.IrDropCompensation[IrDropCompensation])
–
* link:#pypalmsens.MultiStepAmperometry.data_processing[*data_processing*]
(link:#pypalmsens.methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.MultiStepAmperometry.multiplexer[*multiplexer*]
(link:#pypalmsens.methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.MultiStepAmperometry.general[*general*]
(link:#pypalmsens.methods.settings.General[General]) –

==== equilibration_time

[source,python]
----
equilibration_time: float = 0.0
----

==== interval_time

[source,python]
----
interval_time: float = 0.1
----

==== n_cycles

[source,python]
----
n_cycles: float = 1
----

==== levels

[source,python]
----
levels: list[ELevel] = attrs.field(factory=(lambda: [ELevel()]))
----

==== record_auxiliary_input

[source,python]
----
record_auxiliary_input: bool = False
----

==== record_cell_potential

[source,python]
----
record_cell_potential: bool = False
----

==== record_we_potential

[source,python]
----
record_we_potential: bool = False
----

==== enable_bipot_current

[source,python]
----
enable_bipot_current: bool = False
----

==== current_ranges

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== pretreatment

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== bipot

[source,python]
----
bipot: BiPot = attrs.field(factory=BiPot)
----

==== post_measurement

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== current_limits

[source,python]
----
current_limits: CurrentLimits = attrs.field(factory=CurrentLimits)
----

==== ir_drop

[source,python]
----
ir_drop: IrDropCompensation = attrs.field(factory=IrDropCompensation)
----

==== data_processing

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== multiplexer

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== general

[source,python]
----
general: General = attrs.field(factory=General)
----

=== OpenCircuitPotentiometry

Bases: link:#pypalmsens.methods.techniques.BaseConfig[BaseConfig]

Create open circuit potentiometry method parameters.

*Attributes:*

* link:#pypalmsens.OpenCircuitPotentiometry.interval_time[*interval_time*]
(link:#float[float]) –
* link:#pypalmsens.OpenCircuitPotentiometry.run_time[*run_time*]
(link:#float[float]) –
* link:#pypalmsens.OpenCircuitPotentiometry.record_auxiliary_input[*record_auxiliary_input*]
(link:#bool[bool]) –
* link:#pypalmsens.OpenCircuitPotentiometry.record_we_current[*record_we_current*]
(link:#bool[bool]) –
* link:#pypalmsens.OpenCircuitPotentiometry.record_we_current_range[*record_we_current_range*]
(link:#pypalmsens.methods._shared.CURRENT_RANGE[CURRENT_RANGE]) –
* link:#pypalmsens.OpenCircuitPotentiometry.current_ranges[*current_ranges*]
(link:#pypalmsens.methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.OpenCircuitPotentiometry.potential_ranges[*potential_ranges*]
(link:#pypalmsens.methods.settings.PotentialRanges[PotentialRanges]) –
* link:#pypalmsens.OpenCircuitPotentiometry.pretreatment[*pretreatment*]
(link:#pypalmsens.methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.OpenCircuitPotentiometry.post_measurement[*post_measurement*]
(link:#pypalmsens.methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.OpenCircuitPotentiometry.potential_limits[*potential_limits*]
(link:#pypalmsens.methods.settings.PotentialLimits[PotentialLimits]) –
* link:#pypalmsens.OpenCircuitPotentiometry.measurement_triggers[*measurement_triggers*]
(link:#pypalmsens.methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.OpenCircuitPotentiometry.data_processing[*data_processing*]
(link:#pypalmsens.methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.OpenCircuitPotentiometry.multiplexer[*multiplexer*]
(link:#pypalmsens.methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.OpenCircuitPotentiometry.general[*general*]
(link:#pypalmsens.methods.settings.General[General]) –

==== interval_time

[source,python]
----
interval_time: float = 0.1
----

==== run_time

[source,python]
----
run_time: float = 1.0
----

==== record_auxiliary_input

[source,python]
----
record_auxiliary_input: bool = False
----

==== record_we_current

[source,python]
----
record_we_current: bool = False
----

==== record_we_current_range

[source,python]
----
record_we_current_range: CURRENT_RANGE = CURRENT_RANGE.cr_1_uA
----

==== current_ranges

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== potential_ranges

[source,python]
----
potential_ranges: PotentialRanges = attrs.field(factory=PotentialRanges)
----

==== pretreatment

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== post_measurement

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== potential_limits

[source,python]
----
potential_limits: PotentialLimits = attrs.field(factory=PotentialLimits)
----

==== measurement_triggers

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== data_processing

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== multiplexer

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== general

[source,python]
----
general: General = attrs.field(factory=General)
----

=== SquareWaveVoltammetry

Bases: link:#pypalmsens.methods.techniques.BaseConfig[BaseConfig]

Create square wave method parameters.

*Attributes:*

* link:#pypalmsens.SquareWaveVoltammetry.equilibration_time[*equilibration_time*]
(link:#float[float]) –
* link:#pypalmsens.SquareWaveVoltammetry.begin_potential[*begin_potential*]
(link:#float[float]) –
* link:#pypalmsens.SquareWaveVoltammetry.end_potential[*end_potential*]
(link:#float[float]) –
* link:#pypalmsens.SquareWaveVoltammetry.step_potential[*step_potential*]
(link:#float[float]) –
* link:#pypalmsens.SquareWaveVoltammetry.frequency[*frequency*]
(link:#float[float]) –
* link:#pypalmsens.SquareWaveVoltammetry.amplitude[*amplitude*]
(link:#float[float]) –
* link:#pypalmsens.SquareWaveVoltammetry.record_auxiliary_input[*record_auxiliary_input*]
(link:#bool[bool]) –
* link:#pypalmsens.SquareWaveVoltammetry.record_cell_potential[*record_cell_potential*]
(link:#bool[bool]) –
* link:#pypalmsens.SquareWaveVoltammetry.record_we_potential[*record_we_potential*]
(link:#bool[bool]) –
* link:#pypalmsens.SquareWaveVoltammetry.enable_bipot_current[*enable_bipot_current*]
(link:#bool[bool]) –
* link:#pypalmsens.SquareWaveVoltammetry.record_forward_and_reverse_currents[*record_forward_and_reverse_currents*]
(link:#bool[bool]) –
* link:#pypalmsens.SquareWaveVoltammetry.current_ranges[*current_ranges*]
(link:#pypalmsens.methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.SquareWaveVoltammetry.pretreatment[*pretreatment*]
(link:#pypalmsens.methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.SquareWaveVoltammetry.versus_ocp[*versus_ocp*]
(link:#pypalmsens.methods.settings.VersusOCP[VersusOCP]) –
* link:#pypalmsens.SquareWaveVoltammetry.bipot[*bipot*]
(link:#pypalmsens.methods.settings.BiPot[BiPot]) –
* link:#pypalmsens.SquareWaveVoltammetry.post_measurement[*post_measurement*]
(link:#pypalmsens.methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.SquareWaveVoltammetry.ir_drop[*ir_drop*]
(link:#pypalmsens.methods.settings.IrDropCompensation[IrDropCompensation])
–
* link:#pypalmsens.SquareWaveVoltammetry.equilibration_triggers[*equilibration_triggers*]
(link:#pypalmsens.methods.settings.EquilibrationTriggers[EquilibrationTriggers])
–
* link:#pypalmsens.SquareWaveVoltammetry.measurement_triggers[*measurement_triggers*]
(link:#pypalmsens.methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.SquareWaveVoltammetry.data_processing[*data_processing*]
(link:#pypalmsens.methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.SquareWaveVoltammetry.multiplexer[*multiplexer*]
(link:#pypalmsens.methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.SquareWaveVoltammetry.general[*general*]
(link:#pypalmsens.methods.settings.General[General]) –

==== equilibration_time

[source,python]
----
equilibration_time: float = 0.0
----

==== begin_potential

[source,python]
----
begin_potential: float = -0.5
----

==== end_potential

[source,python]
----
end_potential: float = 0.5
----

==== step_potential

[source,python]
----
step_potential: float = 0.1
----

==== frequency

[source,python]
----
frequency: float = 10.0
----

==== amplitude

[source,python]
----
amplitude: float = 0.05
----

==== record_auxiliary_input

[source,python]
----
record_auxiliary_input: bool = False
----

==== record_cell_potential

[source,python]
----
record_cell_potential: bool = False
----

==== record_we_potential

[source,python]
----
record_we_potential: bool = False
----

==== enable_bipot_current

[source,python]
----
enable_bipot_current: bool = False
----

==== record_forward_and_reverse_currents

[source,python]
----
record_forward_and_reverse_currents: bool = False
----

==== current_ranges

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== pretreatment

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== versus_ocp

[source,python]
----
versus_ocp: VersusOCP = attrs.field(factory=VersusOCP)
----

==== bipot

[source,python]
----
bipot: BiPot = attrs.field(factory=BiPot)
----

==== post_measurement

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== ir_drop

[source,python]
----
ir_drop: IrDropCompensation = attrs.field(factory=IrDropCompensation)
----

==== equilibration_triggers

[source,python]
----
equilibration_triggers: EquilibrationTriggers = attrs.field(factory=EquilibrationTriggers)
----

==== measurement_triggers

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== data_processing

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== multiplexer

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== general

[source,python]
----
general: General = attrs.field(factory=General)
----
