== `pypalmsens`

*Classes:*

* link:#pypalmsens.ChronoAmperometry[*ChronoAmperometry*] – Create
chrono amperometry method parameters.
* link:#pypalmsens.ChronoPotentiometry[*ChronoPotentiometry*] – Create
potentiometry method parameters.
* link:#pypalmsens.CyclicVoltammetry[*CyclicVoltammetry*] – Create
cyclic voltammetry method parameters.
* link:#pypalmsens.DifferentialPulseVoltammetry[*DifferentialPulseVoltammetry*]
– Create square wave method parameters.
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy[*ElectrochemicalImpedanceSpectroscopy*]
– Create potentiometry method parameters.
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy[*GalvanostaticImpedanceSpectroscopy*]
– Create potentiometry method parameters.
* link:#pypalmsens.LinearSweepVoltammetry[*LinearSweepVoltammetry*] –
Create linear sweep method parameters.
* link:#pypalmsens.MethodScript[*MethodScript*] – Create a method script
sandbox object.
* link:#pypalmsens.MultiStepAmperometry[*MultiStepAmperometry*] – Create
multi-step amperometry method parameters.
* link:#pypalmsens.OpenCircuitPotentiometry[*OpenCircuitPotentiometry*]
– Create open circuit potentiometry method parameters.
* link:#pypalmsens.SquareWaveVoltammetry[*SquareWaveVoltammetry*] –
Create square wave method parameters.

=== `ChronoAmperometry`

Bases:
link:#pypalmsens._methods.techniques.MethodSettings[MethodSettings]

Create chrono amperometry method parameters.

*Attributes:*

* link:#pypalmsens.ChronoAmperometry.equilibration_time[*equilibration++_++time*]
(link:#float[float]) – Equilibration time in s.
* link:#pypalmsens.ChronoAmperometry.interval_time[*interval++_++time*]
(link:#float[float]) – Interval time in s.
* link:#pypalmsens.ChronoAmperometry.potential[*potential*]
(link:#float[float]) – Potential in V.
* link:#pypalmsens.ChronoAmperometry.run_time[*run++_++time*]
(link:#float[float]) – Run time in s.
* link:#pypalmsens.ChronoAmperometry.enable_bipot_current[*enable++_++bipot++_++current*]
(link:#bool[bool]) – Enable bipot current.
* link:#pypalmsens.ChronoAmperometry.record_auxiliary_input[*record++_++auxiliary++_++input*]
(link:#bool[bool]) – Record auxiliary input.
* link:#pypalmsens.ChronoAmperometry.record_cell_potential[*record++_++cell++_++potential*]
(link:#bool[bool]) – Record cell potential.
* link:#pypalmsens.ChronoAmperometry.record_we_potential[*record++_++we++_++potential*]
(link:#bool[bool]) – Record applied working electrode potential.
* link:#pypalmsens.ChronoAmperometry.current_ranges[*current++_++ranges*]
(link:#pypalmsens._methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.ChronoAmperometry.pretreatment[*pretreatment*]
(link:#pypalmsens._methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.ChronoAmperometry.versus_ocp[*versus++_++ocp*]
(link:#pypalmsens._methods.settings.VersusOCP[VersusOCP]) –
* link:#pypalmsens.ChronoAmperometry.bipot[*bipot*]
(link:#pypalmsens._methods.settings.BiPot[BiPot]) –
* link:#pypalmsens.ChronoAmperometry.post_measurement[*post++_++measurement*]
(link:#pypalmsens._methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.ChronoAmperometry.current_limits[*current++_++limits*]
(link:#pypalmsens._methods.settings.CurrentLimits[CurrentLimits]) –
* link:#pypalmsens.ChronoAmperometry.charge_limits[*charge++_++limits*]
(link:#pypalmsens._methods.settings.ChargeLimits[ChargeLimits]) –
* link:#pypalmsens.ChronoAmperometry.ir_drop[*ir++_++drop*]
(link:#pypalmsens._methods.settings.IrDropCompensation[IrDropCompensation])
–
* link:#pypalmsens.ChronoAmperometry.equilibration_triggers[*equilibration++_++triggers*]
(link:#pypalmsens._methods.settings.EquilibrationTriggers[EquilibrationTriggers])
–
* link:#pypalmsens.ChronoAmperometry.measurement_triggers[*measurement++_++triggers*]
(link:#pypalmsens._methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.ChronoAmperometry.data_processing[*data++_++processing*]
(link:#pypalmsens._methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.ChronoAmperometry.multiplexer[*multiplexer*]
(link:#pypalmsens._methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.ChronoAmperometry.general[*general*]
(link:#pypalmsens._methods.settings.General[General]) –

==== `equilibration++_++time`

[source,python]
----
equilibration_time: float = 0.0
----

Equilibration time in s.

==== `interval++_++time`

[source,python]
----
interval_time: float = 0.1
----

Interval time in s.

==== `potential`

[source,python]
----
potential: float = 0.0
----

Potential in V.

==== `run++_++time`

[source,python]
----
run_time: float = 1.0
----

Run time in s.

==== `enable++_++bipot++_++current`

[source,python]
----
enable_bipot_current: bool = False
----

Enable bipot current.

==== `record++_++auxiliary++_++input`

[source,python]
----
record_auxiliary_input: bool = False
----

Record auxiliary input.

==== `record++_++cell++_++potential`

[source,python]
----
record_cell_potential: bool = False
----

Record cell potential.

Counter electrode vs ground.

==== `record++_++we++_++potential`

[source,python]
----
record_we_potential: bool = False
----

Record applied working electrode potential.

Reference electrode vs ground.

==== `current++_++ranges`

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== `pretreatment`

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== `versus++_++ocp`

[source,python]
----
versus_ocp: VersusOCP = attrs.field(factory=VersusOCP)
----

==== `bipot`

[source,python]
----
bipot: BiPot = attrs.field(factory=BiPot)
----

==== `post++_++measurement`

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== `current++_++limits`

[source,python]
----
current_limits: CurrentLimits = attrs.field(factory=CurrentLimits)
----

==== `charge++_++limits`

[source,python]
----
charge_limits: ChargeLimits = attrs.field(factory=ChargeLimits)
----

==== `ir++_++drop`

[source,python]
----
ir_drop: IrDropCompensation = attrs.field(factory=IrDropCompensation)
----

==== `equilibration++_++triggers`

[source,python]
----
equilibration_triggers: EquilibrationTriggers = attrs.field(factory=EquilibrationTriggers)
----

==== `measurement++_++triggers`

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== `data++_++processing`

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== `multiplexer`

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== `general`

[source,python]
----
general: General = attrs.field(factory=General)
----

=== `ChronoPotentiometry`

Bases:
link:#pypalmsens._methods.techniques.MethodSettings[MethodSettings]

Create potentiometry method parameters.

*Attributes:*

* link:#pypalmsens.ChronoPotentiometry.current[*current*]
(link:#float[float]) – The current to apply in the given current range.
* link:#pypalmsens.ChronoPotentiometry.applied_current_range[*applied++_++current++_++range*]
(link:#pypalmsens._methods._shared.CURRENT_RANGE[CURRENT++_++RANGE]) –
Applied current range.
* link:#pypalmsens.ChronoPotentiometry.interval_time[*interval++_++time*]
(link:#float[float]) – Interval time in s (default: 0.1)
* link:#pypalmsens.ChronoPotentiometry.run_time[*run++_++time*]
(link:#float[float]) – Run time in s (default: 1.0)
* link:#pypalmsens.ChronoPotentiometry.record_auxiliary_input[*record++_++auxiliary++_++input*]
(link:#bool[bool]) – Record auxiliary input.
* link:#pypalmsens.ChronoPotentiometry.record_cell_potential[*record++_++cell++_++potential*]
(link:#bool[bool]) – Record cell potential.
* link:#pypalmsens.ChronoPotentiometry.record_we_current[*record++_++we++_++current*]
(link:#bool[bool]) – Record working electrode current.
* link:#pypalmsens.ChronoPotentiometry.current_ranges[*current++_++ranges*]
(link:#pypalmsens._methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.ChronoPotentiometry.potential_ranges[*potential++_++ranges*]
(link:#pypalmsens._methods.settings.PotentialRanges[PotentialRanges]) –
* link:#pypalmsens.ChronoPotentiometry.pretreatment[*pretreatment*]
(link:#pypalmsens._methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.ChronoPotentiometry.post_measurement[*post++_++measurement*]
(link:#pypalmsens._methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.ChronoPotentiometry.potential_limits[*potential++_++limits*]
(link:#pypalmsens._methods.settings.PotentialLimits[PotentialLimits]) –
* link:#pypalmsens.ChronoPotentiometry.measurement_triggers[*measurement++_++triggers*]
(link:#pypalmsens._methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.ChronoPotentiometry.data_processing[*data++_++processing*]
(link:#pypalmsens._methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.ChronoPotentiometry.multiplexer[*multiplexer*]
(link:#pypalmsens._methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.ChronoPotentiometry.general[*general*]
(link:#pypalmsens._methods.settings.General[General]) –

==== `current`

[source,python]
----
current: float = 0.0
----

The current to apply in the given current range.

Note that this value acts as a multiplier in the applied current range.

So if 10 uA is the applied current range and 1.5 is given as current
value, the applied current will be 15 uA.

==== `applied++_++current++_++range`

[source,python]
----
applied_current_range: CURRENT_RANGE = CURRENT_RANGE.cr_100_uA
----

Applied current range.

Use `CURRENT++_++RANGE` to define the range.

==== `interval++_++time`

[source,python]
----
interval_time: float = 0.1
----

Interval time in s (default: 0.1)

==== `run++_++time`

[source,python]
----
run_time: float = 1.0
----

Run time in s (default: 1.0)

==== `record++_++auxiliary++_++input`

[source,python]
----
record_auxiliary_input: bool = False
----

Record auxiliary input.

==== `record++_++cell++_++potential`

[source,python]
----
record_cell_potential: bool = False
----

Record cell potential.

Counter electrode vs ground.

==== `record++_++we++_++current`

[source,python]
----
record_we_current: bool = False
----

Record working electrode current.

==== `current++_++ranges`

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== `potential++_++ranges`

[source,python]
----
potential_ranges: PotentialRanges = attrs.field(factory=PotentialRanges)
----

==== `pretreatment`

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== `post++_++measurement`

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== `potential++_++limits`

[source,python]
----
potential_limits: PotentialLimits = attrs.field(factory=PotentialLimits)
----

==== `measurement++_++triggers`

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== `data++_++processing`

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== `multiplexer`

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== `general`

[source,python]
----
general: General = attrs.field(factory=General)
----

=== `CyclicVoltammetry`

Bases:
link:#pypalmsens._methods.techniques.MethodSettings[MethodSettings]

Create cyclic voltammetry method parameters.

*Attributes:*

* link:#pypalmsens.CyclicVoltammetry.equilibration_time[*equilibration++_++time*]
(link:#float[float]) – Equilibration time in s
* link:#pypalmsens.CyclicVoltammetry.begin_potential[*begin++_++potential*]
(link:#float[float]) – Begin potential in V
* link:#pypalmsens.CyclicVoltammetry.vertex1_potential[*vertex1++_++potential*]
(link:#float[float]) – Vertex 1 potential in V
* link:#pypalmsens.CyclicVoltammetry.vertex2_potential[*vertex2++_++potential*]
(link:#float[float]) – Vertex 2 potential in V
* link:#pypalmsens.CyclicVoltammetry.step_potential[*step++_++potential*]
(link:#float[float]) – Step potential in V
* link:#pypalmsens.CyclicVoltammetry.scanrate[*scanrate*]
(link:#float[float]) – Scan rate in V/s
* link:#pypalmsens.CyclicVoltammetry.n_scans[*n++_++scans*]
(link:#float[float]) – Number of scans
* link:#pypalmsens.CyclicVoltammetry.enable_bipot_current[*enable++_++bipot++_++current*]
(link:#bool[bool]) – Enable bipot current.
* link:#pypalmsens.CyclicVoltammetry.record_auxiliary_input[*record++_++auxiliary++_++input*]
(link:#bool[bool]) – Record auxiliary input.
* link:#pypalmsens.CyclicVoltammetry.record_cell_potential[*record++_++cell++_++potential*]
(link:#bool[bool]) – Record cell potential.
* link:#pypalmsens.CyclicVoltammetry.record_we_potential[*record++_++we++_++potential*]
(link:#bool[bool]) – Record applied working electrode potential.
* link:#pypalmsens.CyclicVoltammetry.current_ranges[*current++_++ranges*]
(link:#pypalmsens._methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.CyclicVoltammetry.pretreatment[*pretreatment*]
(link:#pypalmsens._methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.CyclicVoltammetry.versus_ocp[*versus++_++ocp*]
(link:#pypalmsens._methods.settings.VersusOCP[VersusOCP]) –
* link:#pypalmsens.CyclicVoltammetry.post_measurement[*post++_++measurement*]
(link:#pypalmsens._methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.CyclicVoltammetry.current_limits[*current++_++limits*]
(link:#pypalmsens._methods.settings.CurrentLimits[CurrentLimits]) –
* link:#pypalmsens.CyclicVoltammetry.ir_drop_compensation[*ir++_++drop++_++compensation*]
(link:#pypalmsens._methods.settings.IrDropCompensation[IrDropCompensation])
–
* link:#pypalmsens.CyclicVoltammetry.equilibrion_triggers[*equilibrion++_++triggers*]
(link:#pypalmsens._methods.settings.EquilibrationTriggers[EquilibrationTriggers])
–
* link:#pypalmsens.CyclicVoltammetry.measurement_triggers[*measurement++_++triggers*]
(link:#pypalmsens._methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.CyclicVoltammetry.data_processing[*data++_++processing*]
(link:#pypalmsens._methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.CyclicVoltammetry.general[*general*]
(link:#pypalmsens._methods.settings.General[General]) –

==== `equilibration++_++time`

[source,python]
----
equilibration_time: float = 0.0
----

Equilibration time in s

==== `begin++_++potential`

[source,python]
----
begin_potential: float = -0.5
----

Begin potential in V

==== `vertex1++_++potential`

[source,python]
----
vertex1_potential: float = 0.5
----

Vertex 1 potential in V

==== `vertex2++_++potential`

[source,python]
----
vertex2_potential: float = -0.5
----

Vertex 2 potential in V

==== `step++_++potential`

[source,python]
----
step_potential: float = 0.1
----

Step potential in V

==== `scanrate`

[source,python]
----
scanrate: float = 1.0
----

Scan rate in V/s

==== `n++_++scans`

[source,python]
----
n_scans: float = 1
----

Number of scans

==== `enable++_++bipot++_++current`

[source,python]
----
enable_bipot_current: bool = False
----

Enable bipot current.

==== `record++_++auxiliary++_++input`

[source,python]
----
record_auxiliary_input: bool = False
----

Record auxiliary input.

==== `record++_++cell++_++potential`

[source,python]
----
record_cell_potential: bool = False
----

Record cell potential.

Counter electrode vs ground.

==== `record++_++we++_++potential`

[source,python]
----
record_we_potential: bool = False
----

Record applied working electrode potential.

Reference electrode vs ground.

==== `current++_++ranges`

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== `pretreatment`

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== `versus++_++ocp`

[source,python]
----
versus_ocp: VersusOCP = attrs.field(factory=VersusOCP)
----

==== `post++_++measurement`

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== `current++_++limits`

[source,python]
----
current_limits: CurrentLimits = attrs.field(factory=CurrentLimits)
----

==== `ir++_++drop++_++compensation`

[source,python]
----
ir_drop_compensation: IrDropCompensation = attrs.field(factory=IrDropCompensation)
----

==== `equilibrion++_++triggers`

[source,python]
----
equilibrion_triggers: EquilibrationTriggers = attrs.field(factory=EquilibrationTriggers)
----

==== `measurement++_++triggers`

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== `data++_++processing`

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== `general`

[source,python]
----
general: General = attrs.field(factory=General)
----

=== `DifferentialPulseVoltammetry`

Bases:
link:#pypalmsens._methods.techniques.MethodSettings[MethodSettings]

Create square wave method parameters.

*Attributes:*

* link:#pypalmsens.DifferentialPulseVoltammetry.equilibration_time[*equilibration++_++time*]
(link:#float[float]) – Equilibration time in s.
* link:#pypalmsens.DifferentialPulseVoltammetry.begin_potential[*begin++_++potential*]
(link:#float[float]) – Begin potential in V.
* link:#pypalmsens.DifferentialPulseVoltammetry.end_potential[*end++_++potential*]
(link:#float[float]) – End potential in V.
* link:#pypalmsens.DifferentialPulseVoltammetry.step_potential[*step++_++potential*]
(link:#float[float]) – Step potential in V.
* link:#pypalmsens.DifferentialPulseVoltammetry.pulse_potential[*pulse++_++potential*]
(link:#float[float]) – Pulse potential in V.
* link:#pypalmsens.DifferentialPulseVoltammetry.pulse_time[*pulse++_++time*]
(link:#float[float]) – Pulse time in s.
* link:#pypalmsens.DifferentialPulseVoltammetry.scan_rate[*scan++_++rate*]
(link:#float[float]) – Scan rate (potential/time) in V/s.
* link:#pypalmsens.DifferentialPulseVoltammetry.enable_bipot_current[*enable++_++bipot++_++current*]
(link:#bool[bool]) – Enable bipot current.
* link:#pypalmsens.DifferentialPulseVoltammetry.record_auxiliary_input[*record++_++auxiliary++_++input*]
(link:#bool[bool]) – Record auxiliary input.
* link:#pypalmsens.DifferentialPulseVoltammetry.record_cell_potential[*record++_++cell++_++potential*]
(link:#bool[bool]) – Record cell potential.
* link:#pypalmsens.DifferentialPulseVoltammetry.record_we_potential[*record++_++we++_++potential*]
(link:#bool[bool]) – Record applied working electrode potential.
* link:#pypalmsens.DifferentialPulseVoltammetry.current_ranges[*current++_++ranges*]
(link:#pypalmsens._methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.pretreatment[*pretreatment*]
(link:#pypalmsens._methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.versus_ocp[*versus++_++ocp*]
(link:#pypalmsens._methods.settings.VersusOCP[VersusOCP]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.bipot[*bipot*]
(link:#pypalmsens._methods.settings.BiPot[BiPot]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.post_measurement[*post++_++measurement*]
(link:#pypalmsens._methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.ir_drop[*ir++_++drop*]
(link:#pypalmsens._methods.settings.IrDropCompensation[IrDropCompensation])
–
* link:#pypalmsens.DifferentialPulseVoltammetry.equilibration_triggers[*equilibration++_++triggers*]
(link:#pypalmsens._methods.settings.EquilibrationTriggers[EquilibrationTriggers])
–
* link:#pypalmsens.DifferentialPulseVoltammetry.measurement_triggers[*measurement++_++triggers*]
(link:#pypalmsens._methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.DifferentialPulseVoltammetry.data_processing[*data++_++processing*]
(link:#pypalmsens._methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.multiplexer[*multiplexer*]
(link:#pypalmsens._methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.DifferentialPulseVoltammetry.general[*general*]
(link:#pypalmsens._methods.settings.General[General]) –

==== `equilibration++_++time`

[source,python]
----
equilibration_time: float = 0.0
----

Equilibration time in s.

==== `begin++_++potential`

[source,python]
----
begin_potential: float = -0.5
----

Begin potential in V.

==== `end++_++potential`

[source,python]
----
end_potential: float = 0.5
----

End potential in V.

==== `step++_++potential`

[source,python]
----
step_potential: float = 0.1
----

Step potential in V.

==== `pulse++_++potential`

[source,python]
----
pulse_potential: float = 0.05
----

Pulse potential in V.

==== `pulse++_++time`

[source,python]
----
pulse_time: float = 0.01
----

Pulse time in s.

==== `scan++_++rate`

[source,python]
----
scan_rate: float = 1.0
----

Scan rate (potential/time) in V/s.

==== `enable++_++bipot++_++current`

[source,python]
----
enable_bipot_current: bool = False
----

Enable bipot current.

==== `record++_++auxiliary++_++input`

[source,python]
----
record_auxiliary_input: bool = False
----

Record auxiliary input.

==== `record++_++cell++_++potential`

[source,python]
----
record_cell_potential: bool = False
----

Record cell potential.

Counter electrode vs ground.

==== `record++_++we++_++potential`

[source,python]
----
record_we_potential: bool = False
----

Record applied working electrode potential.

Reference electrode vs ground.

==== `current++_++ranges`

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== `pretreatment`

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== `versus++_++ocp`

[source,python]
----
versus_ocp: VersusOCP = attrs.field(factory=VersusOCP)
----

==== `bipot`

[source,python]
----
bipot: BiPot = attrs.field(factory=BiPot)
----

==== `post++_++measurement`

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== `ir++_++drop`

[source,python]
----
ir_drop: IrDropCompensation = attrs.field(factory=IrDropCompensation)
----

==== `equilibration++_++triggers`

[source,python]
----
equilibration_triggers: EquilibrationTriggers = attrs.field(factory=EquilibrationTriggers)
----

==== `measurement++_++triggers`

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== `data++_++processing`

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== `multiplexer`

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== `general`

[source,python]
----
general: General = attrs.field(factory=General)
----

=== `ElectrochemicalImpedanceSpectroscopy`

Bases:
link:#pypalmsens._methods.techniques.MethodSettings[MethodSettings]

Create potentiometry method parameters.

*Attributes:*

* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.equilibration_time[*equilibration++_++time*]
(link:#float[float]) – Equilibration time in s.
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.dc_potential[*dc++_++potential*]
(link:#float[float]) – DC potential in V.
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.ac_potential[*ac++_++potential*]
(link:#float[float]) – AC potential in V RMS.
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.n_frequencies[*n++_++frequencies*]
(link:#int[int]) – Number of frequencies.
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.max_frequency[*max++_++frequency*]
(link:#float[float]) – Maximum frequency in Hz.
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.min_frequency[*min++_++frequency*]
(link:#float[float]) – Minimum frequency in Hz.
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.current_ranges[*current++_++ranges*]
(link:#pypalmsens._methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.potential_ranges[*potential++_++ranges*]
(link:#pypalmsens._methods.settings.PotentialRanges[PotentialRanges]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.pretreatment[*pretreatment*]
(link:#pypalmsens._methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.versus_ocp[*versus++_++ocp*]
(link:#pypalmsens._methods.settings.VersusOCP[VersusOCP]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.post_measurement[*post++_++measurement*]
(link:#pypalmsens._methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.measurement_triggers[*measurement++_++triggers*]
(link:#pypalmsens._methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.equilibration_triggers[*equilibration++_++triggers*]
(link:#pypalmsens._methods.settings.EquilibrationTriggers[EquilibrationTriggers])
–
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.multiplexer[*multiplexer*]
(link:#pypalmsens._methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.ElectrochemicalImpedanceSpectroscopy.general[*general*]
(link:#pypalmsens._methods.settings.General[General]) –

==== `equilibration++_++time`

[source,python]
----
equilibration_time: float = 0.0
----

Equilibration time in s.

==== `dc++_++potential`

[source,python]
----
dc_potential: float = 0.0
----

DC potential in V.

==== `ac++_++potential`

[source,python]
----
ac_potential: float = 0.01
----

AC potential in V RMS.

==== `n++_++frequencies`

[source,python]
----
n_frequencies: int = 11
----

Number of frequencies.

==== `max++_++frequency`

[source,python]
----
max_frequency: float = 100000.0
----

Maximum frequency in Hz.

==== `min++_++frequency`

[source,python]
----
min_frequency: float = 1000.0
----

Minimum frequency in Hz.

==== `current++_++ranges`

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== `potential++_++ranges`

[source,python]
----
potential_ranges: PotentialRanges = attrs.field(factory=PotentialRanges)
----

==== `pretreatment`

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== `versus++_++ocp`

[source,python]
----
versus_ocp: VersusOCP = attrs.field(factory=VersusOCP)
----

==== `post++_++measurement`

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== `measurement++_++triggers`

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== `equilibration++_++triggers`

[source,python]
----
equilibration_triggers: EquilibrationTriggers = attrs.field(factory=EquilibrationTriggers)
----

==== `multiplexer`

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== `general`

[source,python]
----
general: General = attrs.field(factory=General)
----

=== `GalvanostaticImpedanceSpectroscopy`

Bases:
link:#pypalmsens._methods.techniques.MethodSettings[MethodSettings]

Create potentiometry method parameters.

*Attributes:*

* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.applied_current_range[*applied++_++current++_++range*]
(link:#pypalmsens._methods._shared.CURRENT_RANGE[CURRENT++_++RANGE]) –
Applied current range.
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.equilibration_time[*equilibration++_++time*]
(link:#float[float]) – Equilibration time in s.
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.ac_current[*ac++_++current*]
(link:#float[float]) – AC current in applied current range RMS.
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.dc_current[*dc++_++current*]
(link:#float[float]) – DC current in applied current range.
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.n_frequencies[*n++_++frequencies*]
(link:#int[int]) – Number of frequencies.
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.max_frequency[*max++_++frequency*]
(link:#float[float]) – Maximum frequency in Hz.
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.min_frequency[*min++_++frequency*]
(link:#float[float]) – Minimum frequency in Hz.
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.current_ranges[*current++_++ranges*]
(link:#pypalmsens._methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.potential_ranges[*potential++_++ranges*]
(link:#pypalmsens._methods.settings.PotentialRanges[PotentialRanges]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.pretreatment[*pretreatment*]
(link:#pypalmsens._methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.post_measurement[*post++_++measurement*]
(link:#pypalmsens._methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.equilibration_triggers[*equilibration++_++triggers*]
(link:#pypalmsens._methods.settings.EquilibrationTriggers[EquilibrationTriggers])
–
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.measurement_triggers[*measurement++_++triggers*]
(link:#pypalmsens._methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.multiplexer[*multiplexer*]
(link:#pypalmsens._methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.GalvanostaticImpedanceSpectroscopy.general[*general*]
(link:#pypalmsens._methods.settings.General[General]) –

==== `applied++_++current++_++range`

[source,python]
----
applied_current_range: CURRENT_RANGE = CURRENT_RANGE.cr_100_uA
----

Applied current range.

Use `CURRENT++_++RANGE` to define the range.

==== `equilibration++_++time`

[source,python]
----
equilibration_time: float = 0.0
----

Equilibration time in s.

==== `ac++_++current`

[source,python]
----
ac_current: float = 0.01
----

AC current in applied current range RMS.

==== `dc++_++current`

[source,python]
----
dc_current: float = 0.0
----

DC current in applied current range.

==== `n++_++frequencies`

[source,python]
----
n_frequencies: int = 11
----

Number of frequencies.

==== `max++_++frequency`

[source,python]
----
max_frequency: float = 100000.0
----

Maximum frequency in Hz.

==== `min++_++frequency`

[source,python]
----
min_frequency: float = 1000.0
----

Minimum frequency in Hz.

==== `current++_++ranges`

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== `potential++_++ranges`

[source,python]
----
potential_ranges: PotentialRanges = attrs.field(factory=PotentialRanges)
----

==== `pretreatment`

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== `post++_++measurement`

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== `equilibration++_++triggers`

[source,python]
----
equilibration_triggers: EquilibrationTriggers = attrs.field(factory=EquilibrationTriggers)
----

==== `measurement++_++triggers`

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== `multiplexer`

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== `general`

[source,python]
----
general: General = attrs.field(factory=General)
----

=== `LinearSweepVoltammetry`

Bases:
link:#pypalmsens._methods.techniques.MethodSettings[MethodSettings]

Create linear sweep method parameters.

*Attributes:*

* link:#pypalmsens.LinearSweepVoltammetry.begin_potential[*begin++_++potential*]
(link:#float[float]) – Begin potential in V.
* link:#pypalmsens.LinearSweepVoltammetry.end_potential[*end++_++potential*]
(link:#float[float]) – End potential in V.
* link:#pypalmsens.LinearSweepVoltammetry.step_potential[*step++_++potential*]
(link:#float[float]) – Step potential in V.
* link:#pypalmsens.LinearSweepVoltammetry.scanrate[*scanrate*]
(link:#float[float]) – Scan rate in V/s.
* link:#pypalmsens.LinearSweepVoltammetry.enable_bipot_current[*enable++_++bipot++_++current*]
(link:#bool[bool]) – Enable bipot current.
* link:#pypalmsens.LinearSweepVoltammetry.record_auxiliary_input[*record++_++auxiliary++_++input*]
(link:#bool[bool]) – Record auxiliary input.
* link:#pypalmsens.LinearSweepVoltammetry.record_cell_potential[*record++_++cell++_++potential*]
(link:#bool[bool]) – Record cell potential.
* link:#pypalmsens.LinearSweepVoltammetry.record_we_potential[*record++_++we++_++potential*]
(link:#bool[bool]) – Record applied working electrode potential.
* link:#pypalmsens.LinearSweepVoltammetry.current_ranges[*current++_++ranges*]
(link:#pypalmsens._methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.LinearSweepVoltammetry.pretreatment[*pretreatment*]
(link:#pypalmsens._methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.LinearSweepVoltammetry.versus_ocp[*versus++_++ocp*]
(link:#pypalmsens._methods.settings.VersusOCP[VersusOCP]) –
* link:#pypalmsens.LinearSweepVoltammetry.bipot[*bipot*]
(link:#pypalmsens._methods.settings.BiPot[BiPot]) –
* link:#pypalmsens.LinearSweepVoltammetry.post_measurement[*post++_++measurement*]
(link:#pypalmsens._methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.LinearSweepVoltammetry.current_limits[*current++_++limits*]
(link:#pypalmsens._methods.settings.CurrentLimits[CurrentLimits]) –
* link:#pypalmsens.LinearSweepVoltammetry.ir_drop[*ir++_++drop*]
(link:#pypalmsens._methods.settings.IrDropCompensation[IrDropCompensation])
–
* link:#pypalmsens.LinearSweepVoltammetry.equilibration_triggers[*equilibration++_++triggers*]
(link:#pypalmsens._methods.settings.EquilibrationTriggers[EquilibrationTriggers])
–
* link:#pypalmsens.LinearSweepVoltammetry.measurement_triggers[*measurement++_++triggers*]
(link:#pypalmsens._methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.LinearSweepVoltammetry.data_processing[*data++_++processing*]
(link:#pypalmsens._methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.LinearSweepVoltammetry.multiplexer[*multiplexer*]
(link:#pypalmsens._methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.LinearSweepVoltammetry.general[*general*]
(link:#pypalmsens._methods.settings.General[General]) –

==== `begin++_++potential`

[source,python]
----
begin_potential: float = -0.5
----

Begin potential in V.

==== `end++_++potential`

[source,python]
----
end_potential: float = 0.5
----

End potential in V.

==== `step++_++potential`

[source,python]
----
step_potential: float = 0.1
----

Step potential in V.

==== `scanrate`

[source,python]
----
scanrate: float = 1.0
----

Scan rate in V/s.

==== `enable++_++bipot++_++current`

[source,python]
----
enable_bipot_current: bool = False
----

Enable bipot current.

==== `record++_++auxiliary++_++input`

[source,python]
----
record_auxiliary_input: bool = False
----

Record auxiliary input.

==== `record++_++cell++_++potential`

[source,python]
----
record_cell_potential: bool = False
----

Record cell potential.

Counter electrode vs ground.

==== `record++_++we++_++potential`

[source,python]
----
record_we_potential: bool = False
----

Record applied working electrode potential.

Reference electrode vs ground.

==== `current++_++ranges`

[source,python]
----
current_ranges: CurrentRanges = CurrentRanges()
----

==== `pretreatment`

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== `versus++_++ocp`

[source,python]
----
versus_ocp: VersusOCP = attrs.field(factory=VersusOCP)
----

==== `bipot`

[source,python]
----
bipot: BiPot = attrs.field(factory=BiPot)
----

==== `post++_++measurement`

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== `current++_++limits`

[source,python]
----
current_limits: CurrentLimits = attrs.field(factory=CurrentLimits)
----

==== `ir++_++drop`

[source,python]
----
ir_drop: IrDropCompensation = attrs.field(factory=IrDropCompensation)
----

==== `equilibration++_++triggers`

[source,python]
----
equilibration_triggers: EquilibrationTriggers = attrs.field(factory=EquilibrationTriggers)
----

==== `measurement++_++triggers`

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== `data++_++processing`

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== `multiplexer`

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== `general`

[source,python]
----
general: General = attrs.field(factory=General)
----

=== `MethodScript`

Bases:
link:#pypalmsens._methods.techniques.MethodSettings[MethodSettings]

Create a method script sandbox object.

*Attributes:*

* link:#pypalmsens.MethodScript.script[*script*] (link:#str[str]) –
Script to run.

==== `script`

[source,python]
----
script: str = 'e\nwait 100m\nif 1 < 2\n    send_string "Hello world"\nendif\n\n'
----

Script to run.

For more info on MethodSCRIPT, see:
https://www.palmsens.com/methodscript/ for more information.

=== `MultiStepAmperometry`

Bases:
link:#pypalmsens._methods.techniques.MethodSettings[MethodSettings]

Create multi-step amperometry method parameters.

*Attributes:*

* link:#pypalmsens.MultiStepAmperometry.equilibration_time[*equilibration++_++time*]
(link:#float[float]) – Equilibration time in s.
* link:#pypalmsens.MultiStepAmperometry.interval_time[*interval++_++time*]
(link:#float[float]) – Interval time in s.
* link:#pypalmsens.MultiStepAmperometry.n_cycles[*n++_++cycles*]
(link:#float[float]) – Number of cycles.
* link:#pypalmsens.MultiStepAmperometry.levels[*levels*]
(link:#list[list]++[++link:#pypalmsens._methods._shared.ELevel[ELevel]++]++)
– List of levels.
* link:#pypalmsens.MultiStepAmperometry.enable_bipot_current[*enable++_++bipot++_++current*]
(link:#bool[bool]) – Enable bipot current.
* link:#pypalmsens.MultiStepAmperometry.record_auxiliary_input[*record++_++auxiliary++_++input*]
(link:#bool[bool]) – Record auxiliary input.
* link:#pypalmsens.MultiStepAmperometry.record_cell_potential[*record++_++cell++_++potential*]
(link:#bool[bool]) – Record cell potential.
* link:#pypalmsens.MultiStepAmperometry.record_we_potential[*record++_++we++_++potential*]
(link:#bool[bool]) – Record applied working electrode potential.
* link:#pypalmsens.MultiStepAmperometry.current_ranges[*current++_++ranges*]
(link:#pypalmsens._methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.MultiStepAmperometry.pretreatment[*pretreatment*]
(link:#pypalmsens._methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.MultiStepAmperometry.bipot[*bipot*]
(link:#pypalmsens._methods.settings.BiPot[BiPot]) –
* link:#pypalmsens.MultiStepAmperometry.post_measurement[*post++_++measurement*]
(link:#pypalmsens._methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.MultiStepAmperometry.current_limits[*current++_++limits*]
(link:#pypalmsens._methods.settings.CurrentLimits[CurrentLimits]) –
* link:#pypalmsens.MultiStepAmperometry.ir_drop[*ir++_++drop*]
(link:#pypalmsens._methods.settings.IrDropCompensation[IrDropCompensation])
–
* link:#pypalmsens.MultiStepAmperometry.data_processing[*data++_++processing*]
(link:#pypalmsens._methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.MultiStepAmperometry.multiplexer[*multiplexer*]
(link:#pypalmsens._methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.MultiStepAmperometry.general[*general*]
(link:#pypalmsens._methods.settings.General[General]) –

==== `equilibration++_++time`

[source,python]
----
equilibration_time: float = 0.0
----

Equilibration time in s.

==== `interval++_++time`

[source,python]
----
interval_time: float = 0.1
----

Interval time in s.

==== `n++_++cycles`

[source,python]
----
n_cycles: float = 1
----

Number of cycles.

==== `levels`

[source,python]
----
levels: list[ELevel] = attrs.field(factory=(lambda: [ELevel()]))
----

List of levels.

Use `ELevel()` to create levels.

==== `enable++_++bipot++_++current`

[source,python]
----
enable_bipot_current: bool = False
----

Enable bipot current.

==== `record++_++auxiliary++_++input`

[source,python]
----
record_auxiliary_input: bool = False
----

Record auxiliary input.

==== `record++_++cell++_++potential`

[source,python]
----
record_cell_potential: bool = False
----

Record cell potential.

Counter electrode vs ground.

==== `record++_++we++_++potential`

[source,python]
----
record_we_potential: bool = False
----

Record applied working electrode potential.

Reference electrode vs ground.

==== `current++_++ranges`

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== `pretreatment`

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== `bipot`

[source,python]
----
bipot: BiPot = attrs.field(factory=BiPot)
----

==== `post++_++measurement`

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== `current++_++limits`

[source,python]
----
current_limits: CurrentLimits = attrs.field(factory=CurrentLimits)
----

==== `ir++_++drop`

[source,python]
----
ir_drop: IrDropCompensation = attrs.field(factory=IrDropCompensation)
----

==== `data++_++processing`

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== `multiplexer`

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== `general`

[source,python]
----
general: General = attrs.field(factory=General)
----

=== `OpenCircuitPotentiometry`

Bases:
link:#pypalmsens._methods.techniques.MethodSettings[MethodSettings]

Create open circuit potentiometry method parameters.

*Attributes:*

* link:#pypalmsens.OpenCircuitPotentiometry.interval_time[*interval++_++time*]
(link:#float[float]) – Interval time in s.
* link:#pypalmsens.OpenCircuitPotentiometry.run_time[*run++_++time*]
(link:#float[float]) – Run time in s.
* link:#pypalmsens.OpenCircuitPotentiometry.record_auxiliary_input[*record++_++auxiliary++_++input*]
(link:#bool[bool]) – Record auxiliary input.
* link:#pypalmsens.OpenCircuitPotentiometry.record_we_current[*record++_++we++_++current*]
(link:#bool[bool]) – Record working electrode current.
* link:#pypalmsens.OpenCircuitPotentiometry.record_we_current_range[*record++_++we++_++current++_++range*]
(link:#pypalmsens._methods._shared.CURRENT_RANGE[CURRENT++_++RANGE]) –
Record working electrode current range.
* link:#pypalmsens.OpenCircuitPotentiometry.current_ranges[*current++_++ranges*]
(link:#pypalmsens._methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.OpenCircuitPotentiometry.potential_ranges[*potential++_++ranges*]
(link:#pypalmsens._methods.settings.PotentialRanges[PotentialRanges]) –
* link:#pypalmsens.OpenCircuitPotentiometry.pretreatment[*pretreatment*]
(link:#pypalmsens._methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.OpenCircuitPotentiometry.post_measurement[*post++_++measurement*]
(link:#pypalmsens._methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.OpenCircuitPotentiometry.potential_limits[*potential++_++limits*]
(link:#pypalmsens._methods.settings.PotentialLimits[PotentialLimits]) –
* link:#pypalmsens.OpenCircuitPotentiometry.measurement_triggers[*measurement++_++triggers*]
(link:#pypalmsens._methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.OpenCircuitPotentiometry.data_processing[*data++_++processing*]
(link:#pypalmsens._methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.OpenCircuitPotentiometry.multiplexer[*multiplexer*]
(link:#pypalmsens._methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.OpenCircuitPotentiometry.general[*general*]
(link:#pypalmsens._methods.settings.General[General]) –

==== `interval++_++time`

[source,python]
----
interval_time: float = 0.1
----

Interval time in s.

==== `run++_++time`

[source,python]
----
run_time: float = 1.0
----

Run time in s.

==== `record++_++auxiliary++_++input`

[source,python]
----
record_auxiliary_input: bool = False
----

Record auxiliary input.

==== `record++_++we++_++current`

[source,python]
----
record_we_current: bool = False
----

Record working electrode current.

==== `record++_++we++_++current++_++range`

[source,python]
----
record_we_current_range: CURRENT_RANGE = CURRENT_RANGE.cr_1_uA
----

Record working electrode current range.

Use `CURRENT++_++RANGE` to define the range.

==== `current++_++ranges`

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== `potential++_++ranges`

[source,python]
----
potential_ranges: PotentialRanges = attrs.field(factory=PotentialRanges)
----

==== `pretreatment`

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== `post++_++measurement`

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== `potential++_++limits`

[source,python]
----
potential_limits: PotentialLimits = attrs.field(factory=PotentialLimits)
----

==== `measurement++_++triggers`

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== `data++_++processing`

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== `multiplexer`

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== `general`

[source,python]
----
general: General = attrs.field(factory=General)
----

=== `SquareWaveVoltammetry`

Bases:
link:#pypalmsens._methods.techniques.MethodSettings[MethodSettings]

Create square wave method parameters.

*Attributes:*

* link:#pypalmsens.SquareWaveVoltammetry.equilibration_time[*equilibration++_++time*]
(link:#float[float]) – Equilibration time in s.
* link:#pypalmsens.SquareWaveVoltammetry.begin_potential[*begin++_++potential*]
(link:#float[float]) – Begin potential in V.
* link:#pypalmsens.SquareWaveVoltammetry.end_potential[*end++_++potential*]
(link:#float[float]) – End potential in V.
* link:#pypalmsens.SquareWaveVoltammetry.step_potential[*step++_++potential*]
(link:#float[float]) – Step potential in V.
* link:#pypalmsens.SquareWaveVoltammetry.frequency[*frequency*]
(link:#float[float]) – Frequency in Hz.
* link:#pypalmsens.SquareWaveVoltammetry.amplitude[*amplitude*]
(link:#float[float]) – Amplitude in V as half peak-to-peak value.
* link:#pypalmsens.SquareWaveVoltammetry.enable_bipot_current[*enable++_++bipot++_++current*]
(link:#bool[bool]) – Enable bipot current.
* link:#pypalmsens.SquareWaveVoltammetry.record_auxiliary_input[*record++_++auxiliary++_++input*]
(link:#bool[bool]) – Record auxiliary input.
* link:#pypalmsens.SquareWaveVoltammetry.record_cell_potential[*record++_++cell++_++potential*]
(link:#bool[bool]) – Record cell potential.
* link:#pypalmsens.SquareWaveVoltammetry.record_we_potential[*record++_++we++_++potential*]
(link:#bool[bool]) – Record applied working electrode potential.
* link:#pypalmsens.SquareWaveVoltammetry.record_forward_and_reverse_currents[*record++_++forward++_++and++_++reverse++_++currents*]
(link:#bool[bool]) – Record forward and reverse currents
* link:#pypalmsens.SquareWaveVoltammetry.current_ranges[*current++_++ranges*]
(link:#pypalmsens._methods.settings.CurrentRanges[CurrentRanges]) –
* link:#pypalmsens.SquareWaveVoltammetry.pretreatment[*pretreatment*]
(link:#pypalmsens._methods.settings.Pretreatment[Pretreatment]) –
* link:#pypalmsens.SquareWaveVoltammetry.versus_ocp[*versus++_++ocp*]
(link:#pypalmsens._methods.settings.VersusOCP[VersusOCP]) –
* link:#pypalmsens.SquareWaveVoltammetry.bipot[*bipot*]
(link:#pypalmsens._methods.settings.BiPot[BiPot]) –
* link:#pypalmsens.SquareWaveVoltammetry.post_measurement[*post++_++measurement*]
(link:#pypalmsens._methods.settings.PostMeasurement[PostMeasurement]) –
* link:#pypalmsens.SquareWaveVoltammetry.ir_drop[*ir++_++drop*]
(link:#pypalmsens._methods.settings.IrDropCompensation[IrDropCompensation])
–
* link:#pypalmsens.SquareWaveVoltammetry.equilibration_triggers[*equilibration++_++triggers*]
(link:#pypalmsens._methods.settings.EquilibrationTriggers[EquilibrationTriggers])
–
* link:#pypalmsens.SquareWaveVoltammetry.measurement_triggers[*measurement++_++triggers*]
(link:#pypalmsens._methods.settings.MeasurementTriggers[MeasurementTriggers])
–
* link:#pypalmsens.SquareWaveVoltammetry.data_processing[*data++_++processing*]
(link:#pypalmsens._methods.settings.DataProcessing[DataProcessing]) –
* link:#pypalmsens.SquareWaveVoltammetry.multiplexer[*multiplexer*]
(link:#pypalmsens._methods.settings.Multiplexer[Multiplexer]) –
* link:#pypalmsens.SquareWaveVoltammetry.general[*general*]
(link:#pypalmsens._methods.settings.General[General]) –

==== `equilibration++_++time`

[source,python]
----
equilibration_time: float = 0.0
----

Equilibration time in s.

==== `begin++_++potential`

[source,python]
----
begin_potential: float = -0.5
----

Begin potential in V.

==== `end++_++potential`

[source,python]
----
end_potential: float = 0.5
----

End potential in V.

==== `step++_++potential`

[source,python]
----
step_potential: float = 0.1
----

Step potential in V.

==== `frequency`

[source,python]
----
frequency: float = 10.0
----

Frequency in Hz.

==== `amplitude`

[source,python]
----
amplitude: float = 0.05
----

Amplitude in V as half peak-to-peak value.

==== `enable++_++bipot++_++current`

[source,python]
----
enable_bipot_current: bool = False
----

Enable bipot current.

==== `record++_++auxiliary++_++input`

[source,python]
----
record_auxiliary_input: bool = False
----

Record auxiliary input.

==== `record++_++cell++_++potential`

[source,python]
----
record_cell_potential: bool = False
----

Record cell potential.

Counter electrode vs ground.

==== `record++_++we++_++potential`

[source,python]
----
record_we_potential: bool = False
----

Record applied working electrode potential.

Reference electrode vs ground.

==== `record++_++forward++_++and++_++reverse++_++currents`

[source,python]
----
record_forward_and_reverse_currents: bool = False
----

Record forward and reverse currents

==== `current++_++ranges`

[source,python]
----
current_ranges: CurrentRanges = attrs.field(factory=CurrentRanges)
----

==== `pretreatment`

[source,python]
----
pretreatment: Pretreatment = attrs.field(factory=Pretreatment)
----

==== `versus++_++ocp`

[source,python]
----
versus_ocp: VersusOCP = attrs.field(factory=VersusOCP)
----

==== `bipot`

[source,python]
----
bipot: BiPot = attrs.field(factory=BiPot)
----

==== `post++_++measurement`

[source,python]
----
post_measurement: PostMeasurement = attrs.field(factory=PostMeasurement)
----

==== `ir++_++drop`

[source,python]
----
ir_drop: IrDropCompensation = attrs.field(factory=IrDropCompensation)
----

==== `equilibration++_++triggers`

[source,python]
----
equilibration_triggers: EquilibrationTriggers = attrs.field(factory=EquilibrationTriggers)
----

==== `measurement++_++triggers`

[source,python]
----
measurement_triggers: MeasurementTriggers = attrs.field(factory=MeasurementTriggers)
----

==== `data++_++processing`

[source,python]
----
data_processing: DataProcessing = attrs.field(factory=DataProcessing)
----

==== `multiplexer`

[source,python]
----
multiplexer: Multiplexer = attrs.field(factory=Multiplexer)
----

==== `general`

[source,python]
----
general: General = attrs.field(factory=General)
----
