= .NET MAUI SDK for PalmSens devices

WARNING: The .NET MAUI SDK is under active development and not ready for use. 🚧

With this PalmSens Software Development Kit you develop Windows applications in Visual Studio using .NET MAUI[https://dotnet.microsoft.com/en-us/apps/maui].
.NET MAUI is a multi-platform app UI framework that lets you build native, cross-platform desktop and mobile apps with one codebase.
The PalmSens .NET MAUI SDK can be used with all PalmSens instruments and potentiostat modules.

Supported platforms:

* Windows
* Android (under development)
// * IOS
// * MacOS

== Contents of the PalmSens SDK

The PalmSens SDK contains the following libraries and projects:

*PalmSens.Core.dll & PalmSens.Core.Windows.dll:*

These libraries contain the namespaces with all the necessary files for
using PalmSens/EmStat devices in

your software.

* PalmSens All necessary classes and functions for performing
measurements and

____
doing analysis with PalmSens or EmStat.
____

* PalmSens.Comm For Serial, USB or TCP communication with PalmSens or
EmStat
* PalmSens.DataFiles For saving and loading method and data files
* PalmSens.Devices For handling communications and device capabilities
* PalmSens.Techniques Contains all measurement techniques for PalmSens
and EmStat
* PalmSens.Units Contains a collection of units used by these libraries

*PalmSens.Core.Windows.BLE.dll*

This is an optional library to add Bluetooth Low Energy support to your
project (Windows 10 only).

*PalmSens.Core.Simplified.csproj &
PalmSens.Core.Simplified.WinForms.csproj:*

These projects contain an open source wrapper for the PalmSens.Core.dll
& PalmSens.Core.Windows.dll. This wrapper gives you quick and easy
access to all the basic functions of the PalmSens/EmStat devices and
automatically handles most potential threading issues for you:

* Connecting
* Manual control of the cell
* Running measurements
* Accessing and processing measured data
* Analyzing and manipulating data

*SDKPlot.csproj and SDKPlot.WinForms.csproj*

These projects contain a simple open source plot control that you can
use to plot your measurements in real-time.

*OxyPlot.dll and OxyPlot.WindowsForms.dll:*

These libraries required when using the SDK’s plot based on the open
source OxyPlot library, http://www.oxyplot.org/.

== Compatible devices and firmware

The PalmSens .NET MAUI SDK is based on PalmSens core version 5.12 which is compatible with:

[cols=",",options="header",]
|===
|Device |Minimum required firmware version
|EmStat |3.7
|EmStat2 |7.7
|EmStat3 |7.7
|EmStat3{plus} |7.7
|EmStat4 |1.3
|EmStat4T |1.4
|EmStat Go |7.7
|EmStat Pico |1.5
|Sensit Smart |1.5
|Sensit BT |1.5
|Sensit Wearable |1.5
|MultiEmStat3 |7.7
|MultiEmStat4 |1.3
|PalmSens3 |2.8
|PalmSens4 |1.7
|MultiPalmSens4 |1.7
|===
