= PalmSens .NET MAUI Documentation

{empty} +
{empty}

image::banner.svg[PalmSens banner, width=80%]

{empty} +
{empty}

With this PalmSens SDK you develop Windows applications in Visual Studio using https://dotnet.microsoft.com/en-us/apps/maui[.NET MAUI].

..NET MAUI is a multi-platform app UI framework that lets you build native, cross-platform desktop and mobile apps with one codebase.
The PalmSens .NET MAUI SDK can be used with all PalmSens instruments and potentiostat modules.

https://github.com/PalmSens/PalmSens_SDK/releases[Click here to download the latest release].

Supported platforms:

* Windows
* Android
// * IOS
// * MacOS

== Contents

These projects contain a simplified open source wrapper for the xref:start:ROOT:core.adoc[`PalmSens.Core`] libraries.

* `PalmSens.Core.Simplified`
* `PalmSens.Core.Simplified.MAUI`
* `PalmSens.Core.Simplified.Android`
* `PalmSens.Core.Simplified.WinUI`

The simplified wrappers give you quick and easy access to all the basic functions of the PalmSens/EmStat devices and automatically handles most potential threading issues for you:

* Connecting
* Manual control of the cell
* Running measurements
* Accessing and processing measured data
* Analyzing and manipulating data

Methods and data structures are referenced from the xref:start:ROOT:core.adoc[`PalmSens.Core`] libraries.

In addition, the projects contain a simple open source plot control that you can use to plot your measurements in real-time.
They are based on the open-source http://www.oxyplot.org/[OxyPlot library].

* `SDKPlot.NET`
* `SDKPlot.Maui`

Click xref:examples.adoc[here] for a list of examples!

== Compatible devices and firmware

The PalmSens .NET MAUI SDK is based on PalmSens Core version 5.12 which is compatible with:

[cols=",",options="header",]
|===
|Device |Minimum required firmware version
|EmStat |3.7
|EmStat2 |7.7
|EmStat3 |7.7
|EmStat3{plus} |7.7
|EmStat4 |1.3
|EmStat4T |1.4
|EmStat Go |7.7
|EmStat Pico |1.5
|Sensit Smart |1.5
|Sensit BT |1.5
|Sensit Wearable |1.5
|MultiEmStat3 |7.7
|MultiEmStat4 |1.3
|PalmSens3 |2.8
|PalmSens4 |1.7
|MultiPalmSens4 |1.7
|===
